// AUTO-GENERATED by scripts/pullDistressedCRE.js — REAL ATTOM data (SF/Oakland commercial),
// distress-PROXY scored (no NOD flag on this ATTOM key). Regenerate to refresh.
export const CRE_DISTRESSED = [
  {
    "attomId": 40543593,
    "address": "325 BATTERY ST, SAN FRANCISCO, CA 94111",
    "submarket": "Financial District",
    "lat": 37.794289,
    "lng": -122.400785,
    "propType": "OFFICE & SHOWROOM",
    "lastSale": 143000000,
    "lastSaleDate": "2020-02-13",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 75,
    "distressBand": "RED",
    "distressReasons": [
      "Office bought at 2019–21 peak — distressed class",
      "Institutional-scale office ($50M+)"
    ]
  },
  {
    "attomId": 28234881,
    "address": "1333 BROADWAY, OAKLAND, CA 94612",
    "submarket": "Oakland CBD",
    "lat": 37.804175,
    "lng": -122.271902,
    "propType": "OFFICE & SHOWROOM",
    "lastSale": 115430000,
    "lastSaleDate": "2019-05-20",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 75,
    "distressBand": "RED",
    "distressReasons": [
      "Office bought at 2019–21 peak — distressed class",
      "Institutional-scale office ($50M+)"
    ]
  },
  {
    "attomId": 155705824,
    "address": "275 BATTERY ST, SAN FRANCISCO, CA 94111",
    "submarket": "Financial District",
    "lat": 37.793863,
    "lng": -122.400374,
    "propType": "OFFICE & SHOWROOM",
    "lastSale": 306200000,
    "lastSaleDate": "2014-12-22",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 30,
    "distressBand": "YELLOW",
    "distressReasons": [
      "Institutional-scale office ($50M+)",
      "Stale ownership (pre-2018)"
    ]
  },
  {
    "attomId": 155705827,
    "address": "475 SACRAMENTO ST, SAN FRANCISCO, CA 94111",
    "submarket": "Financial District",
    "lat": 37.793823,
    "lng": -122.400686,
    "propType": "OFFICE & SHOWROOM",
    "lastSale": 306200000,
    "lastSaleDate": "2014-12-22",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 30,
    "distressBand": "YELLOW",
    "distressReasons": [
      "Institutional-scale office ($50M+)",
      "Stale ownership (pre-2018)"
    ]
  },
  {
    "attomId": 51253700,
    "address": "280 BATTERY ST, SAN FRANCISCO, CA 94111",
    "submarket": "Financial District",
    "lat": 37.79403,
    "lng": -122.399927,
    "propType": "OFFICE BUILDING",
    "lastSale": 65000000,
    "lastSaleDate": "1999-04-20",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 30,
    "distressBand": "YELLOW",
    "distressReasons": [
      "Institutional-scale office ($50M+)",
      "Stale ownership (pre-2018)"
    ]
  },
  {
    "attomId": 51166154,
    "address": "353 SACRAMENTO ST, SAN FRANCISCO, CA 94111",
    "submarket": "Financial District",
    "lat": 37.794053,
    "lng": -122.399752,
    "propType": "OFFICE BUILDING",
    "lastSale": 65000000,
    "lastSaleDate": "1999-04-20",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 30,
    "distressBand": "YELLOW",
    "distressReasons": [
      "Institutional-scale office ($50M+)",
      "Stale ownership (pre-2018)"
    ]
  },
  {
    "attomId": 157647988,
    "address": "1330 BROADWAY STE 1050, OAKLAND, CA 94612",
    "submarket": "Oakland CBD",
    "lat": 37.803907,
    "lng": -122.270818,
    "propType": "OFFICE & SHOWROOM",
    "lastSale": 176000000,
    "lastSaleDate": "2018-07-26",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 20,
    "distressBand": "GREEN",
    "distressReasons": [
      "Institutional-scale office ($50M+)"
    ]
  },
  {
    "attomId": 43120688,
    "address": "114 FREELON ST, SAN FRANCISCO, CA 94107",
    "submarket": "SoMa",
    "lat": 37.778558,
    "lng": -122.397587,
    "propType": "CONDOMINIUM",
    "lastSale": 1295000,
    "lastSaleDate": "2003-02-14",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 10,
    "distressBand": "GREEN",
    "distressReasons": [
      "Stale ownership (pre-2018)"
    ]
  },
  {
    "attomId": 156199971,
    "address": "118 FREELON ST, SAN FRANCISCO, CA 94107",
    "submarket": "SoMa",
    "lat": 37.778558,
    "lng": -122.397587,
    "propType": "CONDOMINIUM",
    "lastSale": 880000,
    "lastSaleDate": "1998-07-01",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 10,
    "distressBand": "GREEN",
    "distressReasons": [
      "Stale ownership (pre-2018)"
    ]
  },
  {
    "attomId": 156199972,
    "address": "110 FREELON ST, SAN FRANCISCO, CA 94107",
    "submarket": "SoMa",
    "lat": 37.778558,
    "lng": -122.397587,
    "propType": "CONDOMINIUM",
    "lastSale": 555000,
    "lastSaleDate": "1995-12-29",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 10,
    "distressBand": "GREEN",
    "distressReasons": [
      "Stale ownership (pre-2018)"
    ]
  },
  {
    "attomId": 3705001,
    "address": "139 WELSH ST APT 12, SAN FRANCISCO, CA 94107",
    "submarket": "SoMa",
    "lat": 37.778532,
    "lng": -122.398018,
    "propType": "CONDOMINIUM",
    "lastSale": 905000,
    "lastSaleDate": "2005-04-13",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 10,
    "distressBand": "GREEN",
    "distressReasons": [
      "Stale ownership (pre-2018)"
    ]
  },
  {
    "attomId": 155705826,
    "address": "350 SANSOME ST, SAN FRANCISCO, CA 94104",
    "submarket": "Financial District",
    "lat": 37.793783,
    "lng": -122.401001,
    "propType": "OFFICE & SHOWROOM",
    "lastSale": null,
    "lastSaleDate": "2005-04-29",
    "avm": null,
    "mortgaged": false,
    "lender": null,
    "distressScore": 10,
    "distressBand": "GREEN",
    "distressReasons": [
      "Stale ownership (pre-2018)"
    ]
  }
];
