// AUTO-GENERATED by functions/functions/scripts/pullREWorkerData.js — REAL ATTOM data.
// Parcel facts (APN, type, year, lot, sqft, lat/lng) + sale history are live ATTOM pulls.
// Regenerate to refresh. Do NOT hand-edit.
export const RE_WORKER_ATTOM = {
  "title-abstract-001": {
    "slug": "title-abstract-001",
    "found": true,
    "address": "325 BATTERY ST, SAN FRANCISCO, CA 94111",
    "apn": "0229-003",
    "fips": "06075",
    "lat": "37.794289",
    "lng": "-122.400785",
    "propType": "OFFICE & SHOWROOM",
    "yearBuilt": 1924,
    "lotSizeAcres": 0.755,
    "bldgSqft": 195543,
    "ownerName": null,
    "assessedTotal": null,
    "marketTotal": null,
    "taxAmt": null,
    "taxYear": null,
    "lastSaleAmt": null,
    "lastSaleDate": null,
    "salesCount": 1,
    "sales": [
      {
        "date": "2020-02-06",
        "amount": 143000000,
        "doc": "DEED"
      }
    ]
  },
  "law-landuse-001": {
    "slug": "law-landuse-001",
    "found": true,
    "address": "658 FRONT ST, LAHAINA, HI 96761",
    "apn": "2-4-6-008-068-0000",
    "fips": "15009",
    "lat": "20.872421",
    "lng": "-156.677221",
    "propType": "COMMERCIAL (NEC)",
    "yearBuilt": null,
    "lotSizeAcres": 0.173,
    "bldgSqft": null,
    "ownerName": null,
    "assessedTotal": null,
    "marketTotal": null,
    "taxAmt": null,
    "taxYear": null,
    "lastSaleAmt": null,
    "lastSaleDate": null,
    "salesCount": 1,
    "sales": [
      {
        "date": "2021-10-01",
        "amount": null,
        "doc": null
      }
    ]
  },
  "zoning-001": {
    "slug": "zoning-001",
    "found": true,
    "address": "658 FRONT ST, LAHAINA, HI 96761",
    "apn": "2-4-6-008-068-0000",
    "fips": "15009",
    "lat": "20.872421",
    "lng": "-156.677221",
    "propType": "COMMERCIAL (NEC)",
    "yearBuilt": null,
    "lotSizeAcres": 0.173,
    "bldgSqft": null,
    "ownerName": null,
    "assessedTotal": null,
    "marketTotal": null,
    "taxAmt": null,
    "taxYear": null,
    "lastSaleAmt": null,
    "lastSaleDate": null,
    "salesCount": 1,
    "sales": [
      {
        "date": "2021-10-01",
        "amount": null,
        "doc": null
      }
    ]
  },
  "feasibility-001": {
    "slug": "feasibility-001",
    "found": true,
    "address": "505 FRONT ST, LAHAINA, HI 96761",
    "apn": "4-6-002-007-0200",
    "fips": "15009",
    "lat": "20.867589",
    "lng": "-156.675325",
    "propType": "RETAIL TRADE",
    "yearBuilt": 1975,
    "lotSizeAcres": 0.9880854,
    "bldgSqft": 5241,
    "ownerName": null,
    "assessedTotal": null,
    "marketTotal": null,
    "taxAmt": null,
    "taxYear": null,
    "lastSaleAmt": null,
    "lastSaleDate": null,
    "salesCount": 1,
    "sales": [
      {
        "date": "2007-09-19",
        "amount": 24873100,
        "doc": "DEED"
      }
    ]
  },
  "site-recon-001": {
    "slug": "site-recon-001",
    "found": true,
    "address": "12625 FREDERICK ST, MORENO VALLEY, CA 92553",
    "apn": "291-570-021",
    "fips": "06065",
    "lat": "33.937518",
    "lng": "-117.261866",
    "propType": "RESTAURANT BUILDING",
    "yearBuilt": 2022,
    "lotSizeAcres": 0.8,
    "bldgSqft": 3105,
    "ownerName": null,
    "assessedTotal": null,
    "marketTotal": null,
    "taxAmt": null,
    "taxYear": null,
    "lastSaleAmt": null,
    "lastSaleDate": null,
    "salesCount": 1,
    "sales": [
      {
        "date": "2021-07-01",
        "amount": 4833500,
        "doc": null
      }
    ]
  }
};
