// titleapp-frontdoor — Cloudflare Worker edge router
//
// REWRITE 2026-09-07. The original worker's source lived only on a machine
// that has since died and was not recoverable (Cloudflare's script-content
// API endpoint does not work with scoped API tokens, and Wrangler has no
// download command). This is a clean reimplementation based on:
//   - docs/STATE.md (the documented, "locked" Door 2 GPT-action routes)
//   - the confirmed live bindings (BACKEND_ORIGIN, FIREBASE_PROJECT_ID)
//   - grepping the real frontend (apps/business/src) for how it actually
//     calls this worker in production
//   - the red-team pass in docs/CODEX-S52.64-Frontdoor-Worker-Rebuild-and-Redteam.md
//
// ROUTING REALITY (confirmed by grep, not assumed):
//   - The web app (99% of real traffic) calls `${apiBase}/api?path=/v1/...`
//     — a single generic proxy path, path-to-forward encoded in a query
//     param. The frontend sets its own Authorization/x-tenant-id headers,
//     and the BACKEND verifies the Firebase token itself
//     (`requireFirebaseUser` in functions/functions/index.js) — this worker
//     does NOT need to re-verify tokens for this path, just proxy cleanly.
//   - The backend also owns CORS end-to-end for successful/backend-reached
//     responses (see `ALLOWED_ORIGINS` / `setCorsHeaders` in
//     functions/functions/index.js). But error responses generated by THIS
//     worker itself (bad path, 404, door-2 auth failure) never reach the
//     backend, so they need their own CORS headers or the frontend can't
//     even read the error (a real gap flagged in the red-team review) — see
//     `corsHeadersFor()` below, using the exact same allow-list as the
//     backend so the policy never diverges between the two layers.
//   - Separately, docs/STATE.md documents three "Door 2" GPT Action
//     endpoints (`/workflows`, `/chat`, `/reportStatus`) where the WORKER
//     itself verifies the Firebase ID token and injects headers before
//     proxying — this is for an external GPT Action integration, distinct
//     from the main web app's chat panel (which uses `/api?path=/v1/chat:message`
//     like everything else). Both paths must keep working.
//   - `apps/business/src/components/DriveImportModal.jsx` calls
//     `https://api-feyfibglbq-uc.a.run.app/v1/drive:...` / `/vault:...`
//     DIRECTLY, bypassing this worker entirely — confirmed via grep, not a
//     gap in this worker's coverage, just a pre-existing architectural
//     inconsistency elsewhere in the app that's out of scope here.
//
// THE BUG THIS REWRITE FIXES: the previous worker leaked raw
// `data: {...}` SSE lines as a client-facing JSON-parse error on streaming
// (accounting-worker) chat responses. The fix is structural: this worker
// NEVER buffers or re-parses a proxied response body. It always returns
// `new Response(originResponse.body, ...)` — the body is streamed straight
// through, and every response header from the origin (including
// `Content-Type: text/event-stream`) is copied over unmodified. There is
// no code path here that touches, decodes, or re-serializes a proxied body.
//
// Live-verified against the real production backend (2026-09-07, via an
// isolated `titleapp-frontdoor-test` deployment, before any cutover):
//   - /api?path=/v1/chat:message with no auth -> backend's own real 401
//     JSON body + backend's own CORS headers, both passed through intact.
//   - /api?path=/v1/workspaces with a syntactically-invalid Bearer token ->
//     backend responds "Invalid token" (not "missing token") — proves the
//     Authorization header is actually forwarded, not dropped.
//   - /chat, /workflows, /reportStatus with no auth -> this worker's own
//     401/error paths fire correctly before ever reaching the backend.
//   - Unknown route -> 404. Missing `path` query param -> 400.

import { createRemoteJWKSet, jwtVerify } from "jose";

/**
 * @typedef {Object} Env
 * @property {string} BACKEND_ORIGIN  e.g. https://api-feyfibglbq-uc.a.run.app
 * @property {string} FIREBASE_PROJECT_ID  e.g. title-app-alpha
 * @property {string} [EDGE_SHARED_SECRET]  wrangler secret (never plain-text
 *   in wrangler.toml) — sent as X-Edge-Secret on every proxied request so
 *   the backend can reject anything that reaches it without going through
 *   this worker. Optional at the type level because it's set as a real
 *   secret post-deploy (`wrangler secret put`), not present in local dev.
 */

// Headers that carry TRUST, not just data: a client must never be able to
// set these itself and have the raw value reach the backend. Stripped
// unconditionally from every incoming request before any routing logic
// runs; re-added only from a verified source (never a raw pass-through of
// the client's own value) on the specific routes that legitimately set
// them (X-User-Id only on the /chat door-2 route, from a verified token's
// uid; X-Edge-Secret always, from the worker's own secret binding).
//
// X-Vertical/X-Jurisdiction are deliberately NOT in this list. Confirmed
// during the S52.64 rebuild that real production admin pages (e.g.
// PipelineMonitor.jsx, BogoManager.jsx) send these directly through the
// generic /api?path= proxy today, and the backend only ever uses them for
// ruleset/vertical selection (`req.headers["x-vertical"] || body.vertical`)
// — never for access control or identity. Treating them as a trust
// boundary here would break real functionality without closing an actual
// vulnerability; they're honestly just routing hints in this app's current
// architecture, worker or no worker.
const TRUST_HEADERS = ["X-User-Id", "X-Edge-Secret"];

function stripTrustHeaders(headers) {
  for (const h of TRUST_HEADERS) headers.delete(h);
}

// SECURITY NOTE — Workers Observability is enabled (see wrangler.toml).
// Never console.log a Request/Headers object, request.headers.get(...) for
// Authorization/X-Edge-Secret, or any variable derived from them, anywhere
// in this file. This worker intentionally has NO logging of request
// headers or bodies at all — Cloudflare's automatic request/trace capture
// records method/URL/status/duration/CPU time, not header contents, but
// any future debugging addition must not defeat that by logging a bearer
// token or the edge secret into Cloudflare's log storage.

// Same allow-list as functions/functions/index.js's ALLOWED_ORIGINS. Kept
// in sync manually (small, stable list) — only used for responses this
// worker generates itself before ever reaching the backend (see comment
// at the top of this file on why that's necessary).
const ALLOWED_ORIGINS = [
  "https://title-app-alpha.web.app",
  "https://title-app-alpha.firebaseapp.com",
  "https://titleapp-frontdoor.titleapp-core.workers.dev",
  "https://app.titleapp.ai",
  "https://titleapp.ai",
  "https://www.titleapp.ai",
  "https://titleapp.io",
  "https://app.sociii.ai",
  "https://sociii.ai",
  "https://www.sociii.ai",
  "http://localhost:3000",
  "http://localhost:5173",
  "http://127.0.0.1:3000",
  "http://127.0.0.1:5173",
];

function corsHeadersFor(request) {
  const origin = request.headers.get("Origin");
  const headers = {
    "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Tenant-Id, X-Vertical, X-Jurisdiction, X-Session-Id",
    "Access-Control-Max-Age": "3600",
  };
  if (origin && ALLOWED_ORIGINS.includes(origin)) {
    headers["Access-Control-Allow-Origin"] = origin;
  }
  return headers;
}

function jsonError(request, status, message, code) {
  return new Response(JSON.stringify({ ok: false, error: message, code: code || undefined }), {
    status,
    headers: {
      "Content-Type": "application/json",
      ...corsHeadersFor(request),
    },
  });
}

// jose's createRemoteJWKSet handles fetching + caching Google's public keys
// itself (including respecting a cooldown between refetches on unknown
// `kid`, so a key rotation doesn't cause a fetch storm, and a genuinely
// unknown kid still triggers a fresh fetch rather than being stuck on a
// stale cache forever). One JWKS instance is reused for the life of the
// isolate; do not recreate it per-request.
let jwks = null;
function getJwks() {
  if (!jwks) {
    jwks = createRemoteJWKSet(
      new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com")
    );
  }
  return jwks;
}

/**
 * Verify a Firebase ID token per Google's documented algorithm:
 * https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library
 *
 * Uses `jose` (a vetted, widely-used JWT library) for signature
 * verification rather than hand-rolled crypto — deliberate choice from the
 * S52.64 red-team review to reduce the chance of a subtle bug in
 * security-critical auth code. `jose` also enforces `alg`/`exp` checks
 * internally; this function additionally checks the Firebase-specific
 * `iss`/`aud`/`sub` requirements Google's docs call out.
 *
 * Throws with a descriptive message on any failure — never returns a
 * partially-valid result.
 *
 * @returns {Promise<{uid: string, email?: string, claims: Record<string, any>}>}
 */
async function verifyFirebaseIdToken(idToken, projectId) {
  if (!idToken || typeof idToken !== "string") throw new Error("missing token");

  const { payload } = await jwtVerify(idToken, getJwks(), {
    algorithms: ["RS256"],
    issuer: `https://securetoken.google.com/${projectId}`,
    audience: projectId,
  });

  if (!payload.sub || typeof payload.sub !== "string") throw new Error("missing sub");

  return { uid: payload.sub, email: payload.email, claims: payload };
}

/** Proxy a request to the backend, streaming the response body through untouched. */
async function proxyToBackend(request, targetUrl, env, extraHeaders = {}) {
  const headers = new Headers(request.headers);
  // Strip any client-supplied trust headers FIRST, then apply only the
  // caller-provided verified values on top — never merge with whatever the
  // client sent.
  stripTrustHeaders(headers);
  for (const [k, v] of Object.entries(extraHeaders)) headers.set(k, v);
  // Host header must match the target origin, not the worker's own host.
  headers.delete("host");
  // Every proxied request carries this, whether or not it's configured yet
  // (see EDGE_SHARED_SECRET jsdoc above). The backend's own check is inert
  // until Sean explicitly activates it in Secret Manager post-cutover, so
  // it's safe to always send this even before that activation step.
  if (env.EDGE_SHARED_SECRET) headers.set("X-Edge-Secret", env.EDGE_SHARED_SECRET);

  const init = {
    method: request.method,
    headers,
    // GET/HEAD must not carry a body.
    body: ["GET", "HEAD"].includes(request.method) ? undefined : request.body,
    redirect: "manual",
  };

  const originResponse = await fetch(targetUrl, init);

  // Stream the body straight through. Do NOT call .json()/.text() or
  // otherwise consume/re-encode it here — that is exactly the class of bug
  // this rewrite exists to fix for SSE/streaming responses. Verified
  // working for both a plain-JSON response and (by code construction,
  // since there is no content-type-specific branching anywhere in this
  // function) would behave identically for a streaming one.
  return new Response(originResponse.body, {
    status: originResponse.status,
    statusText: originResponse.statusText,
    headers: originResponse.headers,
  });
}

export default {
  /** @param {Request} request @param {Env} env */
  async fetch(request, env) {
    // CORS preflight — answered directly, never proxied (OPTIONS requests
    // carry no auth/body worth forwarding, and answering locally is both
    // faster and guarantees a CORS-correct response even if the backend is
    // unreachable).
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeadersFor(request) });
    }

    let url;
    try {
      url = new URL(request.url);
    } catch {
      return jsonError(request, 400, "invalid URL");
    }

    if (!env.BACKEND_ORIGIN) {
      return jsonError(request, 500, "worker misconfigured: BACKEND_ORIGIN not set");
    }

    // ── Generic proxy: /api?path=/v1/... ─────────────────────────────
    // This is the dominant, real traffic pattern used by the entire web
    // app. The frontend already sets Authorization/x-tenant-id itself and
    // the backend verifies/authorizes independently — this worker just
    // proxies. The backend's own CORS headers pass through untouched on
    // its responses; this worker's own 400 (below) needs its own CORS.
    if (url.pathname === "/api") {
      const path = url.searchParams.get("path");
      // Allowlist: only the backend's real, documented API namespace can be
      // reached this way. Without this, the query param would let a caller
      // forward to ANY path on BACKEND_ORIGIN, including routes never meant
      // to be edge-exposed — a distinct bypass surface from token
      // verification, flagged explicitly in the S52.64 red-team review.
      if (!path || !/^\/v1\/[A-Za-z0-9_:./-]+$/.test(path.split("?")[0])) {
        return jsonError(request, 400, "missing or invalid 'path' query parameter");
      }
      const target = new URL(env.BACKEND_ORIGIN);
      // `path` may itself carry a query string (e.g. /reportStatus?jobId=1)
      const [pathOnly, pathQuery] = path.split("?");
      target.pathname = pathOnly;
      if (pathQuery) target.search = pathQuery;
      return proxyToBackend(request, target.toString(), env);
    }

    // ── Door 2 / embedded GPT Action endpoints — see docs/STATE.md ───
    // These are LOCKED routes for an external GPT Action integration,
    // separate from the main web app. The worker verifies the Firebase
    // token itself and injects headers the backend expects.
    if (url.pathname === "/workflows" && request.method === "POST") {
      return handleDoor2(request, env, {
        backendPath: "/v1/raas:workflows",
        requireAuth: true,
        forwardHeaders: ["X-Vertical", "X-Jurisdiction"],
      });
    }

    if (url.pathname === "/chat" && request.method === "POST") {
      return handleDoor2(request, env, {
        backendPath: "/v1/chat:message",
        requireAuth: true,
        injectUserId: true,
      });
    }

    if (url.pathname === "/reportStatus" && request.method === "GET") {
      // Not routed through handleDoor2 — STATE.md doesn't document
      // worker-side auth verification for this one (unlike /workflows and
      // /chat), just proxying. The backend independently requires auth AND
      // checks `data.tenantId !== ctx.tenantId` before returning a job
      // (confirmed in functions/functions/index.js during the S52.64 red-team
      // review — this closes the IDOR concern raised for this route: a
      // cross-tenant jobId lookup gets a 403, not another tenant's data).
      const target = new URL(env.BACKEND_ORIGIN);
      target.pathname = "/v1/report:status";
      target.search = url.search; // forwards ?jobId=...
      return proxyToBackend(request, target.toString(), env);
    }

    return jsonError(request, 404, "not found");
  },
};

/**
 * Shared handler for the two Door-2 routes that require worker-side
 * Firebase token verification before proxying.
 */
async function handleDoor2(request, env, { backendPath, requireAuth, forwardHeaders = [], injectUserId = false }) {
  const authHeader = request.headers.get("Authorization") || "";
  const match = authHeader.match(/^Bearer (.+)$/);

  if (requireAuth && !match) {
    return jsonError(request, 401, "missing Authorization: Bearer <Firebase ID token>", "UNAUTHORIZED");
  }

  let verified = null;
  if (match) {
    try {
      verified = await verifyFirebaseIdToken(match[1], env.FIREBASE_PROJECT_ID);
    } catch (err) {
      return jsonError(request, 401, `invalid Firebase ID token: ${err.message}`, "UNAUTHORIZED");
    }
  }

  const extraHeaders = {};
  if (injectUserId && verified) extraHeaders["X-User-Id"] = verified.uid;
  for (const h of forwardHeaders) {
    const v = request.headers.get(h);
    if (v) extraHeaders[h] = v;
  }

  const target = new URL(env.BACKEND_ORIGIN);
  target.pathname = backendPath;
  return proxyToBackend(request, target.toString(), env, extraHeaders);
}
