// services/documentEngine/generators/docxGenerator.js
// DOCX generation via docx package — covers agreement-standard, letter-formal

const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  TabStopPosition,
  TabStopType,
  Footer,
  PageNumber,
  NumberFormat,
} = require("docx");
const { COLORS } = require("../templates/layouts");

async function generateDocx({ template, data, brand, logoBuffer }) {
  let sections;

  switch (template.id) {
    case "letter-formal":
      sections = buildLetter(data, brand);
      break;
    case "agreement-standard":
    default:
      sections = buildAgreement(data, brand);
      break;
  }

  const doc = new Document({
    creator: "TitleApp Document Engine",
    title: data.title || "Untitled Document",
    description: `Generated by TitleApp.ai for ${brand.name || "TitleApp"}`,
    sections,
  });

  return Packer.toBuffer(doc);
}

function primaryColorHex(brand) {
  return (brand.primaryColor || COLORS.primary).replace("#", "");
}

function aiDisclosureParagraph(brand) {
  return new Paragraph({
    spacing: { before: 400, after: 200 },
    border: {
      top: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
    },
    children: [
      new TextRun({
        text:
          brand.aiDisclosure ||
          "This document was generated by a TitleApp Digital Worker with the assistance of artificial intelligence. All data should be independently verified. Human review recommended.",
        size: 16,
        color: "6B7280",
        italics: true,
        font: "Arial",
      }),
    ],
  });
}

function footerSection(brand) {
  return {
    default: new Footer({
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new TextRun({
              text: brand.footerText || "Generated by TitleApp.ai",
              size: 16,
              color: "6B7280",
              font: "Arial",
            }),
            new TextRun({
              text: "    |    Page ",
              size: 16,
              color: "6B7280",
              font: "Arial",
            }),
            new TextRun({
              children: [PageNumber.CURRENT],
              size: 16,
              color: "6B7280",
              font: "Arial",
            }),
          ],
        }),
      ],
    }),
  };
}

// --- Agreement layout ---

function buildAgreement(data, brand) {
  const children = [];

  // Title
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
      children: [
        new TextRun({
          text: (data.title || "AGREEMENT").toUpperCase(),
          bold: true,
          size: 32,
          color: primaryColorHex(brand),
          font: "Arial",
        }),
      ],
    })
  );

  // Effective date
  if (data.effectiveDate) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
        children: [
          new TextRun({
            text: `Effective Date: ${data.effectiveDate}`,
            size: 22,
            color: "6B7280",
            font: "Arial",
          }),
        ],
      })
    );
  }

  // Parties
  if (data.parties && Array.isArray(data.parties)) {
    children.push(
      new Paragraph({
        spacing: { before: 200, after: 100 },
        children: [
          new TextRun({
            text: "PARTIES",
            bold: true,
            size: 24,
            color: primaryColorHex(brand),
            font: "Arial",
          }),
        ],
      })
    );

    for (const party of data.parties) {
      const name = typeof party === "string" ? party : party.name || "";
      const role = typeof party === "object" ? party.role || "" : "";
      const desc = role ? `${name} ("${role}")` : name;
      children.push(
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({ text: desc, size: 22, font: "Arial" }),
          ],
        })
      );
    }
  }

  // Recitals
  if (data.recitals && Array.isArray(data.recitals)) {
    children.push(
      new Paragraph({
        spacing: { before: 300, after: 100 },
        children: [
          new TextRun({
            text: "RECITALS",
            bold: true,
            size: 24,
            color: primaryColorHex(brand),
            font: "Arial",
          }),
        ],
      })
    );

    for (const recital of data.recitals) {
      children.push(
        new Paragraph({
          spacing: { after: 80 },
          children: [
            new TextRun({
              text: `WHEREAS, ${typeof recital === "string" ? recital : recital.text || ""}`,
              size: 22,
              font: "Arial",
            }),
          ],
        })
      );
    }
  }

  // Clauses
  if (data.clauses && Array.isArray(data.clauses)) {
    children.push(
      new Paragraph({
        spacing: { before: 300, after: 100 },
        children: [
          new TextRun({
            text: "TERMS AND CONDITIONS",
            bold: true,
            size: 24,
            color: primaryColorHex(brand),
            font: "Arial",
          }),
        ],
      })
    );

    for (let i = 0; i < data.clauses.length; i++) {
      const clause = data.clauses[i];
      const title =
        typeof clause === "string"
          ? ""
          : clause.title || clause.heading || "";
      const text =
        typeof clause === "string" ? clause : clause.text || clause.body || "";

      // Clause heading
      if (title) {
        children.push(
          new Paragraph({
            spacing: { before: 200, after: 60 },
            children: [
              new TextRun({
                text: `${i + 1}. ${title}`,
                bold: true,
                size: 22,
                font: "Arial",
              }),
            ],
          })
        );
      }

      // Clause body
      children.push(
        new Paragraph({
          spacing: { after: 80 },
          indent: title ? { left: 360 } : undefined,
          children: [
            new TextRun({
              text: title ? text : `${i + 1}. ${text}`,
              size: 22,
              font: "Arial",
            }),
          ],
        })
      );

      // Sub-clauses
      if (typeof clause === "object" && clause.subclauses && Array.isArray(clause.subclauses)) {
        for (let j = 0; j < clause.subclauses.length; j++) {
          const sub = clause.subclauses[j];
          children.push(
            new Paragraph({
              spacing: { after: 60 },
              indent: { left: 720 },
              children: [
                new TextRun({
                  text: `${i + 1}.${j + 1} ${typeof sub === "string" ? sub : sub.text || ""}`,
                  size: 22,
                  font: "Arial",
                }),
              ],
            })
          );
        }
      }
    }
  }

  // Signature blocks
  if (data.signatures && Array.isArray(data.signatures)) {
    children.push(
      new Paragraph({
        spacing: { before: 600 },
        children: [
          new TextRun({
            text: "IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written above.",
            size: 22,
            font: "Arial",
          }),
        ],
      })
    );

    for (const sig of data.signatures) {
      const name = typeof sig === "string" ? sig : sig.name || "";
      const role = typeof sig === "object" ? sig.role || sig.title || "" : "";

      children.push(
        new Paragraph({ spacing: { before: 400 }, children: [] })
      );
      children.push(
        new Paragraph({
          spacing: { after: 20 },
          children: [
            new TextRun({
              text: "________________________________________",
              size: 22,
              font: "Arial",
            }),
          ],
        })
      );
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: name,
              bold: true,
              size: 22,
              font: "Arial",
            }),
          ],
        })
      );
      if (role) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: role,
                size: 20,
                color: "6B7280",
                font: "Arial",
              }),
            ],
          })
        );
      }
      children.push(
        new Paragraph({
          spacing: { after: 20 },
          children: [
            new TextRun({
              text: "Date: _______________",
              size: 20,
              color: "6B7280",
              font: "Arial",
            }),
          ],
        })
      );
    }
  }

  // Exhibits
  if (data.exhibits && Array.isArray(data.exhibits)) {
    children.push(
      new Paragraph({
        pageBreakBefore: true,
        spacing: { after: 200 },
        children: [
          new TextRun({
            text: "EXHIBITS",
            bold: true,
            size: 28,
            color: primaryColorHex(brand),
            font: "Arial",
          }),
        ],
      })
    );

    for (let i = 0; i < data.exhibits.length; i++) {
      const exhibit = data.exhibits[i];
      const label = String.fromCharCode(65 + i); // A, B, C...
      children.push(
        new Paragraph({
          spacing: { before: 200, after: 80 },
          children: [
            new TextRun({
              text: `Exhibit ${label}: ${typeof exhibit === "string" ? exhibit : exhibit.title || ""}`,
              bold: true,
              size: 22,
              font: "Arial",
            }),
          ],
        })
      );
      if (typeof exhibit === "object" && exhibit.content) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: exhibit.content, size: 22, font: "Arial" }),
            ],
          })
        );
      }
    }
  }

  // AI Disclosure
  children.push(aiDisclosureParagraph(brand));

  return [
    {
      properties: {
        page: {
          margin: {
            top: 1440,
            right: 1440,
            bottom: 1440,
            left: 1440,
          },
        },
      },
      footers: footerSection(brand),
      children,
    },
  ];
}

// --- Letter layout ---

function buildLetter(data, brand) {
  const children = [];

  // Letterhead / From
  children.push(
    new Paragraph({
      spacing: { after: 40 },
      children: [
        new TextRun({
          text: data.from || brand.name || "TitleApp",
          bold: true,
          size: 24,
          color: primaryColorHex(brand),
          font: "Arial",
        }),
      ],
    })
  );

  if (data.fromAddress) {
    const lines = Array.isArray(data.fromAddress)
      ? data.fromAddress
      : data.fromAddress.split("\n");
    for (const line of lines) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: line, size: 20, color: "6B7280", font: "Arial" }),
          ],
        })
      );
    }
  }

  // Date
  children.push(
    new Paragraph({
      spacing: { before: 300, after: 300 },
      children: [
        new TextRun({
          text:
            data.date ||
            new Date().toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            }),
          size: 22,
          font: "Arial",
        }),
      ],
    })
  );

  // Recipient address block
  const toName = typeof data.to === "string" ? data.to : (data.to && data.to.name) || "";
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: toName, bold: true, size: 22, font: "Arial" }),
      ],
    })
  );

  if (data.toAddress) {
    const lines = Array.isArray(data.toAddress)
      ? data.toAddress
      : data.toAddress.split("\n");
    for (const line of lines) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: line, size: 22, font: "Arial" }),
          ],
        })
      );
    }
  }

  // Subject
  if (data.subject) {
    children.push(
      new Paragraph({
        spacing: { before: 300, after: 100 },
        children: [
          new TextRun({
            text: `Re: ${data.subject}`,
            bold: true,
            size: 22,
            font: "Arial",
          }),
        ],
      })
    );
  }

  // Salutation
  children.push(
    new Paragraph({
      spacing: { before: 200, after: 200 },
      children: [
        new TextRun({
          text: data.salutation || `Dear ${toName},`,
          size: 22,
          font: "Arial",
        }),
      ],
    })
  );

  // Body paragraphs
  const bodyText = Array.isArray(data.body) ? data.body : [data.body];
  for (const para of bodyText) {
    children.push(
      new Paragraph({
        spacing: { after: 120 },
        children: [
          new TextRun({ text: para || "", size: 22, font: "Arial" }),
        ],
      })
    );
  }

  // Closing
  children.push(
    new Paragraph({
      spacing: { before: 300 },
      children: [
        new TextRun({
          text: data.closing || "Sincerely,",
          size: 22,
          font: "Arial",
        }),
      ],
    })
  );

  // Signature
  children.push(
    new Paragraph({
      spacing: { before: 400 },
      children: [
        new TextRun({
          text: data.signer || data.from || "",
          bold: true,
          size: 22,
          font: "Arial",
        }),
      ],
    })
  );

  if (data.signerTitle) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: data.signerTitle,
            size: 20,
            color: "6B7280",
            font: "Arial",
          }),
        ],
      })
    );
  }

  // CC
  if (data.cc) {
    const ccList = Array.isArray(data.cc) ? data.cc : [data.cc];
    children.push(
      new Paragraph({
        spacing: { before: 300 },
        children: [
          new TextRun({
            text: `cc: ${ccList.join(", ")}`,
            size: 20,
            color: "6B7280",
            font: "Arial",
          }),
        ],
      })
    );
  }

  // Enclosures
  if (data.enclosures) {
    const encList = Array.isArray(data.enclosures)
      ? data.enclosures
      : [data.enclosures];
    children.push(
      new Paragraph({
        spacing: { before: 100 },
        children: [
          new TextRun({
            text: `Enclosures: ${encList.join(", ")}`,
            size: 20,
            color: "6B7280",
            font: "Arial",
          }),
        ],
      })
    );
  }

  // AI Disclosure
  children.push(aiDisclosureParagraph(brand));

  return [
    {
      properties: {
        page: {
          margin: {
            top: 1440,
            right: 1440,
            bottom: 1440,
            left: 1440,
          },
        },
      },
      footers: footerSection(brand),
      children,
    },
  ];
}

module.exports = { generateDocx };
