// services/documentEngine/generators/pptxGenerator.js
// PPTX generation via pptxgenjs — covers deck-standard

const PptxGenJS = require("pptxgenjs");
const { COLORS } = require("../templates/layouts");

async function generatePptx({ template, data, brand, logoBuffer }) {
  // Route W-016 investor slides to dedicated generator
  if (template.id === "cs-investor-slides") {
    return generateInvestorSlides({ template, data, brand, logoBuffer });
  }

  const pptx = new PptxGenJS();

  pptx.author = "TitleApp Document Engine";
  pptx.company = brand.name || "TitleApp";
  pptx.title = data.title || "Untitled Presentation";
  pptx.subject = data.subtitle || "";
  pptx.layout = "LAYOUT_WIDE";

  const primary = brand.primaryColor || COLORS.primary;
  const secondary = brand.secondaryColor || COLORS.secondary;
  const disclosure =
    brand.aiDisclosure ||
    "Generated by a TitleApp Digital Worker. AI-assisted — human review recommended.";

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: secondary.replace("#", "") };

  // Logo on title slide
  if (logoBuffer) {
    try {
      const base64 = logoBuffer.toString("base64");
      const ext = detectImageType(logoBuffer);
      titleSlide.addImage({
        data: `image/${ext};base64,${base64}`,
        x: 0.5,
        y: 0.4,
        h: 0.8,
        sizing: { type: "contain", h: 0.8 },
      });
    } catch (e) {
      // Logo failed — skip
    }
  }

  titleSlide.addText(data.title || "Untitled", {
    x: 0.5,
    y: 2.0,
    w: "90%",
    fontSize: 36,
    bold: true,
    color: "FFFFFF",
    fontFace: "Arial",
  });

  if (data.subtitle) {
    titleSlide.addText(data.subtitle, {
      x: 0.5,
      y: 3.0,
      w: "90%",
      fontSize: 20,
      color: primary.replace("#", ""),
      fontFace: "Arial",
    });
  }

  const metaLine = [
    data.presenter,
    data.date ||
      new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
  ]
    .filter(Boolean)
    .join("  |  ");

  if (metaLine) {
    titleSlide.addText(metaLine, {
      x: 0.5,
      y: 4.2,
      w: "90%",
      fontSize: 14,
      color: "A0A0A0",
      fontFace: "Arial",
    });
  }

  // AI disclosure on title slide
  titleSlide.addText(disclosure, {
    x: 0.3,
    y: 6.8,
    w: "95%",
    fontSize: 8,
    color: "808080",
    fontFace: "Arial",
    italic: true,
  });

  // Content slides
  const slides = data.slides || [];
  for (const slideData of slides) {
    const slide = pptx.addSlide();

    // Top accent bar
    slide.addShape(pptx.shapes.RECTANGLE, {
      x: 0,
      y: 0,
      w: "100%",
      h: 0.06,
      fill: { color: primary.replace("#", "") },
    });

    // Slide title
    slide.addText(slideData.title || "", {
      x: 0.5,
      y: 0.3,
      w: "90%",
      fontSize: 28,
      bold: true,
      color: secondary.replace("#", ""),
      fontFace: "Arial",
    });

    let contentY = 1.2;

    // Subtitle
    if (slideData.subtitle) {
      slide.addText(slideData.subtitle, {
        x: 0.5,
        y: contentY,
        w: "90%",
        fontSize: 16,
        color: "6B7280",
        fontFace: "Arial",
      });
      contentY += 0.6;
    }

    // Bullet points
    if (slideData.bullets && Array.isArray(slideData.bullets)) {
      const bulletTexts = slideData.bullets.map((b) => ({
        text: typeof b === "string" ? b : b.text || "",
        options: {
          fontSize: 16,
          color: "333333",
          fontFace: "Arial",
          bullet: { type: "bullet" },
          paraSpaceAfter: 8,
        },
      }));

      slide.addText(bulletTexts, {
        x: 0.7,
        y: contentY,
        w: "85%",
        h: 4.5,
        valign: "top",
      });
    }

    // Body text (alternative to bullets)
    if (slideData.body && !slideData.bullets) {
      slide.addText(slideData.body, {
        x: 0.5,
        y: contentY,
        w: "90%",
        h: 4.5,
        fontSize: 16,
        color: "333333",
        fontFace: "Arial",
        valign: "top",
      });
    }

    // Key metrics row
    if (slideData.metrics && Array.isArray(slideData.metrics)) {
      const metricsY = 5.0;
      const count = Math.min(slideData.metrics.length, 4);
      const colW = 12 / count;

      for (let i = 0; i < count; i++) {
        const m = slideData.metrics[i];
        const x = 0.5 + i * colW;

        slide.addText(String(m.value || "0"), {
          x,
          y: metricsY,
          w: colW - 0.3,
          fontSize: 28,
          bold: true,
          color: primary.replace("#", ""),
          fontFace: "Arial",
          align: "center",
        });

        slide.addText(m.label || "", {
          x,
          y: metricsY + 0.6,
          w: colW - 0.3,
          fontSize: 11,
          color: "6B7280",
          fontFace: "Arial",
          align: "center",
        });
      }
    }

    // Notes (speaker notes)
    if (slideData.notes) {
      slide.addNotes(slideData.notes);
    }

    // Footer with disclosure
    slide.addText(disclosure, {
      x: 0.3,
      y: 6.8,
      w: "95%",
      fontSize: 8,
      color: "808080",
      fontFace: "Arial",
      italic: true,
    });
  }

  // Closing slide
  const closingSlide = pptx.addSlide();
  closingSlide.background = { color: secondary.replace("#", "") };

  closingSlide.addText(data.closingTitle || "Thank You", {
    x: 0.5,
    y: 2.5,
    w: "90%",
    fontSize: 36,
    bold: true,
    color: "FFFFFF",
    fontFace: "Arial",
    align: "center",
  });

  if (data.closingSubtitle || data.contactInfo) {
    closingSlide.addText(data.closingSubtitle || data.contactInfo || "", {
      x: 0.5,
      y: 3.5,
      w: "90%",
      fontSize: 18,
      color: primary.replace("#", ""),
      fontFace: "Arial",
      align: "center",
    });
  }

  closingSlide.addText(disclosure, {
    x: 0.3,
    y: 6.8,
    w: "95%",
    fontSize: 8,
    color: "808080",
    fontFace: "Arial",
    italic: true,
  });

  // Generate buffer
  const uint8 = await pptx.write({ outputType: "nodebuffer" });
  return Buffer.from(uint8);
}

async function generateInvestorSlides({ template, data, brand, logoBuffer }) {
  const pptx = new PptxGenJS();

  pptx.author = "TitleApp Document Engine";
  pptx.company = brand.name || "TitleApp";
  pptx.title = data.title || "Capital Stack — Investor Presentation";
  pptx.subject = data.subtitle || "";
  pptx.layout = "LAYOUT_WIDE";

  const primary = brand.primaryColor || COLORS.primary;
  const secondary = brand.secondaryColor || COLORS.secondary;
  const disclosure =
    brand.aiDisclosure ||
    "Generated by a TitleApp Digital Worker. AI-assisted — human review recommended.";

  // Slide 1: Title / Stack Overview
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: secondary.replace("#", "") };

  if (logoBuffer) {
    try {
      const base64 = logoBuffer.toString("base64");
      const ext = detectImageType(logoBuffer);
      titleSlide.addImage({
        data: `image/${ext};base64,${base64}`,
        x: 0.5, y: 0.4, h: 0.8,
        sizing: { type: "contain", h: 0.8 },
      });
    } catch (e) { /* skip */ }
  }

  titleSlide.addText(data.title || "Capital Stack Overview", {
    x: 0.5, y: 2.0, w: "90%",
    fontSize: 36, bold: true, color: "FFFFFF", fontFace: "Arial",
  });

  if (data.dealName || data.subtitle) {
    titleSlide.addText(data.dealName || data.subtitle, {
      x: 0.5, y: 3.0, w: "90%",
      fontSize: 20, color: primary.replace("#", ""), fontFace: "Arial",
    });
  }

  const metaLine = [data.presenter, data.date || new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })].filter(Boolean).join("  |  ");
  if (metaLine) {
    titleSlide.addText(metaLine, { x: 0.5, y: 4.2, w: "90%", fontSize: 14, color: "A0A0A0", fontFace: "Arial" });
  }

  // Stack summary metrics on title slide
  const layers = data.capitalLayers || [];
  const totalSources = layers.reduce((s, l) => s + (l.amount || 0), 0);
  if (totalSources > 0) {
    const stackMetrics = [
      { label: "Total Capital", value: "$" + (totalSources / 1000000).toFixed(1) + "M" },
      { label: "Sources", value: String(layers.length) },
      { label: "WACC", value: (data.wacc || data.returnMetrics?.wacc || "N/A") + "%" },
    ];
    const count = stackMetrics.length;
    const colW = 12 / count;
    for (let i = 0; i < count; i++) {
      const m = stackMetrics[i];
      const x = 0.5 + i * colW;
      titleSlide.addText(String(m.value), { x, y: 5.2, w: colW - 0.3, fontSize: 28, bold: true, color: primary.replace("#", ""), fontFace: "Arial", align: "center" });
      titleSlide.addText(m.label, { x, y: 5.8, w: colW - 0.3, fontSize: 11, color: "6B7280", fontFace: "Arial", align: "center" });
    }
  }

  titleSlide.addText(disclosure, { x: 0.3, y: 6.8, w: "95%", fontSize: 8, color: "808080", fontFace: "Arial", italic: true });

  // Slide 2: Sources & Uses
  const suSlide = pptx.addSlide();
  suSlide.addShape(pptx.shapes.RECTANGLE, { x: 0, y: 0, w: "100%", h: 0.06, fill: { color: primary.replace("#", "") } });
  suSlide.addText("Sources & Uses", { x: 0.5, y: 0.3, w: "90%", fontSize: 28, bold: true, color: secondary.replace("#", ""), fontFace: "Arial" });

  const suBullets = [];
  for (const l of layers) {
    const pct = totalSources > 0 ? ((l.amount || 0) / totalSources * 100).toFixed(0) : "0";
    suBullets.push({ text: (l.source || l.type || "") + ": $" + ((l.amount || 0) / 1000000).toFixed(1) + "M (" + pct + "%)", options: { fontSize: 16, color: "333333", fontFace: "Arial", bullet: { type: "bullet" }, paraSpaceAfter: 8 } });
  }
  if (suBullets.length > 0) {
    suSlide.addText(suBullets, { x: 0.7, y: 1.2, w: "45%", h: 4.5, valign: "top" });
  }

  const uses = data.uses || [];
  const useBullets = [];
  for (const u of uses) {
    useBullets.push({ text: (u.category || u.name || "") + ": $" + ((u.amount || 0) / 1000000).toFixed(1) + "M", options: { fontSize: 16, color: "333333", fontFace: "Arial", bullet: { type: "bullet" }, paraSpaceAfter: 8 } });
  }
  if (useBullets.length > 0) {
    suSlide.addText("Uses", { x: 6.5, y: 1.0, w: "40%", fontSize: 20, bold: true, color: secondary.replace("#", ""), fontFace: "Arial" });
    suSlide.addText(useBullets, { x: 6.5, y: 1.6, w: "40%", h: 4.0, valign: "top" });
  }

  suSlide.addText(disclosure, { x: 0.3, y: 6.8, w: "95%", fontSize: 8, color: "808080", fontFace: "Arial", italic: true });

  // Slide 3: Return Metrics
  const rmSlide = pptx.addSlide();
  rmSlide.addShape(pptx.shapes.RECTANGLE, { x: 0, y: 0, w: "100%", h: 0.06, fill: { color: primary.replace("#", "") } });
  rmSlide.addText("Return Metrics", { x: 0.5, y: 0.3, w: "90%", fontSize: 28, bold: true, color: secondary.replace("#", ""), fontFace: "Arial" });

  const rm = data.returnMetrics || {};
  const returnMetrics = [
    { label: "Levered IRR", value: rm.leveredIrr != null ? rm.leveredIrr + "%" : "N/A" },
    { label: "LP IRR", value: rm.lpIrr != null ? rm.lpIrr + "%" : "N/A" },
    { label: "Equity Multiple", value: rm.equityMultiple != null ? rm.equityMultiple + "x" : "N/A" },
    { label: "Cash-on-Cash Y1", value: rm.cashOnCashY1 != null ? rm.cashOnCashY1 + "%" : (Array.isArray(rm.cashOnCash) && rm.cashOnCash[0] != null ? rm.cashOnCash[0] + "%" : "N/A") },
  ];

  const rmCount = returnMetrics.length;
  const rmColW = 12 / rmCount;
  for (let i = 0; i < rmCount; i++) {
    const m = returnMetrics[i];
    const x = 0.5 + i * rmColW;
    rmSlide.addText(String(m.value), { x, y: 1.5, w: rmColW - 0.3, fontSize: 36, bold: true, color: primary.replace("#", ""), fontFace: "Arial", align: "center" });
    rmSlide.addText(m.label, { x, y: 2.5, w: rmColW - 0.3, fontSize: 14, color: "6B7280", fontFace: "Arial", align: "center" });
  }

  // Additional metrics as bullets
  const addlMetrics = [];
  if (rm.unleveredIrr != null) addlMetrics.push("Unlevered IRR: " + rm.unleveredIrr + "%");
  if (rm.gpIrr != null) addlMetrics.push("GP IRR: " + rm.gpIrr + "%");
  if (rm.paybackPeriod != null) addlMetrics.push("Payback: " + rm.paybackPeriod + " years");
  if (rm.peakEquity != null) addlMetrics.push("Peak Equity: $" + (rm.peakEquity / 1000000).toFixed(1) + "M");

  if (addlMetrics.length > 0) {
    const addlBullets = addlMetrics.map(t => ({ text: t, options: { fontSize: 16, color: "333333", fontFace: "Arial", bullet: { type: "bullet" }, paraSpaceAfter: 8 } }));
    rmSlide.addText(addlBullets, { x: 0.7, y: 3.5, w: "85%", h: 3.0, valign: "top" });
  }

  rmSlide.addText(disclosure, { x: 0.3, y: 6.8, w: "95%", fontSize: 8, color: "808080", fontFace: "Arial", italic: true });

  // Slide 4: Sensitivity
  const sensSlide = pptx.addSlide();
  sensSlide.addShape(pptx.shapes.RECTANGLE, { x: 0, y: 0, w: "100%", h: 0.06, fill: { color: primary.replace("#", "") } });
  sensSlide.addText("Sensitivity Analysis", { x: 0.5, y: 0.3, w: "90%", fontSize: 28, bold: true, color: secondary.replace("#", ""), fontFace: "Arial" });

  const sensData = data.sensitivityData || {};
  const sensBullets = [];
  if (sensData.breakEvenExitCap != null) sensBullets.push("Break-even exit cap: " + sensData.breakEvenExitCap + "%");
  if (sensData.breakEvenVacancy != null) sensBullets.push("Break-even vacancy: " + sensData.breakEvenVacancy + "%");
  if (sensData.breakEvenRentGrowth != null) sensBullets.push("Break-even rent growth: " + sensData.breakEvenRentGrowth + "%");
  if (sensData.highlights && Array.isArray(sensData.highlights)) {
    for (const h of sensData.highlights) sensBullets.push(typeof h === "string" ? h : h.text || "");
  }

  if (sensBullets.length > 0) {
    const sBullets = sensBullets.map(t => ({ text: t, options: { fontSize: 16, color: "333333", fontFace: "Arial", bullet: { type: "bullet" }, paraSpaceAfter: 8 } }));
    sensSlide.addText(sBullets, { x: 0.7, y: 1.2, w: "85%", h: 4.5, valign: "top" });
  } else {
    sensSlide.addText("Sensitivity data to be populated from model outputs.", { x: 0.5, y: 2.0, w: "90%", fontSize: 16, color: "6B7280", fontFace: "Arial" });
  }

  sensSlide.addText(disclosure, { x: 0.3, y: 6.8, w: "95%", fontSize: 8, color: "808080", fontFace: "Arial", italic: true });

  // Slide 5: Risk Factors
  const riskSlide = pptx.addSlide();
  riskSlide.addShape(pptx.shapes.RECTANGLE, { x: 0, y: 0, w: "100%", h: 0.06, fill: { color: primary.replace("#", "") } });
  riskSlide.addText("Risk Factors", { x: 0.5, y: 0.3, w: "90%", fontSize: 28, bold: true, color: secondary.replace("#", ""), fontFace: "Arial" });

  const riskFactors = data.riskFactors || [];
  if (riskFactors.length > 0) {
    const riskBullets = riskFactors.map(r => ({
      text: typeof r === "string" ? r : (r.title || r.name || "") + (r.description ? ": " + r.description : ""),
      options: { fontSize: 16, color: "333333", fontFace: "Arial", bullet: { type: "bullet" }, paraSpaceAfter: 8 },
    }));
    riskSlide.addText(riskBullets, { x: 0.7, y: 1.2, w: "85%", h: 4.5, valign: "top" });
  } else {
    const defaultRisks = [
      "Market risk: changes in cap rates, rent growth, or vacancy from underwriting assumptions",
      "Construction risk: cost overruns, delays, or quality issues during development",
      "Interest rate risk: floating rate exposure on construction or permanent debt",
      "Regulatory risk: zoning, entitlement, or compliance changes",
      "Capital risk: inability to raise planned equity or secure planned debt",
    ];
    const defBullets = defaultRisks.map(t => ({ text: t, options: { fontSize: 16, color: "333333", fontFace: "Arial", bullet: { type: "bullet" }, paraSpaceAfter: 8 } }));
    riskSlide.addText(defBullets, { x: 0.7, y: 1.2, w: "85%", h: 4.5, valign: "top" });
  }

  riskSlide.addText(disclosure, { x: 0.3, y: 6.8, w: "95%", fontSize: 8, color: "808080", fontFace: "Arial", italic: true });

  // Closing slide
  const closingSlide = pptx.addSlide();
  closingSlide.background = { color: secondary.replace("#", "") };
  closingSlide.addText("Thank You", { x: 0.5, y: 2.5, w: "90%", fontSize: 36, bold: true, color: "FFFFFF", fontFace: "Arial", align: "center" });
  if (data.contactInfo) {
    closingSlide.addText(data.contactInfo, { x: 0.5, y: 3.5, w: "90%", fontSize: 18, color: primary.replace("#", ""), fontFace: "Arial", align: "center" });
  }
  closingSlide.addText(disclosure, { x: 0.3, y: 6.8, w: "95%", fontSize: 8, color: "808080", fontFace: "Arial", italic: true });

  const uint8 = await pptx.write({ outputType: "nodebuffer" });
  return Buffer.from(uint8);
}

function detectImageType(buffer) {
  if (!buffer || buffer.length < 4) return "png";
  // PNG: 89 50 4E 47
  if (buffer[0] === 0x89 && buffer[1] === 0x50) return "png";
  // JPEG: FF D8 FF
  if (buffer[0] === 0xff && buffer[1] === 0xd8) return "jpeg";
  return "png";
}

module.exports = { generatePptx };
