// services/documentEngine/generators/pptxGenerator.js
// PPTX generation via pptxgenjs — covers deck-standard + cs-investor-slides
//
// Design system (matches TitleApp pitch deck + RE development deck):
//   Dark bg:   #0D1B2A   Light bg:  #EEF2F6
//   Purple:    #6B46C1   Accent:    #A78BFA
//   Gray text: #64748B   Muted:     #99AABB
//   Font:      Calibri   Layout:    Alternating dark/light slides

const PptxGenJS = require("pptxgenjs");
const { COLORS } = require("../templates/layouts");

// ─── Design helpers ──────────────────────────────────────

const FONT = "Calibri";

function strip(hex) { return (hex || "").replace("#", ""); }

function isDark(slideIndex) {
  // Slide 0 (title) and odd-indexed content slides get dark bg
  // Even-indexed content slides get light bg — matching deck alternation
  return slideIndex % 2 === 0;
}

function addFooter(slide, pptx, text, slideNum, totalSlides, opts) {
  const { dark, primary, muted } = opts;
  const color = dark ? strip(muted) : strip(muted);
  const footerLine = text + (slideNum ? `\n${slideNum} / ${totalSlides}` : "");
  slide.addText(footerLine, {
    x: 0.5, y: 6.75, w: "90%",
    fontSize: 8, color, fontFace: FONT, align: "left",
  });
}

function addDisclosure(slide, disclosure, dark) {
  slide.addText(disclosure, {
    x: 0.3, y: 7.15, w: "95%",
    fontSize: 7, color: dark ? "556677" : "999999",
    fontFace: FONT, italic: true,
  });
}


// ═══════════════════════════════════════════════════════════
// STANDARD DECK (deck-standard template)
// ═══════════════════════════════════════════════════════════

async function generatePptx({ template, data, brand, logoBuffer }) {
  if (template.id === "cs-investor-slides") {
    return generateInvestorSlides({ template, data, brand, logoBuffer });
  }

  const pptx = new PptxGenJS();
  pptx.author = "TitleApp Document Engine";
  pptx.company = brand.name || "TitleApp";
  pptx.title = data.title || "Untitled Presentation";
  pptx.subject = data.subtitle || "";
  pptx.layout = "LAYOUT_WIDE";

  const primary = brand.primaryColor || COLORS.primary;
  const secondary = brand.secondaryColor || COLORS.secondary;
  const accent = brand.accentColor || COLORS.accent || primary;
  const lightBg = COLORS.lightBg || "EEF2F6";
  const textMuted = COLORS.textMuted || "99AABB";
  const textLight = COLORS.textLight || "64748B";
  const disclosure = brand.aiDisclosure ||
    "Generated by a TitleApp Digital Worker. AI-assisted — human review recommended.";
  const footerBase = brand.footerText || "titleapp.ai";
  const suiteName = data.suiteName || "";
  const footerText = suiteName
    ? `${footerBase}  ·  ${suiteName}`
    : footerBase;

  const slides = data.slides || [];
  const totalSlides = slides.length + 2; // title + content + closing

  // ── Slide 1: Title (dark) ──
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: strip(secondary) };

  if (logoBuffer) {
    try {
      const base64 = logoBuffer.toString("base64");
      const ext = detectImageType(logoBuffer);
      titleSlide.addImage({
        data: `image/${ext};base64,${base64}`,
        x: 0.5, y: 0.4, h: 0.8,
        sizing: { type: "contain", h: 0.8 },
      });
    } catch (_) { /* skip */ }
  }

  titleSlide.addText(data.title || "Untitled", {
    x: 0.5, y: 1.8, w: "90%",
    fontSize: 36, bold: true, color: "FFFFFF", fontFace: FONT,
  });

  if (data.subtitle) {
    titleSlide.addText(data.subtitle, {
      x: 0.5, y: 2.8, w: "90%",
      fontSize: 18, color: strip(accent), fontFace: FONT,
    });
  }

  const metaParts = [
    data.presenter,
    data.date || new Date().toLocaleDateString("en-US", { year: "numeric", month: "long" }),
  ].filter(Boolean);
  if (metaParts.length) {
    titleSlide.addText(metaParts.join("  |  "), {
      x: 0.5, y: 4.0, w: "90%",
      fontSize: 12, color: strip(textMuted), fontFace: FONT,
    });
  }

  addDisclosure(titleSlide, disclosure, true);

  // ── Content slides (alternating dark/light) ──
  for (let i = 0; i < slides.length; i++) {
    const sd = slides[i];
    const slide = pptx.addSlide();
    const dark = i % 2 === 0; // first content slide = dark, then alternates
    const bgColor = dark ? strip(secondary) : strip(lightBg);
    slide.background = { color: bgColor };

    const titleColor = dark ? "FFFFFF" : strip(secondary);
    const subtitleColor = dark ? strip(textMuted) : strip(textLight);
    const bodyColor = dark ? "DDDDDD" : strip(secondary);
    const metricColor = dark ? strip(accent) : strip(primary);

    // Slide title
    slide.addText((sd.title || "").toUpperCase(), {
      x: 0.5, y: 0.3, w: "90%",
      fontSize: 11, bold: true, color: strip(primary),
      fontFace: FONT, letterSpacing: 2,
    });

    let contentY = 0.7;

    // Subtitle / headline
    if (sd.subtitle) {
      slide.addText(sd.subtitle, {
        x: 0.5, y: contentY, w: "90%",
        fontSize: 22, bold: true, color: titleColor, fontFace: FONT,
      });
      contentY += 0.8;
    }

    // Bullet points
    if (sd.bullets && Array.isArray(sd.bullets)) {
      const bulletTexts = sd.bullets.map((b) => ({
        text: typeof b === "string" ? b : b.text || "",
        options: {
          fontSize: 14, color: bodyColor, fontFace: FONT,
          bullet: { type: "bullet", color: strip(primary) },
          paraSpaceAfter: 8,
        },
      }));
      slide.addText(bulletTexts, {
        x: 0.7, y: contentY, w: "85%", h: 4.2, valign: "top",
      });
    }

    // Body text
    if (sd.body && !sd.bullets) {
      slide.addText(sd.body, {
        x: 0.5, y: contentY, w: "90%", h: 4.2,
        fontSize: 14, color: bodyColor, fontFace: FONT,
        valign: "top", lineSpacingMultiple: 1.3,
      });
    }

    // Metrics row
    if (sd.metrics && Array.isArray(sd.metrics)) {
      const metricsY = sd.bullets || sd.body ? 5.2 : 2.0;
      const count = Math.min(sd.metrics.length, 4);
      const colW = 11 / count;

      for (let j = 0; j < count; j++) {
        const m = sd.metrics[j];
        const x = 0.8 + j * colW;

        slide.addText(String(m.value || "0"), {
          x, y: metricsY, w: colW - 0.3,
          fontSize: 28, bold: true, color: metricColor,
          fontFace: FONT, align: "center",
        });
        slide.addText(m.label || "", {
          x, y: metricsY + 0.55, w: colW - 0.3,
          fontSize: 10, color: subtitleColor,
          fontFace: FONT, align: "center",
        });
      }
    }

    if (sd.notes) slide.addNotes(sd.notes);

    addFooter(slide, pptx, footerText, i + 2, totalSlides,
      { dark, primary, muted: textMuted });
    addDisclosure(slide, disclosure, dark);
  }

  // ── Closing slide (dark) ──
  const closingSlide = pptx.addSlide();
  closingSlide.background = { color: strip(secondary) };

  closingSlide.addText(data.closingTitle || brand.name || "TITLEAPP", {
    x: 0.5, y: 1.8, w: "90%",
    fontSize: 36, bold: true, color: "FFFFFF", fontFace: FONT, align: "center",
  });

  if (data.closingSubtitle || data.contactInfo) {
    closingSlide.addText(data.closingSubtitle || data.contactInfo || "", {
      x: 0.5, y: 2.8, w: "90%",
      fontSize: 16, color: strip(accent), fontFace: FONT, align: "center",
    });
  }

  addFooter(closingSlide, pptx, footerText, totalSlides, totalSlides,
    { dark: true, primary, muted: textMuted });
  addDisclosure(closingSlide, disclosure, true);

  const uint8 = await pptx.write({ outputType: "nodebuffer" });
  return Buffer.from(uint8);
}


// ═══════════════════════════════════════════════════════════
// CAPITAL STACK / INVESTOR SLIDES (cs-investor-slides)
// ═══════════════════════════════════════════════════════════

async function generateInvestorSlides({ template, data, brand, logoBuffer }) {
  const pptx = new PptxGenJS();
  pptx.author = "TitleApp Document Engine";
  pptx.company = brand.name || "TitleApp";
  pptx.title = data.title || "Capital Stack — Investor Presentation";
  pptx.subject = data.subtitle || "";
  pptx.layout = "LAYOUT_WIDE";

  const primary = brand.primaryColor || COLORS.primary;
  const secondary = brand.secondaryColor || COLORS.secondary;
  const accent = brand.accentColor || COLORS.accent || primary;
  const lightBg = COLORS.lightBg || "EEF2F6";
  const textMuted = COLORS.textMuted || "99AABB";
  const textLight = COLORS.textLight || "64748B";
  const disclosure = brand.aiDisclosure ||
    "Generated by a TitleApp Digital Worker. AI-assisted — human review recommended.";
  const footerText = brand.footerText || "titleapp.ai";

  // ── Slide 1: Title / Stack Overview (dark) ──
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: strip(secondary) };

  if (logoBuffer) {
    try {
      const base64 = logoBuffer.toString("base64");
      const ext = detectImageType(logoBuffer);
      titleSlide.addImage({
        data: `image/${ext};base64,${base64}`,
        x: 0.5, y: 0.4, h: 0.8,
        sizing: { type: "contain", h: 0.8 },
      });
    } catch (_) { /* skip */ }
  }

  titleSlide.addText(data.title || "Capital Stack Overview", {
    x: 0.5, y: 1.8, w: "90%",
    fontSize: 36, bold: true, color: "FFFFFF", fontFace: FONT,
  });

  if (data.dealName || data.subtitle) {
    titleSlide.addText(data.dealName || data.subtitle, {
      x: 0.5, y: 2.8, w: "90%",
      fontSize: 18, color: strip(accent), fontFace: FONT,
    });
  }

  const metaLine = [
    data.presenter,
    data.date || new Date().toLocaleDateString("en-US", { year: "numeric", month: "long" }),
  ].filter(Boolean).join("  |  ");
  if (metaLine) {
    titleSlide.addText(metaLine, {
      x: 0.5, y: 4.0, w: "90%",
      fontSize: 12, color: strip(textMuted), fontFace: FONT,
    });
  }

  // Stack summary metrics
  const layers = data.capitalLayers || [];
  const totalSources = layers.reduce((s, l) => s + (l.amount || 0), 0);
  if (totalSources > 0) {
    const stackMetrics = [
      { label: "Total Capital", value: "$" + (totalSources / 1000000).toFixed(1) + "M" },
      { label: "Sources", value: String(layers.length) },
      { label: "WACC", value: (data.wacc || data.returnMetrics?.wacc || "N/A") + "%" },
    ];
    const count = stackMetrics.length;
    const colW = 11 / count;
    for (let i = 0; i < count; i++) {
      const m = stackMetrics[i];
      const x = 0.8 + i * colW;
      titleSlide.addText(String(m.value), {
        x, y: 5.2, w: colW - 0.3,
        fontSize: 28, bold: true, color: strip(accent), fontFace: FONT, align: "center",
      });
      titleSlide.addText(m.label, {
        x, y: 5.8, w: colW - 0.3,
        fontSize: 10, color: strip(textMuted), fontFace: FONT, align: "center",
      });
    }
  }

  addFooter(titleSlide, pptx, footerText, 1, 6, { dark: true, primary, muted: textMuted });
  addDisclosure(titleSlide, disclosure, true);

  // ── Slide 2: Sources & Uses (light) ──
  const suSlide = pptx.addSlide();
  suSlide.background = { color: strip(lightBg) };

  suSlide.addText("SOURCES & USES", {
    x: 0.5, y: 0.3, w: "90%",
    fontSize: 11, bold: true, color: strip(primary), fontFace: FONT, letterSpacing: 2,
  });
  suSlide.addText("Capital Structure", {
    x: 0.5, y: 0.7, w: "90%",
    fontSize: 22, bold: true, color: strip(secondary), fontFace: FONT,
  });

  const suBullets = layers.map((l) => {
    const pct = totalSources > 0 ? ((l.amount || 0) / totalSources * 100).toFixed(0) : "0";
    return {
      text: (l.source || l.type || "") + ": $" + ((l.amount || 0) / 1000000).toFixed(1) + "M (" + pct + "%)",
      options: { fontSize: 14, color: strip(secondary), fontFace: FONT, bullet: { type: "bullet", color: strip(primary) }, paraSpaceAfter: 8 },
    };
  });
  if (suBullets.length > 0) {
    suSlide.addText(suBullets, { x: 0.7, y: 1.4, w: "45%", h: 4.5, valign: "top" });
  }

  const uses = data.uses || [];
  if (uses.length > 0) {
    suSlide.addText("Uses", {
      x: 6.5, y: 1.2, w: "40%",
      fontSize: 16, bold: true, color: strip(primary), fontFace: FONT,
    });
    const useBullets = uses.map((u) => ({
      text: (u.category || u.name || "") + ": $" + ((u.amount || 0) / 1000000).toFixed(1) + "M",
      options: { fontSize: 14, color: strip(secondary), fontFace: FONT, bullet: { type: "bullet", color: strip(primary) }, paraSpaceAfter: 8 },
    }));
    suSlide.addText(useBullets, { x: 6.5, y: 1.8, w: "40%", h: 4.0, valign: "top" });
  }

  addFooter(suSlide, pptx, footerText, 2, 6, { dark: false, primary, muted: textMuted });
  addDisclosure(suSlide, disclosure, false);

  // ── Slide 3: Return Metrics (dark) ──
  const rmSlide = pptx.addSlide();
  rmSlide.background = { color: strip(secondary) };

  rmSlide.addText("RETURN METRICS", {
    x: 0.5, y: 0.3, w: "90%",
    fontSize: 11, bold: true, color: strip(primary), fontFace: FONT, letterSpacing: 2,
  });

  const rm = data.returnMetrics || {};
  const returnMetrics = [
    { label: "Levered IRR", value: rm.leveredIrr != null ? rm.leveredIrr + "%" : "N/A" },
    { label: "LP IRR", value: rm.lpIrr != null ? rm.lpIrr + "%" : "N/A" },
    { label: "Equity Multiple", value: rm.equityMultiple != null ? rm.equityMultiple + "x" : "N/A" },
    { label: "Cash-on-Cash Y1", value: rm.cashOnCashY1 != null ? rm.cashOnCashY1 + "%" : (Array.isArray(rm.cashOnCash) && rm.cashOnCash[0] != null ? rm.cashOnCash[0] + "%" : "N/A") },
  ];

  const rmCount = returnMetrics.length;
  const rmColW = 11 / rmCount;
  for (let i = 0; i < rmCount; i++) {
    const m = returnMetrics[i];
    const x = 0.8 + i * rmColW;
    rmSlide.addText(String(m.value), {
      x, y: 1.5, w: rmColW - 0.3,
      fontSize: 36, bold: true, color: strip(accent), fontFace: FONT, align: "center",
    });
    rmSlide.addText(m.label, {
      x, y: 2.5, w: rmColW - 0.3,
      fontSize: 12, color: strip(textMuted), fontFace: FONT, align: "center",
    });
  }

  const addlMetrics = [];
  if (rm.unleveredIrr != null) addlMetrics.push("Unlevered IRR: " + rm.unleveredIrr + "%");
  if (rm.gpIrr != null) addlMetrics.push("GP IRR: " + rm.gpIrr + "%");
  if (rm.paybackPeriod != null) addlMetrics.push("Payback: " + rm.paybackPeriod + " years");
  if (rm.peakEquity != null) addlMetrics.push("Peak Equity: $" + (rm.peakEquity / 1000000).toFixed(1) + "M");

  if (addlMetrics.length > 0) {
    const addlBullets = addlMetrics.map((t) => ({
      text: t,
      options: { fontSize: 14, color: "DDDDDD", fontFace: FONT, bullet: { type: "bullet", color: strip(primary) }, paraSpaceAfter: 8 },
    }));
    rmSlide.addText(addlBullets, { x: 0.7, y: 3.5, w: "85%", h: 3.0, valign: "top" });
  }

  addFooter(rmSlide, pptx, footerText, 3, 6, { dark: true, primary, muted: textMuted });
  addDisclosure(rmSlide, disclosure, true);

  // ── Slide 4: Sensitivity (light) ──
  const sensSlide = pptx.addSlide();
  sensSlide.background = { color: strip(lightBg) };

  sensSlide.addText("SENSITIVITY ANALYSIS", {
    x: 0.5, y: 0.3, w: "90%",
    fontSize: 11, bold: true, color: strip(primary), fontFace: FONT, letterSpacing: 2,
  });

  const sensData = data.sensitivityData || {};
  const sensBullets = [];
  if (sensData.breakEvenExitCap != null) sensBullets.push("Break-even exit cap: " + sensData.breakEvenExitCap + "%");
  if (sensData.breakEvenVacancy != null) sensBullets.push("Break-even vacancy: " + sensData.breakEvenVacancy + "%");
  if (sensData.breakEvenRentGrowth != null) sensBullets.push("Break-even rent growth: " + sensData.breakEvenRentGrowth + "%");
  if (sensData.highlights && Array.isArray(sensData.highlights)) {
    for (const h of sensData.highlights) sensBullets.push(typeof h === "string" ? h : h.text || "");
  }

  if (sensBullets.length > 0) {
    const sBullets = sensBullets.map((t) => ({
      text: t,
      options: { fontSize: 14, color: strip(secondary), fontFace: FONT, bullet: { type: "bullet", color: strip(primary) }, paraSpaceAfter: 8 },
    }));
    sensSlide.addText(sBullets, { x: 0.7, y: 1.0, w: "85%", h: 5.0, valign: "top" });
  } else {
    sensSlide.addText("Sensitivity data to be populated from model outputs.", {
      x: 0.5, y: 2.0, w: "90%",
      fontSize: 14, color: strip(textLight), fontFace: FONT,
    });
  }

  addFooter(sensSlide, pptx, footerText, 4, 6, { dark: false, primary, muted: textMuted });
  addDisclosure(sensSlide, disclosure, false);

  // ── Slide 5: Risk Factors (dark) ──
  const riskSlide = pptx.addSlide();
  riskSlide.background = { color: strip(secondary) };

  riskSlide.addText("RISK FACTORS", {
    x: 0.5, y: 0.3, w: "90%",
    fontSize: 11, bold: true, color: strip(primary), fontFace: FONT, letterSpacing: 2,
  });

  const riskFactors = data.riskFactors || [];
  const riskItems = riskFactors.length > 0
    ? riskFactors.map((r) => typeof r === "string" ? r : (r.title || r.name || "") + (r.description ? ": " + r.description : ""))
    : [
      "Market risk: changes in cap rates, rent growth, or vacancy from underwriting assumptions",
      "Construction risk: cost overruns, delays, or quality issues during development",
      "Interest rate risk: floating rate exposure on construction or permanent debt",
      "Regulatory risk: zoning, entitlement, or compliance changes",
      "Capital risk: inability to raise planned equity or secure planned debt",
    ];

  const riskBullets = riskItems.map((t) => ({
    text: t,
    options: { fontSize: 14, color: "DDDDDD", fontFace: FONT, bullet: { type: "bullet", color: strip(primary) }, paraSpaceAfter: 8 },
  }));
  riskSlide.addText(riskBullets, { x: 0.7, y: 1.0, w: "85%", h: 5.0, valign: "top" });

  addFooter(riskSlide, pptx, footerText, 5, 6, { dark: true, primary, muted: textMuted });
  addDisclosure(riskSlide, disclosure, true);

  // ── Slide 6: Closing (dark) ──
  const closingSlide = pptx.addSlide();
  closingSlide.background = { color: strip(secondary) };

  closingSlide.addText(brand.name || "TITLEAPP", {
    x: 0.5, y: 1.8, w: "90%",
    fontSize: 36, bold: true, color: "FFFFFF", fontFace: FONT, align: "center",
  });
  if (data.contactInfo) {
    closingSlide.addText(data.contactInfo, {
      x: 0.5, y: 2.8, w: "90%",
      fontSize: 16, color: strip(accent), fontFace: FONT, align: "center",
    });
  }

  addFooter(closingSlide, pptx, footerText, 6, 6, { dark: true, primary, muted: textMuted });
  addDisclosure(closingSlide, disclosure, true);

  const uint8 = await pptx.write({ outputType: "nodebuffer" });
  return Buffer.from(uint8);
}


// ─── Helpers ─────────────────────────────────────────────

function detectImageType(buffer) {
  if (!buffer || buffer.length < 4) return "png";
  if (buffer[0] === 0x89 && buffer[1] === 0x50) return "png";
  if (buffer[0] === 0xff && buffer[1] === 0xd8) return "jpeg";
  return "png";
}

module.exports = { generatePptx };
