// scripts/pullREWorkerData.js — pull REAL ATTOM data for each RE worker's
// subject property (the #34 "pre-pull now" path). Mirrors the cre-analyst
// pattern: pull once, emit a committed data file the canvas reads. Honest by
// construction — only fields ATTOM actually returns are marked real; the
// specialized analysis blocks (liens/easements/zoning verdict) stay modeled and
// are labeled as such in the canvas builder.
//
// Run:  ATTOM_API_KEY=$(firebase functions:secrets:access ATTOM_API_KEY) \
//       node scripts/pullREWorkerData.js
//
// ATTOM endpoints used: /property/detail, /saleshistory/detail, /avm/detail

const ATTOM_BASE = "https://api.gateway.attomdata.com/propertyapi/v1.0.0";
const KEY = process.env.ATTOM_API_KEY;

// Subject property per worker. Chosen for ATTOM coverage + fit to the worker's
// narrative. address1 = street, address2 = "CITY, ST".
const SUBJECTS = {
  "title-abstract-001": { address1: "325 BATTERY ST",   address2: "SAN FRANCISCO, CA" },
  "law-landuse-001":    { address1: "658 FRONT ST",     address2: "LAHAINA, HI" },
  "zoning-001":         { address1: "658 FRONT ST",     address2: "LAHAINA, HI" },
  "feasibility-001":    { address1: "505 FRONT ST",     address2: "LAHAINA, HI" },
  "site-recon-001":     { address1: "12625 FREDERICK ST", address2: "MORENO VALLEY, CA" },
};

async function attomGet(path, params) {
  const url = new URL(ATTOM_BASE + path);
  Object.entries(params).forEach(([k, v]) => url.searchParams.set(k, v));
  try {
    const resp = await fetch(url.toString(), { headers: { apikey: KEY, accept: "application/json" } });
    const json = await resp.json();
    return { ok: resp.ok, status: resp.status, json };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

function summarize(slug, subj, prof, sales) {
  const p = prof.json?.property?.[0] || {};
  const salesArr = sales.json?.property?.[0]?.salehistory || sales.json?.property?.[0]?.saleHistory || [];
  const found = !!(p.identifier?.apn);
  return {
    slug,
    found,
    address: p.address?.oneLine || `${p.address?.line1 || subj.address1}, ${p.address?.line2 || subj.address2}`,
    apn: p.identifier?.apn || null,
    fips: p.identifier?.fips || null,
    lat: p.location?.latitude || null,
    lng: p.location?.longitude || null,
    propType: p.summary?.proptype || p.summary?.propclass || null,
    yearBuilt: p.summary?.yearbuilt || null,
    lotSizeAcres: p.lot?.lotsize1 || null,
    bldgSqft: p.building?.size?.universalsize || p.building?.size?.bldgsize || null,
    ownerName: p.owner?.owner1?.fullname || p.owner?.owner1?.lastname || p.assessment?.owner?.owner1?.lastname || null,
    assessedTotal: p.assessment?.assessed?.assdttlvalue || null,
    marketTotal: p.assessment?.market?.mktttlvalue || null,
    taxAmt: p.assessment?.tax?.taxamt || null,
    taxYear: p.assessment?.tax?.taxyear || null,
    lastSaleAmt: p.sale?.amount?.saleamt || null,
    lastSaleDate: p.sale?.amount?.salerecdate || p.sale?.saleTransDate || null,
    salesCount: Array.isArray(salesArr) ? salesArr.length : 0,
    sales: (Array.isArray(salesArr) ? salesArr : []).slice(0, 6).map(s => ({
      date: s.saleTransDate || s.amount?.salerecdate || s.saletrandate || null,
      amount: s.amount?.saleamt || s.saleamt || null,
      doc: s.saleTransType || s.amount?.saledoctype || null,
    })),
  };
}

async function pullOne(slug, subj) {
  const prof = await attomGet("/property/detail", subj);
  const sales = await attomGet("/saleshistory/detail", subj);
  return summarize(slug, subj, prof, sales);
}

(async () => {
  if (!KEY) { console.error("ATTOM_API_KEY not set"); process.exit(1); }
  const fs = require("fs");
  const out = {};
  for (const [slug, subj] of Object.entries(SUBJECTS)) {
    process.stderr.write(`pulling ${slug} (${subj.address1})...\n`);
    out[slug] = await pullOne(slug, subj);
  }
  const banner = "// AUTO-GENERATED by functions/functions/scripts/pullREWorkerData.js — REAL ATTOM data.\n" +
                 "// Parcel facts (APN, type, year, lot, sqft, lat/lng) + sale history are live ATTOM pulls.\n" +
                 "// Regenerate to refresh. Do NOT hand-edit.\n";
  const target = "../../../apps/business/src/components/canvas/reWorkerAttomData.js";
  fs.writeFileSync(require("path").join(__dirname, target),
    banner + "export const RE_WORKER_ATTOM = " + JSON.stringify(out, null, 2) + ";\n");
  process.stderr.write(`\nwrote ${target}\n`);
  console.log(JSON.stringify(out, null, 2));
})();
