// services/documentEngine/branding.js
// Loads brand configuration and logo assets per tenant

const admin = require("firebase-admin");

function getDb() { return admin.firestore(); }

const SYSTEM_BRAND = {
  id: "system",
  name: "TitleApp",
  primaryColor: "#7c3aed",
  secondaryColor: "#1e1b4b",
  accentColor: "#a78bfa",
  fontFamily: "Helvetica",
  logoPath: null,
  footerText: "Generated by TitleApp.ai",
  aiDisclosure:
    "This document was generated by a TitleApp Digital Worker with the assistance of artificial intelligence. All data should be independently verified. Human review recommended.",
};

const STORAGE_BUCKET =
  process.env.STORAGE_BUCKET || "title-app-alpha.firebasestorage.app";

async function getBrandConfig(tenantId) {
  if (!tenantId) return { ...SYSTEM_BRAND };

  try {
    const snap = await getDb().collection("brandAssets").doc(tenantId).get();
    if (!snap.exists) return { ...SYSTEM_BRAND };
    const custom = snap.data();
    return { ...SYSTEM_BRAND, ...custom, id: tenantId };
  } catch (e) {
    console.warn("branding: failed to load brand for", tenantId, e.message);
    return { ...SYSTEM_BRAND };
  }
}

async function getLogoBuffer(brandConfig) {
  if (!brandConfig || !brandConfig.logoPath) return null;
  try {
    const bucket = admin.storage().bucket(STORAGE_BUCKET);
    const [buffer] = await bucket.file(brandConfig.logoPath).download();
    return buffer;
  } catch (e) {
    console.warn("branding: failed to load logo", e.message);
    return null;
  }
}

module.exports = { getBrandConfig, getLogoBuffer, SYSTEM_BRAND };
