"use strict";

const PDFDocument = require("pdfkit");

function hexToArray(hex) {
  const h = (hex || "#000000").replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

async function generatePdf(templateDef, content, branding) {
  return new Promise((resolve, reject) => {
    const styles = templateDef.defaultStyles || {};
    const margins = styles.margins || { top: 72, bottom: 72, left: 72, right: 72 };
    const fontSize = styles.fontSize || 11;
    const headerSize = styles.headerSize || 16;
    const subheaderSize = styles.subheaderSize || 13;
    const accentColor = hexToArray(branding.accentColor || styles.accentColor || "#7c3aed");
    const textColor = hexToArray(branding.textColor || styles.textColor || "#1a1a1a");
    const mutedColor = hexToArray(branding.mutedColor || styles.mutedColor || "#6b7280");

    const doc = new PDFDocument({
      size: "LETTER",
      margins: { top: margins.top, bottom: margins.bottom, left: margins.left, right: margins.right },
      bufferPages: true,
      info: {
        Title: content.title || content.coverPage?.title || templateDef.name,
        Author: branding.companyName || "TitleApp",
        Creator: "TitleApp Document Engine",
      },
    });

    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => {
      const buffer = Buffer.concat(chunks);
      resolve({ buffer, pageCount: doc._pageCount || 1 });
    });
    doc.on("error", reject);

    const contentWidth = 612 - margins.left - margins.right;

    function heading(text, level) {
      const sz = level === 1 ? headerSize : subheaderSize;
      doc.moveDown(0.5);
      doc.fillColor(accentColor).fontSize(sz).font("Helvetica-Bold").text(text || "");
      doc.moveDown(0.3);
    }

    function body(text) {
      doc.fillColor(textColor).fontSize(fontSize).font("Helvetica").text(text || "", { lineGap: 3 });
    }

    function muted(text, opts = {}) {
      doc.fillColor(mutedColor).fontSize(opts.size || 10).font("Helvetica").text(text || "", opts);
    }

    function hr() {
      doc.moveDown(0.3);
      doc.strokeColor(mutedColor).lineWidth(0.5)
        .moveTo(margins.left, doc.y)
        .lineTo(612 - margins.right, doc.y)
        .stroke();
      doc.moveDown(0.5);
    }

    function embedLogo() {
      if (branding.logoBuffer) {
        try {
          doc.image(branding.logoBuffer, margins.left, margins.top, { width: 100 });
          doc.moveDown(3);
        } catch (e) {
          // Logo embedding failed, skip
        }
      }
    }

    function addFooters() {
      const range = doc.bufferedPageRange();
      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(i);
        const footerY = 792 - margins.bottom + 10;
        doc.fillColor(mutedColor).fontSize(7).font("Helvetica");
        doc.text(
          branding.footerText || "Generated by TitleApp Digital Worker. AI-assisted analysis — human review recommended.",
          margins.left, footerY, { width: contentWidth - 50, lineBreak: false }
        );
        doc.text(`Page ${i + 1} of ${range.count}`, 0, footerY, {
          width: 612 - margins.right,
          align: "right",
        });
      }
    }

    // --- Template-specific rendering ---

    const templateId = templateDef.id;

    if (templateId === "report-standard") {
      // Cover page
      embedLogo();
      doc.y = 400;
      doc.fillColor(accentColor).fontSize(28).font("Helvetica-Bold")
        .text(content.coverPage?.title || "Report", { align: "left" });
      doc.moveDown(0.3);
      if (content.coverPage?.subtitle) {
        doc.fillColor(textColor).fontSize(16).font("Helvetica")
          .text(content.coverPage.subtitle);
      }
      doc.moveDown(1);
      if (content.coverPage?.author) muted(`Prepared by: ${content.coverPage.author}`);
      if (content.coverPage?.preparedFor) muted(`Prepared for: ${content.coverPage.preparedFor}`);
      if (content.coverPage?.date) muted(content.coverPage.date);

      // Executive summary
      doc.addPage();
      heading("Executive Summary", 1);
      const summary = typeof content.executiveSummary === "string"
        ? content.executiveSummary
        : (content.executiveSummary || {}).text || "";
      body(summary);

      if (content.executiveSummary?.highlights) {
        doc.moveDown(0.5);
        for (const h of content.executiveSummary.highlights) {
          doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
            .text(`${h.label}: `, { continued: true });
          doc.font("Helvetica").text(h.value || "");
        }
      }

      // Body sections
      for (const section of (content.sections || [])) {
        doc.moveDown(0.5);
        heading(section.heading || "Section", 2);
        body(section.content || "");
        if (section.table) renderTable(section.table);
      }

      // Appendix
      if (content.appendix) {
        hr();
        heading("Appendix", 1);
        body(typeof content.appendix === "string" ? content.appendix : JSON.stringify(content.appendix, null, 2));
      }

    } else if (templateId === "memo-executive") {
      embedLogo();
      heading("MEMORANDUM", 1);
      hr();
      const hdr = content.header || {};
      for (const [label, val] of [["TO", hdr.to], ["FROM", hdr.from], ["DATE", hdr.date], ["RE", hdr.re || hdr.subject]]) {
        if (!val) continue;
        doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
          .text(`${label}: `, { continued: true });
        doc.font("Helvetica").text(val);
      }
      hr();
      doc.moveDown(0.3);
      body(content.body || "");
      if (content.recommendation) {
        doc.moveDown(0.5);
        heading("Recommendation", 2);
        body(content.recommendation);
      }

    } else if (templateId === "one-pager") {
      embedLogo();
      const hdr = content.header || {};
      heading(hdr.title || content.title || "Summary", 1);
      if (hdr.subtitle) muted(hdr.subtitle);
      doc.moveDown(0.5);

      // Metrics grid
      const metrics = content.metrics || [];
      if (metrics.length > 0) {
        const colWidth = contentWidth / 2;
        for (let i = 0; i < metrics.length; i += 2) {
          const startX = margins.left;
          const startY = doc.y;
          for (let col = 0; col < 2 && i + col < metrics.length; col++) {
            const m = metrics[i + col];
            const x = startX + col * colWidth;
            doc.fillColor(accentColor).fontSize(18).font("Helvetica-Bold")
              .text(m.value || "", x, startY, { width: colWidth - 10 });
            doc.fillColor(mutedColor).fontSize(9).font("Helvetica")
              .text(m.label || "", x, startY + 20, { width: colWidth - 10 });
          }
          doc.y = startY + 40;
        }
      }
      hr();
      body(content.body || "");
      if (content.callToAction) {
        doc.moveDown(0.5);
        doc.fillColor(accentColor).fontSize(fontSize).font("Helvetica-Bold")
          .text(content.callToAction);
      }

    } else if (templateId === "letter-formal") {
      const sender = content.sender || {};
      const recipient = content.recipient || {};
      embedLogo();
      for (const line of [sender.name, sender.title, sender.company, sender.address].filter(Boolean)) {
        muted(line);
      }
      doc.moveDown(1);
      body(content.date || new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }));
      doc.moveDown(1);
      for (const line of [recipient.name, recipient.title, recipient.company, recipient.address].filter(Boolean)) {
        body(line);
      }
      doc.moveDown(1);
      body(content.salutation || `Dear ${recipient.name || "Sir/Madam"},`);
      doc.moveDown(0.5);
      body(content.body || "");
      doc.moveDown(1.5);
      const closing = content.closing || {};
      body(closing.text || "Sincerely,");
      doc.moveDown(2);
      doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
        .text(sender.name || "");
      if (sender.title) muted(sender.title);

    } else if (templateId === "agreement-standard") {
      const hdr = content.header || {};
      heading(hdr.title || "Agreement", 1);
      muted(`Effective Date: ${hdr.effectiveDate || "___________"}`);
      doc.moveDown(0.5);

      const parties = content.parties || [];
      if (parties.length > 0) {
        heading("Parties", 2);
        for (const p of parties) {
          doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
            .text(`${p.role || "Party"}: ${p.name || ""}`);
          if (p.address) muted(p.address);
          doc.moveDown(0.2);
        }
      }

      if (content.recitals?.length > 0) {
        heading("Recitals", 2);
        for (const r of content.recitals) { body(`WHEREAS, ${r}`); doc.moveDown(0.2); }
      }

      const terms = content.terms || [];
      if (terms.length > 0) {
        heading("Terms and Conditions", 2);
        for (let i = 0; i < terms.length; i++) {
          const t = terms[i];
          doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
            .text(`${i + 1}. ${t.heading || `Section ${i + 1}`}`);
          if (t.content) body(t.content);
          doc.moveDown(0.2);
        }
      }

      const sigs = content.signatures || content.parties || [];
      if (sigs.length > 0) {
        doc.moveDown(1);
        heading("Signatures", 2);
        for (const s of sigs) {
          doc.moveDown(0.8);
          doc.strokeColor(textColor).lineWidth(0.5)
            .moveTo(margins.left, doc.y)
            .lineTo(margins.left + 200, doc.y)
            .stroke();
          doc.moveDown(0.3);
          doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
            .text(s.name || "Name: ___________");
          muted(`Role: ${s.role || "___________"}`);
          muted("Date: ___________");
        }
      }

    } else if (templateId === "ir-waterfall-report") {
      // Waterfall Distribution Report
      embedLogo();
      heading(content.dealSummary?.title || "Waterfall Distribution Report", 1);
      if (content.dealSummary) {
        const ds = content.dealSummary;
        if (ds.dealName) body(`Deal: ${ds.dealName}`);
        if (ds.dealType) body(`Type: ${ds.dealType}`);
        if (ds.totalInvested) body(`Total Invested: $${Number(ds.totalInvested).toLocaleString()}`);
        if (ds.lpInvested) body(`LP Invested: $${Number(ds.lpInvested).toLocaleString()}`);
        if (ds.gpInvested) body(`GP Invested: $${Number(ds.gpInvested).toLocaleString()}`);
        doc.moveDown(0.3);
      }

      // Performance metrics
      if (content.dealSummary?.irr || content.dealSummary?.equityMultiple) {
        heading("Performance Summary", 2);
        const perf = content.dealSummary;
        const perfMetrics = [
          perf.irr ? `IRR: ${perf.irr}` : null,
          perf.equityMultiple ? `Equity Multiple: ${perf.equityMultiple}x` : null,
          perf.dpi ? `DPI: ${perf.dpi}x` : null,
        ].filter(Boolean);
        for (const m of perfMetrics) body(m);
        doc.moveDown(0.3);
      }

      // Waterfall tiers table
      if (content.waterfallTiers && content.waterfallTiers.length > 0) {
        heading("Waterfall Structure", 2);
        renderTable({
          headers: ["Tier", "Type", "LP Split", "GP Split", "Threshold"],
          rows: content.waterfallTiers.map((t) => [
            t.name || "",
            t.type || "",
            t.lpSplit != null ? `${(t.lpSplit * 100).toFixed(0)}%` : "",
            t.gpSplit != null ? `${(t.gpSplit * 100).toFixed(0)}%` : "",
            t.threshold != null ? (t.type === "preferred" ? `${(t.threshold * 100).toFixed(1)}%` : `${(t.threshold * 100).toFixed(0)}%`) : "",
          ]),
        });
      }

      // Distribution breakdown
      if (content.distributionBreakdown && content.distributionBreakdown.length > 0) {
        doc.moveDown(0.3);
        heading("Distribution Breakdown", 2);
        renderTable({
          headers: ["Period", "Cash Flow", "LP Amount", "GP Amount"],
          rows: content.distributionBreakdown.map((p) => [
            p.label || p.period || "",
            `$${Number(p.netCashFlow || 0).toLocaleString()}`,
            `$${Number(p.lpTotal || 0).toLocaleString()}`,
            `$${Number(p.gpTotal || 0).toLocaleString()}`,
          ]),
        });
      }

      // Investor allocations
      if (content.investorAllocations && content.investorAllocations.length > 0) {
        doc.moveDown(0.3);
        heading("Investor Allocations", 2);
        renderTable({
          headers: ["Investor", "Commitment", "Share", "Distribution"],
          rows: content.investorAllocations.map((inv) => [
            inv.name || "",
            `$${Number(inv.commitmentAmount || 0).toLocaleString()}`,
            inv.share ? `${(inv.share * 100).toFixed(1)}%` : "",
            `$${Number(inv.distributionAmount || 0).toLocaleString()}`,
          ]),
        });
      }

      // Disclaimer
      doc.moveDown(1);
      muted("This is a projection based on stated assumptions. Actual returns may vary. Past performance does not guarantee future results. This document does not constitute an offer to sell or a solicitation to buy securities.");

    } else if (templateId === "ir-capital-call") {
      // Capital Call Notice
      embedLogo();
      heading("CAPITAL CALL NOTICE", 1);
      hr();
      const hdr = content.header || {};
      if (hdr.fundName) {
        doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
          .text("Fund: ", { continued: true });
        doc.font("Helvetica").text(hdr.fundName);
      }
      if (hdr.dealName) {
        doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
          .text("Deal: ", { continued: true });
        doc.font("Helvetica").text(hdr.dealName);
      }
      if (hdr.date) {
        doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
          .text("Date: ", { continued: true });
        doc.font("Helvetica").text(hdr.date);
      }
      hr();

      const cd = content.callDetails || {};
      doc.moveDown(0.3);
      heading("Call Details", 2);
      if (cd.amount) body(`Amount: $${Number(cd.amount).toLocaleString()}`);
      if (cd.dueDate) body(`Due Date: ${cd.dueDate}`);
      if (cd.purpose) body(`Purpose: ${cd.purpose}`);
      if (cd.memo) { doc.moveDown(0.3); body(cd.memo); }

      if (content.wireInstructions) {
        doc.moveDown(0.5);
        heading("Wire Instructions", 2);
        // Wire box
        const boxY = doc.y;
        doc.rect(margins.left, boxY, contentWidth, 80).stroke();
        doc.fillColor(textColor).fontSize(9).font("Helvetica")
          .text(content.wireInstructions, margins.left + 10, boxY + 10, { width: contentWidth - 20 });
        doc.y = boxY + 90;
      }

      if (content.investorAllocation) {
        doc.moveDown(0.5);
        heading("Your Allocation", 2);
        const ia = content.investorAllocation;
        if (ia.investorName) body(`Investor: ${ia.investorName}`);
        if (ia.commitmentAmount) body(`Total Commitment: $${Number(ia.commitmentAmount).toLocaleString()}`);
        if (ia.callAmount) body(`This Call: $${Number(ia.callAmount).toLocaleString()}`);
        if (ia.share) body(`Pro-Rata Share: ${(ia.share * 100).toFixed(2)}%`);
      }

      doc.moveDown(1);
      muted("Failure to fund may result in dilution or default penalties as outlined in the governing documents.");

    } else if (templateId === "ir-quarterly-report") {
      // Quarterly Investor Report
      embedLogo();
      doc.y = 400;
      const cp = content.coverPage || {};
      doc.fillColor(accentColor).fontSize(28).font("Helvetica-Bold")
        .text(cp.title || "Quarterly Investor Report", { align: "left" });
      doc.moveDown(0.3);
      if (cp.subtitle) doc.fillColor(textColor).fontSize(16).font("Helvetica").text(cp.subtitle);
      if (cp.quarter) muted(`Q${cp.quarter} ${cp.year || ""}`);
      if (cp.date) muted(cp.date);

      doc.addPage();
      heading("Portfolio Summary", 1);
      const ps = content.portfolioSummary || {};
      if (ps.totalAUM) body(`Total AUM: $${Number(ps.totalAUM).toLocaleString()}`);
      if (ps.activeDeals) body(`Active Deals: ${ps.activeDeals}`);
      if (ps.totalDistributed) body(`Total Distributed: $${Number(ps.totalDistributed).toLocaleString()}`);
      if (ps.portfolioIRR) body(`Portfolio IRR: ${ps.portfolioIRR}`);
      if (ps.narrative) { doc.moveDown(0.3); body(ps.narrative); }

      if (content.dealUpdates && content.dealUpdates.length > 0) {
        doc.moveDown(0.5);
        heading("Deal Updates", 1);
        for (const update of content.dealUpdates) {
          heading(update.dealName || "Deal", 2);
          if (update.status) body(`Status: ${update.status}`);
          if (update.narrative) body(update.narrative);
          doc.moveDown(0.2);
        }
      }

      if (content.financialSummary) {
        doc.moveDown(0.5);
        heading("Financial Summary", 1);
        body(typeof content.financialSummary === "string" ? content.financialSummary : JSON.stringify(content.financialSummary, null, 2));
      }

      if (content.outlook) {
        doc.moveDown(0.5);
        heading("Outlook", 1);
        body(content.outlook);
      }

    } else if (templateId === "ir-investor-summary") {
      // Investor Portfolio Summary
      embedLogo();
      const ip = content.investorProfile || {};
      heading(ip.name || "Investor Summary", 1);
      if (ip.email) muted(ip.email);
      if (ip.accreditationStatus) muted(`Accreditation: ${ip.accreditationStatus}`);
      if (ip.joinDate) muted(`Investor Since: ${ip.joinDate}`);
      hr();

      if (content.commitments && content.commitments.length > 0) {
        heading("Active Commitments", 2);
        renderTable({
          headers: ["Deal", "Type", "Committed", "Funded", "Status"],
          rows: content.commitments.map((c) => [
            c.dealName || "",
            c.dealType || "",
            `$${Number(c.commitmentAmount || 0).toLocaleString()}`,
            `$${Number(c.fundedAmount || 0).toLocaleString()}`,
            c.status || "",
          ]),
        });
      }

      if (content.distributions && content.distributions.length > 0) {
        doc.moveDown(0.5);
        heading("Distribution History", 2);
        renderTable({
          headers: ["Date", "Deal", "Amount", "Source"],
          rows: content.distributions.map((d) => [
            d.date || "",
            d.dealName || "",
            `$${Number(d.amount || 0).toLocaleString()}`,
            d.source || "",
          ]),
        });
        const totalDist = content.distributions.reduce((s, d) => s + (d.amount || 0), 0);
        doc.moveDown(0.3);
        doc.fillColor(accentColor).fontSize(fontSize).font("Helvetica-Bold")
          .text(`Total Distributions: $${totalDist.toLocaleString()}`);
      }

    } else if (templateId === "ir-deal-memo") {
      // Investment Deal Memo
      embedLogo();
      doc.y = 400;
      const ov = content.dealOverview || {};
      doc.fillColor(accentColor).fontSize(28).font("Helvetica-Bold")
        .text(ov.title || "Investment Memo", { align: "left" });
      doc.moveDown(0.3);
      if (ov.dealType) doc.fillColor(textColor).fontSize(16).font("Helvetica").text(ov.dealType);
      if (ov.date) muted(ov.date);
      muted("CONFIDENTIAL");

      doc.addPage();
      heading("Deal Overview", 1);
      if (ov.summary) body(ov.summary);
      if (ov.keyTerms) {
        doc.moveDown(0.3);
        for (const [label, val] of Object.entries(ov.keyTerms)) {
          doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
            .text(`${label}: `, { continued: true });
          doc.font("Helvetica").text(String(val));
        }
      }

      if (content.financialAnalysis) {
        doc.moveDown(0.5);
        heading("Financial Analysis", 1);
        if (typeof content.financialAnalysis === "string") {
          body(content.financialAnalysis);
        } else {
          if (content.financialAnalysis.narrative) body(content.financialAnalysis.narrative);
          if (content.financialAnalysis.table) renderTable(content.financialAnalysis.table);
        }
      }

      if (content.riskFactors) {
        doc.moveDown(0.5);
        heading("Risk Factors", 1);
        if (Array.isArray(content.riskFactors)) {
          for (const rf of content.riskFactors) {
            doc.fillColor(textColor).fontSize(fontSize).font("Helvetica-Bold")
              .text(`${rf.risk || rf.name || "Risk"}: `, { continued: true });
            doc.font("Helvetica").text(rf.mitigation || rf.description || "");
          }
        } else {
          body(String(content.riskFactors));
        }
      }

      if (content.projections) {
        doc.moveDown(0.5);
        heading("Projections", 1);
        if (typeof content.projections === "string") {
          body(content.projections);
        } else if (content.projections.table) {
          renderTable(content.projections.table);
        }
      }

      if (content.recommendation) {
        doc.moveDown(0.5);
        heading("Recommendation", 1);
        body(content.recommendation);
      }

      doc.moveDown(1);
      muted("This memo is for informational purposes only and does not constitute investment advice or an offer to sell securities.");

    } else {
      // Fallback
      heading(content.title || templateId, 1);
      body(JSON.stringify(content, null, 2));
    }

    // Table helper
    function renderTable(table) {
      if (!table?.rows?.length) return;
      const cols = table.headers || Object.keys(table.rows[0]);
      const colW = contentWidth / cols.length;
      doc.moveDown(0.3);
      // Header
      const headerY = doc.y;
      for (let c = 0; c < cols.length; c++) {
        doc.fillColor(textColor).fontSize(9).font("Helvetica-Bold")
          .text(String(cols[c]), margins.left + c * colW, headerY, { width: colW - 4 });
      }
      doc.y = headerY + 14;
      hr();
      // Rows
      for (const row of table.rows) {
        const vals = Array.isArray(row) ? row : cols.map((c) => row[c] || "");
        const rowY = doc.y;
        for (let c = 0; c < vals.length; c++) {
          doc.fillColor(textColor).fontSize(9).font("Helvetica")
            .text(String(vals[c]).substring(0, 40), margins.left + c * colW, rowY, { width: colW - 4 });
        }
        doc.y = rowY + 14;
      }
    }

    // Add footers to all pages and capture page count before ending
    addFooters();
    const finalPageCount = doc.bufferedPageRange().count;
    doc._pageCount = finalPageCount;
    doc.end();
  });
}

module.exports = { generatePdf };
