"use strict";

const admin = require("firebase-admin");

const STORAGE_BUCKET = process.env.STORAGE_BUCKET || "title-app-alpha.firebasestorage.app";

const DEFAULT_BRANDING = {
  companyName: "TitleApp AI",
  accentColor: "#7c3aed",
  headerColor: "#1a1a1a",
  textColor: "#1a1a1a",
  mutedColor: "#6b7280",
  fontFamily: "Helvetica",
  footerText: "Generated by TitleApp Digital Worker. AI-assisted analysis — human review recommended.",
  disclaimer: "This document was generated by an AI-powered Digital Worker on the TitleApp platform. All analysis is informational only and does not constitute professional advice.",
  logoBuffer: null,
  logoFormat: null,
};

async function loadBranding(tenantId) {
  if (!tenantId) return { ...DEFAULT_BRANDING };

  try {
    const db = admin.firestore();
    const snap = await db.collection("brandAssets").doc(tenantId).get();
    if (!snap.exists) return { ...DEFAULT_BRANDING };

    const data = snap.data() || {};
    const branding = {
      companyName: data.companyName || DEFAULT_BRANDING.companyName,
      accentColor: data.accentColor || data.primaryColor || DEFAULT_BRANDING.accentColor,
      headerColor: data.headerColor || DEFAULT_BRANDING.headerColor,
      textColor: data.textColor || DEFAULT_BRANDING.textColor,
      mutedColor: data.mutedColor || DEFAULT_BRANDING.mutedColor,
      fontFamily: data.fontFamily || DEFAULT_BRANDING.fontFamily,
      footerText: data.footerText || DEFAULT_BRANDING.footerText,
      disclaimer: data.disclaimer || DEFAULT_BRANDING.disclaimer,
      logoBuffer: null,
      logoFormat: null,
    };

    // Download logo from Cloud Storage if available
    if (data.logoStoragePath) {
      try {
        const bucket = admin.storage().bucket(STORAGE_BUCKET);
        const [buffer] = await bucket.file(data.logoStoragePath).download();
        branding.logoBuffer = buffer;
        branding.logoFormat = data.logoStoragePath.toLowerCase().endsWith(".png") ? "png" : "jpg";
      } catch (logoErr) {
        console.warn("Could not load branding logo:", logoErr.message);
      }
    }

    return branding;
  } catch (err) {
    console.warn("Could not load branding for tenant:", tenantId, err.message);
    return { ...DEFAULT_BRANDING };
  }
}

function applyBranding(templateStyles, branding) {
  return {
    ...templateStyles,
    accentColor: branding.accentColor || templateStyles.accentColor,
    textColor: branding.textColor || templateStyles.textColor,
    mutedColor: branding.mutedColor || templateStyles.mutedColor,
  };
}

module.exports = { DEFAULT_BRANDING, loadBranding, applyBranding };
