/**
 * healthEducation.js — Health & EMS Education suite defaults
 *
 * Layer 1 defaults applied to all HE workers.
 * Loaded by raas.engine.js before worker-specific rules.
 *
 * Two Axes: Every HE worker must define subject_domain + jurisdiction.
 * Three Deployment Tiers: Platform Default (1), Creator Public (2), Institutional Private (3).
 * Six Lanes: Build It, Learn It, Chart It, Back Me Up, Cert It, Grow It.
 */

// ═══════════════════════════════════════════════════════════════
//  LANES — Defines the six content lanes + liability + disclaimers
// ═══════════════════════════════════════════════════════════════

const HE_LANES = {
  build_it: {
    name: "Build It",
    workerRange: "HE-001 to HE-010",
    focus: "Curriculum design, accreditation, AI program architecture",
    liability: "LOW",
    disclaimerRequired: false,
    anchor: "HE-001",
    defaultDisclaimerText: null,
  },
  learn_it: {
    name: "Learn It",
    workerRange: "HE-011 to HE-018",
    focus: "Scenarios, drills, competency, exam prep",
    liability: "LOW-MED",
    disclaimerRequired: true,
    disclaimerType: "simulation",
    anchor: "HE-011",
    defaultDisclaimerText: "Scenarios generated by this worker are educational simulations only. They are not clinical protocols, standing orders, or patient care directives. Do not use simulation outputs for actual patient care decisions.",
  },
  chart_it: {
    name: "Chart It",
    workerRange: "HE-019 to HE-026",
    focus: "Documentation, handoffs, transport records, ePCR",
    liability: "MED-HIGH",
    disclaimerRequired: true,
    disclaimerType: "jurisdiction",
    anchor: "HE-019",
    defaultDisclaimerText: "This worker uses TitleApp platform-default templates. Outputs are educational reference material only. Upload your employer protocols, scope of practice rules, and jurisdiction-specific policies to activate compliant documentation.",
  },
  back_me_up: {
    name: "Back Me Up",
    workerRange: "HE-027 to HE-031",
    focus: "Real-time protocol/drug reference, scope of practice",
    liability: "HIGH",
    disclaimerRequired: true,
    disclaimerType: "clinical",
    anchor: "HE-029",
    defaultDisclaimerText: "This worker is a reference tool only. It does not provide clinical guidance, diagnosis, or treatment recommendations. It is not a substitute for clinical judgment, medical director authority, or institutional protocols. Do not use outputs for patient care decisions.",
  },
  cert_it: {
    name: "Cert It",
    workerRange: "HE-032 to HE-036",
    focus: "CEU tracking, license renewal, continuing competency",
    liability: "LOW",
    disclaimerRequired: false,
    anchor: "HE-032",
    defaultDisclaimerText: null,
  },
  grow_it: {
    name: "Grow It",
    workerRange: "HE-037 to HE-042",
    focus: "Creator onboarding, side hustle tools, marketplace analytics",
    liability: "LOW",
    disclaimerRequired: false,
    anchor: "HE-037",
    defaultDisclaimerText: null,
  },
};

// ═══════════════════════════════════════════════════════════════
//  SUBJECT DOMAINS — 10 clinical/educational specialties
// ═══════════════════════════════════════════════════════════════

const HE_SUBJECT_DOMAINS = {
  critical_care_icu: {
    label: "Critical Care / ICU",
    credential: "RN, CCRN",
    regulatoryBodies: ["AACN", "TJC", "CMS CoP"],
    defaultComplianceTags: ["AACN", "TJC", "CMS", "HIPAA", "state board"],
  },
  emergency_er: {
    label: "Emergency / ER",
    credential: "RN, CEN",
    regulatoryBodies: ["ENA", "TJC", "CMS"],
    defaultComplianceTags: ["ENA", "TJC", "CMS", "HIPAA", "state board"],
  },
  flight_nursing: {
    label: "Flight Nursing / Critical Care Transport",
    credential: "RN, CFRN, FP-C",
    regulatoryBodies: ["CAMTS", "FAA", "state board"],
    defaultComplianceTags: ["CAMTS", "FAA", "HIPAA", "state board", "medical director"],
  },
  ems_paramedic: {
    label: "EMS / Paramedic",
    credential: "NRP, NREMT-P",
    regulatoryBodies: ["NREMT", "NAEMSP", "state EMS office"],
    defaultComplianceTags: ["NREMT", "state EMS", "NEMSIS", "medical director"],
  },
  perioperative_or: {
    label: "Perioperative / OR",
    credential: "RN, CNOR",
    regulatoryBodies: ["AORN", "TJC", "CMS"],
    defaultComplianceTags: ["AORN", "TJC", "CMS", "HIPAA", "state board"],
  },
  pediatrics_nicu: {
    label: "Pediatrics / NICU",
    credential: "RN, CPN, CCRN-Neonatal",
    regulatoryBodies: ["SPN", "AAP", "TJC"],
    defaultComplianceTags: ["SPN", "AAP", "TJC", "CMS", "HIPAA", "state board"],
  },
  ob_labor_delivery: {
    label: "OB / Labor & Delivery",
    credential: "RN, RNC-OB",
    regulatoryBodies: ["AWHONN", "ACOG", "TJC"],
    defaultComplianceTags: ["AWHONN", "ACOG", "TJC", "HIPAA", "state board"],
  },
  home_health: {
    label: "Home Health",
    credential: "RN, HHA",
    regulatoryBodies: ["CMS CoP Part 484", "state licensing"],
    defaultComplianceTags: ["CMS Part 484", "state license", "HIPAA", "OASIS"],
  },
  nursing_education_faculty: {
    label: "Nursing Education Faculty",
    credential: "RN, MSN/PhD, CNE",
    regulatoryBodies: ["ACEN", "CCNE", "NLN", "state board"],
    defaultComplianceTags: ["ACEN", "CCNE", "FERPA", "state board"],
  },
  ems_instructor_academy: {
    label: "EMS Instructor / Academy",
    credential: "NRP, EMS-I",
    regulatoryBodies: ["NAEMSE", "CoAEMSP", "state EMS office"],
    defaultComplianceTags: ["NAEMSE", "CoAEMSP", "NREMT", "state EMS office"],
  },
};

// ═══════════════════════════════════════════════════════════════
//  TIER 0 EXTENSION — Applied to all HE workers
// ═══════════════════════════════════════════════════════════════

const HE_TIER_0_EXTENSION = {
  audit_trail:            "append_only",
  human_in_the_loop:      true,
  pii_handling:           "masked_in_logs",
  hipaa_phi_prohibited:   true,
  clinical_advice_blocked: true,
  disclaimer_default:     true,
  credential_self_attestation: true,
  baa_required_for_phi:   true,
};

// ═══════════════════════════════════════════════════════════════
//  ONBOARDING GATE TEXTS — Per-lane acknowledgment content
// ═══════════════════════════════════════════════════════════════

const HE_ONBOARDING_GATES = {
  simulation: {
    title: "Simulation Disclaimer",
    text: "Scenarios are educational simulations. Not clinical protocols or orders.",
    ackField: "simulationAck",
    perWorker: false,
  },
  jurisdiction: {
    title: "Jurisdiction Acknowledgment",
    text: "This worker uses TitleApp platform-default content. It is educational reference material only until you or the worker creator uploads jurisdiction-specific protocols, scope of practice rules, and employer policies. Do you understand?",
    ackField: "chartItJurisdictionAck",
    perWorker: false,
  },
  clinical: {
    title: "Clinical Reference Disclaimer",
    text: "This worker is a reference tool only. Not clinical guidance. Not a substitute for clinical judgment. Not approved for patient care decisions.",
    ackField: "backMeUpDisclaimerAck",
    perWorker: false,
  },
};

// ═══════════════════════════════════════════════════════════════
//  MD GATE WORKERS — Require medical director co-sign
// ═══════════════════════════════════════════════════════════════

const HE_MD_GATE_WORKERS = [
  "HE-013", // NREMT Scenario Simulator
  "HE-025", // EMS Patient Care Report (ePCR)
  "HE-027", // Protocol Reference Worker
  "HE-028", // Drug Reference Assistant
  "HE-030", // 3am Thinking Partner
];

module.exports = {
  HE_LANES,
  HE_SUBJECT_DOMAINS,
  HE_TIER_0_EXTENSION,
  HE_ONBOARDING_GATES,
  HE_MD_GATE_WORKERS,
};
