"use strict";

/**
 * Build Log — auto-generated CODEX for each Worker Sandbox build.
 * CODEX 47.4 Phase A (T1).
 *
 * Reads workerStepHistory[] + workerSteps + spec + Studio Locker docs and
 * emits a plain-English markdown record of the build, structured per
 * CODEX 47.4 Part 8.
 *
 * The Build Log is regenerated on every step completion and stored on
 * sandboxSessions.buildLog. Creator notes are append-only and stored on
 * sandboxSessions.buildLogNotes[].
 *
 * Append-only invariant: notes are appended, never overwritten. The
 * generated body itself is regenerated from the underlying history,
 * which is itself append-only — so the body is always a deterministic
 * projection of the event history.
 */

const admin = require("firebase-admin");
const { WORKER_STEPS, STEP_STATUS } = require("./workerBuildFlow");

function getDb() { return admin.firestore(); }
function nowServerTs() { return admin.firestore.FieldValue.serverTimestamp(); }

// ─── Section renderers ─────────────────────────────────────────────────────

function renderHeader(spec, sessionId) {
  const name = spec.name || "Untitled Worker";
  return `# Build Log — ${name}\n\n_Session ${sessionId}_\n\n` +
    `Auto-generated by Alex. This log is the audit trail for ${name} — ` +
    `every decision, every document, every rule. When you revise this worker ` +
    `or a subscriber asks how an output was produced, the answer is here.\n\n---\n\n`;
}

function renderStepHeader(stepId, label, step, order) {
  const status = step?.status || STEP_STATUS.NOT_STARTED;
  const badge = {
    [STEP_STATUS.NOT_STARTED]: "⬜ Not started",
    [STEP_STATUS.IN_PROGRESS]: "🟡 In progress",
    [STEP_STATUS.COMPLETE]:    "🟢 Complete",
  }[status];
  const completedAt = step?.completedAt ? ` — ${step.completedAt}` : "";
  return `## Step ${order} — ${label}\n\n**${badge}**${completedAt}\n\n`;
}

function renderDefine(step, spec) {
  let body = "";
  if (spec.name)            body += `- **Worker name:** ${spec.name}\n`;
  if (spec.category)        body += `- **Vertical:** ${spec.category}\n`;
  if (spec.targetAudience)  body += `- **Audience:** ${spec.targetAudience}\n`;
  if (spec.problemSolves)   body += `- **Job it performs:** ${spec.problemSolves}\n`;
  if (spec.tagline)         body += `- **One-line value:** ${spec.tagline}\n`;
  if (!body)                body = "_Define step has no captured data yet._\n";
  return body + "\n";
}

function renderDesign(step) {
  const data = step?.data || {};
  let body = "";
  if (data.uxType)            body += `- **UX type:** ${data.uxType}\n`;
  if (data.primaryColor)      body += `- **Primary color:** ${data.primaryColor}\n`;
  if (data.workerAvatar)      body += `- **Worker avatar:** ${data.workerAvatar}\n`;
  if (data.layoutDensity)     body += `- **Layout density:** ${data.layoutDensity}\n`;
  if (data.fontStyle)         body += `- **Font style:** ${data.fontStyle}\n`;
  if (Array.isArray(data.widgets) && data.widgets.length) {
    body += `- **Widgets selected:** ${data.widgets.join(", ")}\n`;
  }
  if (data.animationFlagged) {
    body += `- **Animation:** flagged for v1.1 — will apply automatically when available\n`;
  }
  if (data.rationale) body += `\n**Why this design:** ${data.rationale}\n`;
  if (!body)          body = "_Design step has no captured data yet._\n";
  return body + "\n";
}

function renderKnowledge(step, lockerDocs) {
  if (!lockerDocs || lockerDocs.length === 0) {
    return "_No documents ingested yet._\n\n";
  }

  const byTier = { 1: [], 2: [], 3: [] };
  let totalChars = 0;
  let avgConfidence = 0;
  let needsReview = 0;
  let failed = 0;

  for (const doc of lockerDocs) {
    const tier = doc.tier || 3;
    if (byTier[tier]) byTier[tier].push(doc);
    totalChars += doc.charCount || 0;
    avgConfidence += doc.confidence || 0;
    if (doc.ingestionStatus === "needs_review") needsReview++;
    if (doc.ingestionStatus === "failed") failed++;
  }
  avgConfidence = lockerDocs.length > 0 ? (avgConfidence / lockerDocs.length) : 0;

  let body = "";
  body += `- **Documents ingested:** ${lockerDocs.length}\n`;
  body += `- **Total characters extracted:** ${totalChars.toLocaleString()}\n`;
  body += `- **Average ingestion confidence:** ${(avgConfidence * 100).toFixed(0)}%\n`;
  if (needsReview > 0) body += `- **Needs review:** ${needsReview}\n`;
  if (failed > 0)      body += `- **Failed ingest:** ${failed}\n`;
  body += "\n";

  for (const tier of [1, 2, 3]) {
    const docs = byTier[tier];
    if (docs.length === 0) continue;
    const tierLabel = { 1: "Tier 1 — Platform", 2: "Tier 2 — Professional Library", 3: "Tier 3 — Worker-Specific" }[tier];
    body += `### ${tierLabel}\n\n`;
    for (const d of docs) {
      const conf = ((d.confidence || 0) * 100).toFixed(0);
      const status = d.ingestionStatus || "unknown";
      const pages = d.pageCount ? ` · ${d.pageCount} pages` : "";
      body += `- **${d.name}** (${d.sourceType})${pages} — ${status} · ${conf}% confidence\n`;
    }
    body += "\n";
  }

  return body;
}

function renderRules(step) {
  const data = step?.data || {};
  let body = "";

  const tiers = data.raasTiers || {};
  for (const tierKey of ["tier0", "tier1", "tier2", "tier3"]) {
    const rules = tiers[tierKey];
    if (!Array.isArray(rules) || rules.length === 0) continue;
    const label = {
      tier0: "Tier 0 — Style",
      tier1: "Tier 1 — Always",
      tier2: "Tier 2 — Never",
      tier3: "Tier 3 — Escalate",
    }[tierKey];
    body += `### ${label}\n\n`;
    for (const r of rules) body += `- ${r}\n`;
    body += "\n";
  }

  if (Array.isArray(data.edgeCases) && data.edgeCases.length > 0) {
    body += `### Edge cases surfaced\n\n`;
    for (const ec of data.edgeCases) body += `- ${ec}\n`;
    body += "\n";
  }

  if (data.reasoning) body += `**Reasoning behind key decisions:** ${data.reasoning}\n\n`;

  if (!body) body = "_Rules step has no captured data yet._\n\n";
  return body;
}

function renderTools(step) {
  const data = step?.data || {};
  const tools = data.connectedTools || [];
  if (tools.length === 0) return "_No tools connected yet._\n\n";

  let body = "";
  for (const t of tools) {
    if (typeof t === "string") {
      body += `- **${t}** — connected\n`;
    } else {
      body += `- **${t.name || "Unnamed tool"}** — ${t.status || "connected"}${t.enables ? ` · enables: ${t.enables}` : ""}\n`;
    }
  }
  if (Array.isArray(data.pendingTools) && data.pendingTools.length > 0) {
    body += `\n**Pending connections:**\n`;
    for (const p of data.pendingTools) body += `- ${p}\n`;
  }
  return body + "\n";
}

function renderTest(step) {
  const data = step?.data || {};
  const runs = Array.isArray(data.runs) ? data.runs : [];
  if (runs.length === 0) return "_No test runs recorded yet._\n\n";

  let body = "";
  body += `- **Test runs:** ${runs.length}\n`;
  const lastRun = runs[runs.length - 1];
  if (lastRun) {
    body += `- **Last run at:** ${lastRun.at || "unknown"}\n`;
    if (lastRun.summary) {
      body += `  - Clean: ${lastRun.summary.clean || 0}\n`;
      body += `  - Flagged: ${lastRun.summary.flagged || 0}\n`;
      body += `  - Escalated: ${lastRun.summary.escalated || 0}\n`;
    }
  }

  if (Array.isArray(data.questionsAsked) && data.questionsAsked.length > 0) {
    body += `\n### Red team questions asked\n\n`;
    for (const q of data.questionsAsked) body += `- ${q}\n`;
    body += "\n";
  }

  if (Array.isArray(data.issuesFound) && data.issuesFound.length > 0) {
    body += `### Issues found and resolved\n\n`;
    for (const i of data.issuesFound) {
      body += `- **${i.title || "Issue"}** — ${i.resolution || "resolved"}\n`;
    }
    body += "\n";
  }

  return body;
}

function renderPreflight(step) {
  const data = step?.data || {};
  if (!data.gatesPassed && !data.gates) return "_Preflight not yet complete._\n\n";
  let body = `- **Gates passed:** ${data.gatesPassed || 0}/7\n`;
  if (data.completedAt) body += `- **Completed at:** ${data.completedAt}\n`;
  return body + "\n";
}

function renderDistribute(step) {
  const data = step?.data || {};
  let body = "";
  if (data.launchedAt)     body += `- **Launched at:** ${data.launchedAt}\n`;
  if (data.shareUrl)       body += `- **Share URL:** ${data.shareUrl}\n`;
  if (data.firstShareChannel) body += `- **First share channel:** ${data.firstShareChannel}\n`;
  if (!body)               body = "_Distribution kit not yet shared._\n";
  return body + "\n";
}

function renderGrow(step) {
  const data = step?.data || {};
  let body = "";
  if (typeof data.subscribers === "number") body += `- **Subscribers:** ${data.subscribers}\n`;
  if (typeof data.earnings === "number")    body += `- **Earnings:** $${data.earnings}\n`;
  if (Array.isArray(data.revisions) && data.revisions.length) {
    body += `- **Revisions made:** ${data.revisions.length}\n`;
    for (const r of data.revisions) {
      body += `  - ${r.at || "unknown"} — ${r.summary || "revision"}\n`;
    }
  }
  if (!body) body = "_Grow & Revise has no captured data yet._\n";
  return body + "\n";
}

function renderNotes(notes) {
  if (!Array.isArray(notes) || notes.length === 0) return "";
  let body = `## Creator Notes\n\n`;
  for (const n of notes) {
    body += `- **${n.at || "unknown"}** — ${n.text}\n`;
  }
  return body + "\n";
}

// ─── Main render ───────────────────────────────────────────────────────────

function renderStep(stepId, label, step, ctx, order) {
  let body = renderStepHeader(stepId, label, step, order);
  switch (stepId) {
    case "define":     body += renderDefine(step, ctx.spec); break;
    case "design":     body += renderDesign(step); break;
    case "knowledge":  body += renderKnowledge(step, ctx.lockerDocs); break;
    case "rules":      body += renderRules(step); break;
    case "tools":      body += renderTools(step); break;
    case "test":       body += renderTest(step); break;
    case "preflight":  body += renderPreflight(step); break;
    case "distribute": body += renderDistribute(step); break;
    case "grow":       body += renderGrow(step); break;
    default:           body += "_(no renderer)_\n\n";
  }
  return body + "---\n\n";
}

/**
 * Generate the full Build Log markdown body for a session.
 * Pure function over (sessionData, lockerDocs, notes).
 */
function generateBuildLogMarkdown({ sessionId, sessionData, lockerDocs, notes }) {
  const spec = sessionData.spec || {};
  const steps = sessionData.workerSteps || {};

  let md = renderHeader(spec, sessionId);

  for (const stepDef of WORKER_STEPS) {
    md += renderStep(stepDef.id, stepDef.label, steps[stepDef.id], {
      spec,
      lockerDocs: lockerDocs || [],
    }, stepDef.order);
  }

  md += renderNotes(notes || []);
  md += `\n_Generated by Alex · TitleApp · CODEX 47.4_\n`;
  return md;
}

/**
 * Regenerate the Build Log for a session and persist it to
 * sandboxSessions/{sessionId}.buildLog. Called from the worker advance
 * handler on every step completion (non-blocking — failures logged but
 * never bubble up to the caller).
 */
async function regenerateBuildLog({ userId, sessionId }) {
  const db = getDb();
  const ref = db.collection("sandboxSessions").doc(sessionId);
  const snap = await ref.get();
  if (!snap.exists) throw new Error(`sandboxSessions/${sessionId} not found`);
  const data = snap.data();
  if (data.userId !== userId) throw new Error("Not authorized for this session");

  // Pull Studio Locker docs for this session/worker
  const workerId = sessionId; // Until a worker is published, sessionId is the workerId
  let lockerDocs = [];
  try {
    const { listDocuments } = require("./studioLocker");
    lockerDocs = await listDocuments({ userId, workerId });
  } catch (e) {
    console.warn("[buildLog] could not load Studio Locker docs:", e.message);
  }

  const md = generateBuildLogMarkdown({
    sessionId,
    sessionData: data,
    lockerDocs,
    notes: data.buildLogNotes || [],
  });

  await ref.update({
    buildLog: {
      markdown: md,
      generatedAt: nowServerTs(),
      docCount: lockerDocs.length,
    },
    updatedAt: nowServerTs(),
  });

  return { markdown: md, docCount: lockerDocs.length };
}

// ─── Route handlers ────────────────────────────────────────────────────────

/**
 * GET /v1/sandbox:worker:buildlog?sessionId=...
 */
async function handleGetBuildLog(req, res, user) {
  try {
    const sessionId = (req.query && req.query.sessionId) || (req.body && req.body.sessionId);
    if (!sessionId) return res.status(400).json({ ok: false, error: "sessionId required" });

    const db = getDb();
    const ref = db.collection("sandboxSessions").doc(sessionId);
    const snap = await ref.get();
    if (!snap.exists) return res.status(404).json({ ok: false, error: "Session not found" });
    const data = snap.data();
    if (data.userId !== user.uid) return res.status(403).json({ ok: false, error: "Forbidden" });

    // If no log yet, generate one on demand
    let buildLog = data.buildLog;
    if (!buildLog || !buildLog.markdown) {
      const result = await regenerateBuildLog({ userId: user.uid, sessionId });
      buildLog = { markdown: result.markdown, docCount: result.docCount };
    }

    return res.json({
      ok: true,
      sessionId,
      buildLog,
      notes: data.buildLogNotes || [],
    });
  } catch (e) {
    console.error("[sandbox:worker:buildlog GET] failed:", e);
    return res.status(500).json({ ok: false, error: e.message });
  }
}

/**
 * POST /v1/sandbox:worker:buildlog:note
 * Body: { sessionId, text }
 */
async function handleAppendNote(req, res, user) {
  try {
    const { sessionId, text } = req.body || {};
    if (!sessionId || !text) {
      return res.status(400).json({ ok: false, error: "sessionId and text required" });
    }

    const db = getDb();
    const ref = db.collection("sandboxSessions").doc(sessionId);
    const snap = await ref.get();
    if (!snap.exists) return res.status(404).json({ ok: false, error: "Session not found" });
    const data = snap.data();
    if (data.userId !== user.uid) return res.status(403).json({ ok: false, error: "Forbidden" });

    const note = {
      at: new Date().toISOString(),
      text: String(text).slice(0, 2000),
      by: user.uid,
    };

    // Append-only — use arrayUnion-style append by reading and writing.
    // We do not use FieldValue.arrayUnion because it deduplicates and we
    // want every note preserved even if text matches a previous note.
    const existing = Array.isArray(data.buildLogNotes) ? data.buildLogNotes.slice() : [];
    existing.push(note);

    await ref.update({
      buildLogNotes: existing,
      updatedAt: nowServerTs(),
    });

    // Regenerate so the note appears in the markdown body
    await regenerateBuildLog({ userId: user.uid, sessionId });

    return res.json({ ok: true, note });
  } catch (e) {
    console.error("[sandbox:worker:buildlog:note] failed:", e);
    return res.status(500).json({ ok: false, error: e.message });
  }
}

module.exports = {
  generateBuildLogMarkdown,
  regenerateBuildLog,
  handleGetBuildLog,
  handleAppendNote,
};
