// services/documentEngine/templates/registry.js
// System template definitions + Firestore custom template lookup

const admin = require("firebase-admin");

function getDb() { return admin.firestore(); }

const SYSTEM_TEMPLATES = {
  "report-standard": {
    id: "report-standard",
    name: "Standard Report",
    format: "pdf",
    category: "report",
    description:
      "Multi-section PDF report with cover page, table of contents, and branded headers",
    sections: ["cover", "toc", "executive_summary", "body", "appendix"],
    requiredFields: ["title"],
    optionalFields: [
      "subtitle",
      "author",
      "date",
      "sections",
      "appendix",
    ],
    system: true,
  },
  "memo-executive": {
    id: "memo-executive",
    name: "Executive Memo",
    format: "pdf",
    category: "memo",
    description:
      "One-to-two page executive memorandum with structured fields",
    sections: ["header", "body", "recommendation"],
    requiredFields: ["title", "to", "from", "body"],
    optionalFields: ["date", "subject", "recommendation", "cc"],
    system: true,
  },
  "agreement-standard": {
    id: "agreement-standard",
    name: "Standard Agreement",
    format: "docx",
    category: "agreement",
    description:
      "Editable DOCX contract with numbered clauses and signature blocks",
    sections: ["header", "recitals", "clauses", "signatures"],
    requiredFields: ["title", "parties", "clauses"],
    optionalFields: [
      "recitals",
      "effectiveDate",
      "signatures",
      "exhibits",
    ],
    system: true,
  },
  "deck-standard": {
    id: "deck-standard",
    name: "Standard Pitch Deck",
    format: "pptx",
    category: "presentation",
    description:
      "Branded slide deck with title slide, content slides, and closing",
    sections: ["title_slide", "content_slides", "closing_slide"],
    requiredFields: ["title", "slides"],
    optionalFields: ["subtitle", "presenter", "date"],
    system: true,
  },
  "model-cashflow": {
    id: "model-cashflow",
    name: "Cash Flow Model",
    format: "xlsx",
    category: "financial",
    description:
      "Multi-tab XLSX workbook with revenue, expenses, and cash flow projections",
    sections: ["assumptions", "revenue", "expenses", "cashflow", "summary"],
    requiredFields: ["title", "periods"],
    optionalFields: ["assumptions", "revenue", "expenses", "notes"],
    system: true,
  },
  "model-proforma": {
    id: "model-proforma",
    name: "Pro Forma Model",
    format: "xlsx",
    category: "financial",
    description:
      "Real estate pro forma with acquisition, operating, and disposition analysis",
    sections: ["acquisition", "operating", "disposition", "returns"],
    requiredFields: ["title", "propertyData"],
    optionalFields: ["assumptions", "comparables", "notes"],
    system: true,
  },
  "one-pager": {
    id: "one-pager",
    name: "One-Pager",
    format: "pdf",
    category: "summary",
    description:
      "Single-page branded summary with key metrics and highlights",
    sections: ["header", "metrics", "highlights", "footer"],
    requiredFields: ["title", "metrics"],
    optionalFields: [
      "subtitle",
      "highlights",
      "callToAction",
      "contactInfo",
    ],
    system: true,
  },
  "letter-formal": {
    id: "letter-formal",
    name: "Formal Letter",
    format: "docx",
    category: "correspondence",
    description:
      "Editable DOCX letter with letterhead, salutation, body, and closing",
    sections: [
      "letterhead",
      "address_block",
      "salutation",
      "body",
      "closing",
      "signature",
    ],
    requiredFields: ["to", "from", "body"],
    optionalFields: ["date", "subject", "cc", "enclosures"],
    system: true,
  },
  "draw-g702": {
    id: "draw-g702",
    name: "AIA G702 — Application for Payment",
    format: "pdf",
    category: "construction",
    description: "AIA G702 Application and Certificate for Payment with contract sum summary, retainage, and payment due",
    sections: ["header", "project_info", "contract_summary", "payment_due", "certifications"],
    requiredFields: ["title", "projectName", "applicationNumber"],
    optionalFields: ["contractorName", "ownerName", "periodFrom", "periodTo", "originalContractSum", "changeOrders", "completedToDate", "retainagePercent", "previousCertificates", "notes"],
    system: true,
  },
  "draw-g703": {
    id: "draw-g703",
    name: "AIA G703 — Continuation Sheet",
    format: "xlsx",
    category: "construction",
    description: "AIA G703 Schedule of Values continuation sheet with line-item detail for each draw period",
    sections: ["schedule_of_values"],
    requiredFields: ["title", "lineItems"],
    optionalFields: ["projectName", "applicationNumber", "periodTo", "retainagePercent"],
    system: true,
  },
  "draw-waiver-matrix": {
    id: "draw-waiver-matrix",
    name: "Lien Waiver Matrix",
    format: "xlsx",
    category: "construction",
    description: "Lien waiver tracking matrix showing conditional and unconditional waiver status for every subcontractor across all draws",
    sections: ["waiver_status"],
    requiredFields: ["title", "subcontractors"],
    optionalFields: ["projectName", "asOfDate", "drawCount"],
    system: true,
  },
  "draw-reconciliation": {
    id: "draw-reconciliation",
    name: "Draw Reconciliation Report",
    format: "xlsx",
    category: "construction",
    description: "Multi-tab reconciliation of draws vs budget with summary, division detail, cumulative tracking, and retainage",
    sections: ["summary", "by_division", "cumulative", "retainage"],
    requiredFields: ["title", "draws"],
    optionalFields: ["projectName", "loanCommitment", "interestReserve", "divisions", "retainageData"],
    system: true,
  },
  "draw-lender-checklist": {
    id: "draw-lender-checklist",
    name: "Lender Submission Checklist",
    format: "pdf",
    category: "construction",
    description: "Checklist of all required documents for lender draw submission with status tracking",
    sections: ["checklist"],
    requiredFields: ["title", "checklistItems"],
    optionalFields: ["projectName", "drawNumber", "lenderName", "submissionDate", "notes"],
    system: true,
  },

  // ── W-021 Construction Manager templates ──
  "cm-monthly-progress": {
    id: "cm-monthly-progress",
    name: "Monthly Progress Report",
    format: "pdf",
    category: "construction",
    description: "Monthly construction progress report with schedule status, budget summary, change order log, RFI summary, and risk register",
    sections: ["cover", "executive_summary", "schedule", "budget", "change_orders", "rfis", "safety", "risk_register", "look_ahead"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["reportPeriod", "percentComplete", "daysAheadBehind", "budgetSummary", "changeOrders", "rfis", "safetyStats", "risks", "lookAhead", "photos", "notes"],
    system: true,
  },
  "cm-budget-tracker": {
    id: "cm-budget-tracker",
    name: "Budget Tracking Report",
    format: "xlsx",
    category: "construction",
    description: "Multi-tab construction budget tracker with summary by division, line-item detail, change order log, contingency tracking, and cash flow",
    sections: ["summary", "detail", "change_orders", "contingency", "cashflow"],
    requiredFields: ["title", "divisions"],
    optionalFields: ["projectName", "originalContract", "approvedChanges", "changeOrders", "contingencyBudget", "contingencyUsed", "cashFlowPeriods", "notes"],
    system: true,
  },
  "cm-rfi-log": {
    id: "cm-rfi-log",
    name: "RFI Log",
    format: "xlsx",
    category: "construction",
    description: "Request for Information tracking log with aging analysis, cost and schedule impact flags",
    sections: ["rfi_log"],
    requiredFields: ["title", "rfis"],
    optionalFields: ["projectName", "asOfDate"],
    system: true,
  },
  "cm-co-log": {
    id: "cm-co-log",
    name: "Change Order Log",
    format: "xlsx",
    category: "construction",
    description: "Change order tracking log with running totals, approval status, and cumulative contract impact",
    sections: ["co_log"],
    requiredFields: ["title", "changeOrders"],
    optionalFields: ["projectName", "originalContractSum", "asOfDate"],
    system: true,
  },
  "cm-weekly-oac": {
    id: "cm-weekly-oac",
    name: "Weekly OAC Report",
    format: "pdf",
    category: "construction",
    description: "Weekly Owner-Architect-Contractor meeting report with schedule snapshot, budget status, open items, and 3-week look-ahead",
    sections: ["schedule", "budget", "open_items", "inspections", "look_ahead", "action_items"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["weekNumber", "reportDate", "percentComplete", "daysAheadBehind", "budgetSummary", "openRfis", "openCOs", "openSubmittals", "inspections", "lookAhead", "actionItems", "notes"],
    system: true,
  },
  "cm-punchlist": {
    id: "cm-punchlist",
    name: "Punchlist",
    format: "pdf",
    category: "construction",
    description: "Substantial completion punchlist organized by area with responsible subcontractor, due dates, and status tracking",
    sections: ["punchlist"],
    requiredFields: ["title", "punchlistItems"],
    optionalFields: ["projectName", "inspectionDate", "inspectedBy", "notes"],
    system: true,
  },

  // ── W-015 Construction Lending templates ──
  "cl-loan-comparison": {
    id: "cl-loan-comparison",
    name: "Loan Comparison Report",
    format: "pdf",
    category: "construction",
    description: "Side-by-side construction loan term sheet comparison with total cost of capital analysis and recommendation",
    sections: ["executive_summary", "comparison_table", "cost_analysis", "interest_reserve", "recourse", "conversion", "pros_cons"],
    requiredFields: ["title", "termSheets"],
    optionalFields: ["projectName", "projectCost", "recommendation", "notes"],
    system: true,
  },
  "cl-draw-schedule": {
    id: "cl-draw-schedule",
    name: "Draw Schedule",
    format: "xlsx",
    category: "construction",
    description: "Construction loan draw schedule with projected draws, interest model, equity contributions, and scenario analysis",
    sections: ["schedule", "interest_model", "scenarios", "summary"],
    requiredFields: ["title", "periods"],
    optionalFields: ["projectName", "loanAmount", "rate", "interestReserve", "equityContributions", "scenarios", "notes"],
    system: true,
  },
  "cl-interest-reserve": {
    id: "cl-interest-reserve",
    name: "Interest Reserve Model",
    format: "xlsx",
    category: "construction",
    description: "Interest reserve model showing monthly accrual on increasing balance with base, delay, and rate increase scenarios",
    sections: ["base_case", "delay_scenario", "rate_scenarios", "summary"],
    requiredFields: ["title", "loanAmount", "rate"],
    optionalFields: ["projectName", "interestReserve", "constructionMonths", "drawSchedule", "scenarios", "notes"],
    system: true,
  },
  "cl-utilization-dashboard": {
    id: "cl-utilization-dashboard",
    name: "Loan Utilization Dashboard",
    format: "pdf",
    category: "construction",
    description: "One-page construction loan utilization summary with commitment, drawn, reserve status, and maturity countdown",
    sections: ["summary", "utilization", "interest_reserve", "maturity", "conversion", "flags"],
    requiredFields: ["title", "loanCommitment"],
    optionalFields: ["projectName", "drawnToDate", "interestReserveBalance", "maturityDate", "constructionPercent", "conversionConditions", "flags", "notes"],
    system: true,
  },
  "cl-conversion-checklist": {
    id: "cl-conversion-checklist",
    name: "Conversion Tracking Checklist",
    format: "pdf",
    category: "construction",
    description: "Construction-to-permanent loan conversion requirements with status tracking, responsible parties, and deadlines",
    sections: ["checklist"],
    requiredFields: ["title", "conditions"],
    optionalFields: ["projectName", "lenderName", "maturityDate", "conversionDeadline", "notes"],
    system: true,
  },

  // ── W-016 Capital Stack Optimizer templates ──
  "cs-stack-summary": {
    id: "cs-stack-summary",
    name: "Capital Stack Summary",
    format: "pdf",
    category: "financial",
    description: "One-page capital stack summary with sources & uses, blended cost of capital, return metrics, and scenario comparison",
    sections: ["sources_uses", "capital_stack", "return_metrics", "scenario_comparison"],
    requiredFields: ["title", "capitalLayers"],
    optionalFields: ["dealName", "totalProjectCost", "uses", "wacc", "returnMetrics", "scenarios", "notes"],
    system: true,
  },
  "cs-full-model": {
    id: "cs-full-model",
    name: "Full Capital Stack Model",
    format: "xlsx",
    category: "financial",
    description: "10-tab capital stack workbook with assumptions, sources & uses, capital stack, pro forma, debt service, waterfall, returns, sensitivity, and scenarios",
    sections: ["assumptions", "sources_uses", "capital_stack", "pro_forma", "debt_service", "waterfall_operating", "waterfall_disposition", "return_summary", "sensitivity", "scenarios"],
    requiredFields: ["title", "capitalLayers"],
    optionalFields: ["dealName", "totalProjectCost", "uses", "proFormaAssumptions", "waterfallTerms", "sensitivityVars", "scenarios", "notes"],
    system: true,
  },
  "cs-waterfall": {
    id: "cs-waterfall",
    name: "Waterfall Distribution Model",
    format: "xlsx",
    category: "financial",
    description: "5-tab LP/GP waterfall model with operating and disposition waterfalls, LP and GP return detail, and tier comparison",
    sections: ["operating_waterfall", "disposition_waterfall", "lp_detail", "gp_detail", "comparison"],
    requiredFields: ["title", "waterfallTerms"],
    optionalFields: ["dealName", "totalEquity", "annualCashFlows", "dispositionProceeds", "holdPeriod", "notes"],
    system: true,
  },
  "cs-investor-slides": {
    id: "cs-investor-slides",
    name: "Capital Stack Investor Deck",
    format: "pptx",
    category: "financial",
    description: "5-slide investor presentation with capital stack overview, sources & uses, return metrics, sensitivity, and risk factors",
    sections: ["stack_overview", "sources_uses", "return_metrics", "sensitivity", "risk_factors"],
    requiredFields: ["title"],
    optionalFields: ["dealName", "subtitle", "capitalLayers", "uses", "returnMetrics", "sensitivityData", "riskFactors", "presenter", "date", "notes"],
    system: true,
  },
  "cs-scenario-comparison": {
    id: "cs-scenario-comparison",
    name: "Scenario Comparison Report",
    format: "pdf",
    category: "financial",
    description: "Side-by-side base, upside, and downside scenario comparison with full return metrics and sensitivity highlights",
    sections: ["scenario_summary", "metrics_comparison", "sensitivity_highlights", "recommendation"],
    requiredFields: ["title", "scenarios"],
    optionalFields: ["dealName", "capitalLayers", "proFormaAssumptions", "recommendation", "notes"],
    system: true,
  },

  // ── W-002 CRE Deal Analyst templates ──
  "da-ic-memo": {
    id: "da-ic-memo",
    name: "IC Memo Lite",
    format: "pdf",
    category: "analysis",
    description: "Investment Committee memo with deal summary, thesis, key metrics, risks, and recommendation — every numeric claim evidence-cited",
    sections: ["deal_summary", "investment_thesis", "key_metrics", "risks_and_mitigations", "recommendation"],
    requiredFields: ["title", "dealSummary"],
    optionalFields: ["dealType", "asset", "location", "askPrice", "proposedTerms", "thesis", "keyAssumptions", "metrics", "risks", "mitigations", "openQuestions", "recommendation", "nextSteps", "evidencePointers", "notes"],
    system: true,
  },
  "da-risk-summary": {
    id: "da-risk-summary",
    name: "Deal Risk Summary",
    format: "pdf",
    category: "analysis",
    description: "Risk assessment summary with overall rating, risk drivers, missing documents, gating failures, and approval conditions",
    sections: ["risk_rating", "risk_drivers", "missing_docs", "gating_failures", "approval_conditions"],
    requiredFields: ["title", "overallRiskRating"],
    optionalFields: ["dealName", "riskDrivers", "missingDocuments", "gatingFailures", "approvalConditions", "notes"],
    system: true,
  },
  "da-assumptions": {
    id: "da-assumptions",
    name: "Assumptions Register",
    format: "xlsx",
    category: "analysis",
    description: "Tabular register of all deal assumptions with source, sensitivity rating, and notes",
    sections: ["assumptions"],
    requiredFields: ["title", "assumptions"],
    optionalFields: ["dealName", "notes"],
    system: true,
  },
  "da-evidence-table": {
    id: "da-evidence-table",
    name: "Evidence Table",
    format: "xlsx",
    category: "analysis",
    description: "Claim-by-claim evidence table with value, unit, confidence, and source pointers for every numeric assertion",
    sections: ["evidence"],
    requiredFields: ["title", "claims"],
    optionalFields: ["dealName", "notes"],
    system: true,
  },

  // ── W-019 Investor Relations templates ──
  "ir-compliance-checklist": {
    id: "ir-compliance-checklist",
    name: "IR Compliance Checklist",
    format: "pdf",
    category: "compliance",
    description: "Securities compliance checklist covering Reg D, accreditation, investor limits, and required documents",
    sections: ["regulation_type", "accreditation_status", "investor_limits", "required_documents", "filing_deadlines"],
    requiredFields: ["title", "regulation"],
    optionalFields: ["dealName", "investorCount", "nonAccreditedCount", "totalRaised", "filingDeadlines", "documents", "notes"],
    system: true,
  },
  "ir-investor-summary": {
    id: "ir-investor-summary",
    name: "Investor Summary Report",
    format: "pdf",
    category: "investor-relations",
    description: "Investor roster with commitment amounts, accreditation status, capital called, distributions, and remaining commitment",
    sections: ["roster", "commitments", "capital_activity", "distributions"],
    requiredFields: ["title", "investors"],
    optionalFields: ["dealName", "totalCommitments", "totalCalled", "totalDistributed", "notes"],
    system: true,
  },
  "ir-accreditation-report": {
    id: "ir-accreditation-report",
    name: "Accreditation Report",
    format: "pdf",
    category: "compliance",
    description: "Accreditation verification report with method, status, expiration, and audit trail per investor",
    sections: ["verification_summary", "investor_detail", "expiration_tracking"],
    requiredFields: ["title", "investors"],
    optionalFields: ["dealName", "regulation", "notes"],
    system: true,
  },
  "ir-fund-overview": {
    id: "ir-fund-overview",
    name: "Fund Overview",
    format: "pdf",
    category: "investor-relations",
    description: "Fund summary with strategy, size, terms, GP commitment, management fee, and carry structure",
    sections: ["fund_summary", "strategy", "terms", "fee_structure", "gp_commitment"],
    requiredFields: ["title", "fundName"],
    optionalFields: ["strategy", "fundSize", "targetRaise", "gpCommit", "managementFee", "carry", "hurdleRate", "fundLife", "investmentPeriod", "notes"],
    system: true,
  },
  "ir-fee-analysis": {
    id: "ir-fee-analysis",
    name: "Fee & Carry Analysis",
    format: "xlsx",
    category: "investor-relations",
    description: "Multi-tab fee analysis with management fees, carry projections, GP commitment tracking, and net return impact",
    sections: ["management_fees", "carry_projection", "gp_commitment", "net_returns"],
    requiredFields: ["title", "fundSize"],
    optionalFields: ["fundName", "managementFee", "carry", "hurdleRate", "gpCommit", "fundLife", "investmentPeriod", "projectedReturns", "notes"],
    system: true,
  },
  "ir-waterfall": {
    id: "ir-waterfall",
    name: "IR Waterfall Distribution",
    format: "xlsx",
    category: "investor-relations",
    description: "Four-tier waterfall distribution model with return of capital, preferred return, GP catch-up, and carried interest",
    sections: ["return_of_capital", "preferred_return", "gp_catchup", "carried_interest", "allocations"],
    requiredFields: ["title", "totalEquity"],
    optionalFields: ["dealName", "investors", "cashFlows", "prefReturn", "catchUpSplit", "carrySplit", "dispositionProceeds", "notes"],
    system: true,
  },
  "ir-lp-terms": {
    id: "ir-lp-terms",
    name: "LP Terms Summary",
    format: "pdf",
    category: "investor-relations",
    description: "One-page LP terms summary with economics, governance, reporting, and transfer provisions",
    sections: ["economics", "governance", "reporting", "transfers", "key_provisions"],
    requiredFields: ["title"],
    optionalFields: ["fundName", "prefReturn", "carry", "hurdleRate", "gpCommit", "managementFee", "clawback", "keyPerson", "advisoryCommittee", "reportingFrequency", "transferRestrictions", "notes"],
    system: true,
  },
  "ir-deal-summary": {
    id: "ir-deal-summary",
    name: "Syndication Deal Summary",
    format: "pdf",
    category: "investor-relations",
    description: "CRE syndication deal summary with property overview, underwriting metrics, capital structure, and investment thesis",
    sections: ["property_overview", "underwriting", "capital_structure", "thesis", "risks"],
    requiredFields: ["title", "propertyName"],
    optionalFields: ["dealName", "purchasePrice", "noi", "capRate", "ltv", "dscr", "targetRaise", "holdPeriod", "targetIrr", "equityMultiple", "risks", "notes"],
    system: true,
  },
  "ir-waterfall-projection": {
    id: "ir-waterfall-projection",
    name: "Waterfall Projection",
    format: "xlsx",
    category: "investor-relations",
    description: "Year-by-year waterfall projection showing operating distributions and disposition proceeds across all tiers",
    sections: ["operating_distributions", "disposition_waterfall", "cumulative_returns"],
    requiredFields: ["title", "totalEquity"],
    optionalFields: ["dealName", "holdPeriod", "annualCashFlows", "dispositionProceeds", "prefReturn", "carrySplit", "investors", "notes"],
    system: true,
  },
  "ir-risk-assessment": {
    id: "ir-risk-assessment",
    name: "Syndication Risk Assessment",
    format: "pdf",
    category: "investor-relations",
    description: "Risk assessment for CRE syndication with market, operational, financial, and structural risk analysis",
    sections: ["market_risk", "operational_risk", "financial_risk", "structural_risk", "mitigants"],
    requiredFields: ["title"],
    optionalFields: ["dealName", "propertyName", "marketRisks", "operationalRisks", "financialRisks", "structuralRisks", "mitigants", "overallRating", "notes"],
    system: true,
  },
  "ir-offering-memo": {
    id: "ir-offering-memo",
    name: "Investor Offering Memorandum",
    format: "pdf",
    category: "investor-relations",
    description: "Investor offering memo with executive summary, property details, financial projections, risk factors, and terms",
    sections: ["executive_summary", "property_details", "market_analysis", "financial_projections", "risk_factors", "terms", "disclaimers"],
    requiredFields: ["title", "propertyName"],
    optionalFields: ["dealName", "purchasePrice", "noi", "capRate", "targetIrr", "equityMultiple", "holdPeriod", "capitalStructure", "projections", "riskFactors", "legalDisclaimers", "notes"],
    system: true,
  },
  "ir-quarterly-report": {
    id: "ir-quarterly-report",
    name: "Quarterly Investor Report",
    format: "pdf",
    category: "investor-relations",
    description: "Quarterly LP report with portfolio summary, deal updates, financial performance, distributions, and outlook",
    sections: ["cover", "portfolio_summary", "deal_updates", "financials", "distributions", "outlook"],
    requiredFields: ["title", "quarter"],
    optionalFields: ["fundName", "deals", "distributions", "performance", "outlook", "notes"],
    system: true,
  },
  "ir-capital-call": {
    id: "ir-capital-call",
    name: "Capital Call Notice",
    format: "pdf",
    category: "investor-relations",
    description: "Formal capital call notice with amount, purpose, due date, wire instructions, and investor allocation",
    sections: ["header", "call_details", "allocation", "wire_instructions", "compliance"],
    requiredFields: ["title", "callAmount"],
    optionalFields: ["fundName", "dealName", "purpose", "dueDate", "wireInstructions", "investors", "notes"],
    system: true,
  },

  // ── W-048 Chief of Staff / Alex templates ──
  "cos-pipeline-status": {
    id: "cos-pipeline-status",
    name: "Pipeline Status Report",
    format: "pdf",
    category: "operations",
    description: "Cross-worker pipeline status with active tasks, blocked items, upcoming deadlines, and worker health summary",
    sections: ["summary", "active_pipelines", "blocked_items", "deadlines", "worker_status"],
    requiredFields: ["title"],
    optionalFields: ["workspaceName", "pipelines", "blockedItems", "deadlines", "workerHealth", "notes"],
    system: true,
  },
  "cos-weekly-digest": {
    id: "cos-weekly-digest",
    name: "Weekly Workspace Digest",
    format: "pdf",
    category: "operations",
    description: "Weekly summary of all worker activity, documents generated, decisions pending, and key metrics across the workspace",
    sections: ["highlights", "worker_activity", "documents", "decisions_pending", "metrics"],
    requiredFields: ["title"],
    optionalFields: ["workspaceName", "weekOf", "highlights", "workerActivity", "documentsGenerated", "decisionsPending", "keyMetrics", "notes"],
    system: true,
  },
  "cos-task-tracker": {
    id: "cos-task-tracker",
    name: "Task Tracker",
    format: "xlsx",
    category: "operations",
    description: "Cross-worker task tracker with owner, status, priority, due date, and dependency mapping",
    sections: ["tasks", "dependencies", "summary"],
    requiredFields: ["title", "tasks"],
    optionalFields: ["workspaceName", "notes"],
    system: true,
  },
  "cos-handoff-memo": {
    id: "cos-handoff-memo",
    name: "Worker Handoff Memo",
    format: "pdf",
    category: "operations",
    description: "Structured handoff between workers with context, data passed, expected outputs, and approval status",
    sections: ["context", "source_worker", "target_worker", "data_passed", "expected_output", "approval"],
    requiredFields: ["title", "sourceWorker", "targetWorker"],
    optionalFields: ["workspaceName", "dealName", "context", "dataPassed", "expectedOutput", "approvalStatus", "notes"],
    system: true,
  },

  // ── W-022 Bid & Procurement templates ──
  "bp-bid-package": {
    id: "bp-bid-package",
    name: "Bid Package",
    format: "pdf",
    category: "construction",
    description: "Bid package prepared by CSI division with scope of work, schedule requirements, and bid instructions",
    sections: ["cover", "scope", "schedule", "bid_instructions", "requirements", "attachments"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["division", "bidDueDate", "scopeDescription", "scheduleRequirements", "insuranceRequirements", "bondRequirements"],
    system: true,
  },
  "bp-bid-matrix": {
    id: "bp-bid-matrix",
    name: "Bid Comparison Matrix",
    format: "xlsx",
    category: "construction",
    description: "Side-by-side bid comparison with base bid, alternates, exclusions, qualifications, and anomaly flags",
    sections: ["summary", "comparison", "alternates", "exclusions", "qualifications"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["division", "bidders", "baseBids", "alternates", "exclusions", "medianBid"],
    system: true,
  },
  "bp-award-memo": {
    id: "bp-award-memo",
    name: "Award Recommendation Memo",
    format: "pdf",
    category: "construction",
    description: "Subcontractor award recommendation with rationale, risk factors, and negotiation points",
    sections: ["summary", "recommendation", "bid_analysis", "risk_factors", "negotiation_points"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["division", "recommendedSub", "bidAmount", "rationale", "riskFactors", "negotiationPoints"],
    system: true,
  },
  "bp-sub-qual": {
    id: "bp-sub-qual",
    name: "Subcontractor Qualification Review",
    format: "pdf",
    category: "construction",
    description: "Subcontractor qualification review covering license, insurance, EMR, bonding capacity, and references",
    sections: ["summary", "license", "insurance", "safety", "bonding", "references"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["subName", "licenseNumber", "insuranceLimits", "emr", "bondingCapacity", "references"],
    system: true,
  },

  // ── W-025 Insurance & Risk templates ──
  "ir-insurance-matrix": {
    id: "ir-insurance-matrix",
    name: "Insurance Matrix",
    format: "xlsx",
    category: "construction",
    description: "Master insurance compliance matrix for all subcontractors with coverage status and expiration tracking",
    sections: ["summary", "matrix", "deficiencies", "expirations"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["subcontractors", "coverageTypes", "minimumLimits", "expirationDates"],
    system: true,
  },
  "ir-coi-deficiency": {
    id: "ir-coi-deficiency",
    name: "COI Deficiency Notice",
    format: "pdf",
    category: "construction",
    description: "Certificate of insurance deficiency notice identifying missing or insufficient coverage",
    sections: ["header", "deficiencies", "required_actions", "deadline"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["subName", "deficiencies", "requiredCoverage", "currentCoverage", "deadline"],
    system: true,
  },
  "ir-lender-report": {
    id: "ir-lender-report",
    name: "Lender Insurance Compliance Report",
    format: "pdf",
    category: "construction",
    description: "Insurance compliance report formatted for lender requirements with coverage verification",
    sections: ["summary", "project_coverage", "sub_compliance", "gaps", "recommendations"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["lenderName", "lenderRequirements", "complianceStatus", "gaps"],
    system: true,
  },
  "ir-risk-summary": {
    id: "ir-risk-summary",
    name: "Risk Exposure Summary",
    format: "pdf",
    category: "construction",
    description: "Risk exposure analysis covering builder's risk adequacy, umbrella coverage, and excluded perils",
    sections: ["summary", "builders_risk", "umbrella", "excluded_perils", "recommendations"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["buildersRiskAmount", "umbrellaCoverage", "excludedPerils", "exposures"],
    system: true,
  },

  // ── W-027 Quality Control & Inspection templates ──
  "qc-inspection-report": {
    id: "qc-inspection-report",
    name: "Inspection Report",
    format: "pdf",
    category: "construction",
    description: "Inspection results report with pass/fail status, conditions, deficiencies, and re-inspection requirements",
    sections: ["header", "results", "conditions", "deficiencies", "reinspection"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["inspectionType", "inspector", "date", "result", "conditions", "deficiencies", "photos"],
    system: true,
  },
  "qc-deficiency-log": {
    id: "qc-deficiency-log",
    name: "Deficiency Log",
    format: "xlsx",
    category: "construction",
    description: "Deficiency tracking log with description, location, responsible sub, severity, deadline, and status",
    sections: ["summary", "deficiencies", "by_trade", "overdue"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["deficiencies", "trades", "deadlines"],
    system: true,
  },
  "qc-trade-checklist": {
    id: "qc-trade-checklist",
    name: "Trade Quality Checklist",
    format: "pdf",
    category: "construction",
    description: "Pre-inspection quality checklist by trade for GC self-verification before formal inspection",
    sections: ["header", "checklist_items", "sign_off"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["trade", "checklistItems", "inspector", "date"],
    system: true,
  },
  "qc-co-tracker": {
    id: "qc-co-tracker",
    name: "Certificate of Occupancy Tracker",
    format: "pdf",
    category: "construction",
    description: "CO requirements tracker including inspections passed, fire alarm, elevator cert, utilities, as-builts, O&M manuals",
    sections: ["summary", "inspections", "certificates", "utilities", "documentation"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["requirements", "inspectionStatus", "certificateStatus", "targetDate"],
    system: true,
  },

  // ── W-028 Safety & OSHA templates ──
  "safety-site-plan": {
    id: "safety-site-plan",
    name: "Site Safety Plan",
    format: "pdf",
    category: "construction",
    description: "Site-specific safety plan with hazard assessment, PPE requirements, emergency procedures, and competent persons",
    sections: ["cover", "hazard_assessment", "ppe", "emergency_procedures", "hospital_routes", "competent_persons", "site_rules"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["siteAddress", "hazards", "ppeRequirements", "emergencyContacts", "hospitalRoute", "competentPersons"],
    system: true,
  },
  "safety-osha-300": {
    id: "safety-osha-300",
    name: "OSHA 300 Log",
    format: "xlsx",
    category: "construction",
    description: "OSHA Forms 300, 300A, and 301 with TRIR and DART rate calculations",
    sections: ["form_300", "form_300a", "form_301", "metrics"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["incidents", "employeeHours", "year"],
    system: true,
  },
  "safety-incident-report": {
    id: "safety-incident-report",
    name: "Incident Report",
    format: "pdf",
    category: "construction",
    description: "Structured incident or near-miss report with date, location, witnesses, root cause, and corrective actions",
    sections: ["header", "incident_details", "witnesses", "injury", "root_cause", "corrective_actions", "osha_recordability"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["date", "time", "location", "description", "witnesses", "injury", "rootCause", "correctiveActions"],
    system: true,
  },
  "safety-toolbox-talk": {
    id: "safety-toolbox-talk",
    name: "Toolbox Talk",
    format: "pdf",
    category: "construction",
    description: "Toolbox talk documentation with topic, key points, attendance, and sign-off",
    sections: ["header", "topic", "key_points", "discussion", "attendance"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["topic", "presenter", "date", "keyPoints", "attendees"],
    system: true,
  },
  "safety-jha": {
    id: "safety-jha",
    name: "Job Hazard Analysis",
    format: "pdf",
    category: "construction",
    description: "Job hazard analysis by activity with hazard identification, risk assessment, and control measures",
    sections: ["header", "activity", "hazards", "risk_assessment", "controls"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["activity", "hazards", "probability", "severity", "controls"],
    system: true,
  },

  // ── W-029 MEP Coordination templates ──
  "mep-clash-log": {
    id: "mep-clash-log",
    name: "Clash Detection Log",
    format: "xlsx",
    category: "construction",
    description: "BIM/field clash detection log with location, systems involved, severity, responsible trade, and resolution status",
    sections: ["summary", "clashes", "by_system", "resolution_status"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["clashes", "systems", "severityLevels"],
    system: true,
  },
  "mep-meeting-minutes": {
    id: "mep-meeting-minutes",
    name: "MEP Coordination Meeting Minutes",
    format: "pdf",
    category: "construction",
    description: "MEP coordination meeting minutes with agenda, attendees, action items, and follow-up tracking",
    sections: ["header", "agenda", "attendees", "discussion", "action_items", "follow_up"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["meetingDate", "attendees", "agendaItems", "actionItems"],
    system: true,
  },
  "mep-cx-checklist": {
    id: "mep-cx-checklist",
    name: "Commissioning Checklist",
    format: "pdf",
    category: "construction",
    description: "MEP commissioning checklist covering functional performance testing, TAB, controls verification, and documentation",
    sections: ["summary", "performance_testing", "tab", "controls", "documentation"],
    requiredFields: ["title", "projectName"],
    optionalFields: ["systems", "testResults", "tabData", "controlsStatus"],
    system: true,
  },

  // ── W-024 Labor & Staffing templates ──
  "ls-certified-payroll": {
    id: "ls-certified-payroll",
    name: "Certified Payroll (WH-347)",
    format: "xlsx",
    category: "construction",
    description: "WH-347 certified payroll report with worker classifications, prevailing wage rates, fringe benefits, and weekly hours",
    sections: ["payroll_header", "worker_detail", "fringe_benefits", "certification"],
    requiredFields: ["title", "workers"],
    optionalFields: ["projectName", "weekEnding", "contractorName", "wageDecisionNumber", "fringeBenefits", "notes"],
    system: true,
  },
  "ls-workforce-report": {
    id: "ls-workforce-report",
    name: "Workforce Report",
    format: "pdf",
    category: "construction",
    description: "Daily/weekly workforce summary with headcount by trade, hours, employer, and certification status",
    sections: ["summary", "by_trade", "by_employer", "certification_status", "overtime"],
    requiredFields: ["title", "reportDate"],
    optionalFields: ["projectName", "totalHeadcount", "tradeBreakdown", "employerBreakdown", "certificationAlerts", "overtimeHours", "notes"],
    system: true,
  },
  "ls-diversity-report": {
    id: "ls-diversity-report",
    name: "Diversity Report",
    format: "pdf",
    category: "construction",
    description: "MBE/WBE/DBE/Section 3 workforce participation report with goals vs actuals and trend analysis",
    sections: ["goals", "actuals", "gap_analysis", "trend", "recommendations"],
    requiredFields: ["title", "diversityGoals"],
    optionalFields: ["projectName", "reportPeriod", "participationActuals", "trendData", "recommendations", "notes"],
    system: true,
  },
  "ls-certification-tracker": {
    id: "ls-certification-tracker",
    name: "Certification Tracker",
    format: "xlsx",
    category: "construction",
    description: "All worker certifications with type, issue date, expiration date, and renewal status alerts",
    sections: ["certifications"],
    requiredFields: ["title", "certifications"],
    optionalFields: ["projectName", "asOfDate", "expiringWithin30", "expiringWithin60", "notes"],
    system: true,
  },

  // ── W-026 Materials & Supply Chain templates ──
  "msc-procurement-schedule": {
    id: "msc-procurement-schedule",
    name: "Procurement Schedule",
    format: "xlsx",
    category: "construction",
    description: "All materials with order date, lead time, delivery date, installation date, and long-lead flag",
    sections: ["schedule", "long_lead_items", "summary"],
    requiredFields: ["title", "materials"],
    optionalFields: ["projectName", "scheduleStart", "scheduleEnd", "longLeadThreshold", "notes"],
    system: true,
  },
  "msc-long-lead-tracker": {
    id: "msc-long-lead-tracker",
    name: "Long-Lead Item Tracker",
    format: "xlsx",
    category: "construction",
    description: "Long-lead items with vendor, lead time, order status, risk assessment, and schedule impact",
    sections: ["items", "risk_assessment", "schedule_impact"],
    requiredFields: ["title", "items"],
    optionalFields: ["projectName", "asOfDate", "criticalItems", "riskAssessment", "notes"],
    system: true,
  },
  "msc-stored-materials-package": {
    id: "msc-stored-materials-package",
    name: "Stored Materials Package",
    format: "pdf",
    category: "construction",
    description: "Draw-ready documentation for stored materials with paid invoices, delivery receipts, photos, and insurance certificates",
    sections: ["summary", "invoices", "delivery_receipts", "photos", "insurance", "storage_verification"],
    requiredFields: ["title", "materials"],
    optionalFields: ["projectName", "drawNumber", "storageLocation", "insuranceCertificate", "totalValue", "notes"],
    system: true,
  },
  "msc-price-escalation-report": {
    id: "msc-price-escalation-report",
    name: "Price Escalation Report",
    format: "pdf",
    category: "construction",
    description: "Budget vs actual material costs with escalation analysis, tariff impact, and projected total budget impact",
    sections: ["summary", "by_material", "tariff_impact", "projections", "recommendations"],
    requiredFields: ["title", "materials"],
    optionalFields: ["projectName", "reportDate", "budgetTotal", "actualTotal", "tariffImpact", "projections", "notes"],
    system: true,
  },

  // ── W-014 Mezzanine & Preferred Equity templates ──
  "mpe-structure-comparison": {
    id: "mpe-structure-comparison",
    name: "Structure Comparison",
    format: "pdf",
    category: "financial",
    description: "Mezzanine debt vs preferred equity vs JV equity side-by-side comparison with cost, control, tax, and foreclosure analysis",
    sections: ["executive_summary", "comparison_table", "cost_of_capital", "control_rights", "tax_treatment", "foreclosure_remedies", "recommendation"],
    requiredFields: ["title", "structures"],
    optionalFields: ["dealName", "gapAmount", "seniorDebtTerms", "projectReturns", "recommendation", "notes"],
    system: true,
  },
  "mpe-waterfall-model": {
    id: "mpe-waterfall-model",
    name: "Mezz/Pref Equity Waterfall Model",
    format: "xlsx",
    category: "financial",
    description: "Multi-tier waterfall with preferred returns, return of capital, promote splits, catch-up provisions, and IRR hurdles",
    sections: ["assumptions", "preferred_return", "return_of_capital", "promote_tiers", "irr_sensitivity", "summary"],
    requiredFields: ["title", "waterfallTerms"],
    optionalFields: ["dealName", "totalEquity", "prefReturn", "promoteTiers", "holdPeriod", "cashFlows", "dispositionProceeds", "notes"],
    system: true,
  },
  "mpe-term-sheet-analysis": {
    id: "mpe-term-sheet-analysis",
    name: "Mezz/Pref Equity Term Sheet Analysis",
    format: "pdf",
    category: "financial",
    description: "Parsed term sheet with key terms highlighted — rate, term, prepayment, conversion, governance, and guaranty",
    sections: ["summary", "key_terms", "rate_analysis", "governance_rights", "guaranty_requirements", "risks", "recommendation"],
    requiredFields: ["title", "termSheetData"],
    optionalFields: ["dealName", "lenderName", "currentRate", "accrualRate", "term", "prepayment", "conversionRights", "governanceRights", "notes"],
    system: true,
  },
  "mpe-investor-report": {
    id: "mpe-investor-report",
    name: "Mezz/Pref Equity Investor Report",
    format: "pdf",
    category: "financial",
    description: "Periodic report for mezz/pref equity investors with distributions, accrued returns, covenant compliance, and project status",
    sections: ["distributions", "accrued_returns", "covenant_compliance", "project_status", "outlook"],
    requiredFields: ["title", "reportPeriod"],
    optionalFields: ["dealName", "investorName", "currentPayDistributions", "accruedBalance", "covenants", "projectUpdate", "notes"],
    system: true,
  },

  // ── W-018 Crowdfunding & Reg D templates ──
  "crd-exemption-analysis": {
    id: "crd-exemption-analysis",
    name: "Exemption Analysis",
    format: "pdf",
    category: "financial",
    description: "Securities exemption comparison and recommendation — 506(b) vs 506(c) vs Reg CF vs Reg A with cost, timeline, and restrictions",
    sections: ["summary", "exemption_comparison", "cost_analysis", "timeline", "restrictions", "recommendation"],
    requiredFields: ["title", "raiseAmount"],
    optionalFields: ["dealName", "investorTypes", "marketingPlans", "recommendation", "notes"],
    system: true,
  },
  "crd-investor-tracker": {
    id: "crd-investor-tracker",
    name: "Investor Tracker",
    format: "xlsx",
    category: "financial",
    description: "All investors with accredited status, verification method, subscription amount, investment limits, and document status",
    sections: ["investors", "verification_status", "subscription_status", "limits"],
    requiredFields: ["title", "investors"],
    optionalFields: ["dealName", "exemptionType", "totalRaised", "targetRaise", "notes"],
    system: true,
  },
  "crd-compliance-calendar": {
    id: "crd-compliance-calendar",
    name: "Compliance Calendar",
    format: "xlsx",
    category: "financial",
    description: "All filing deadlines by exemption type — Form D, Blue Sky, Form C, ongoing reporting with status tracking",
    sections: ["filings", "deadlines", "status"],
    requiredFields: ["title", "exemptionType"],
    optionalFields: ["dealName", "firstSaleDate", "stateFilings", "ongoingReporting", "notes"],
    system: true,
  },
  "crd-cap-table": {
    id: "crd-cap-table",
    name: "Cap Table",
    format: "xlsx",
    category: "financial",
    description: "Investor cap table with ownership percentage, investment amount, preferred return status, and distribution tracking",
    sections: ["ownership", "investments", "distributions", "summary"],
    requiredFields: ["title", "investors"],
    optionalFields: ["dealName", "totalEquity", "preferredReturn", "distributions", "notes"],
    system: true,
  },

  // ── W-003 Site Due Diligence templates ──
  "sdd-checklist": {
    id: "sdd-checklist",
    name: "Due Diligence Checklist",
    format: "xlsx",
    category: "real-estate",
    description: "Comprehensive DD checklist with all required studies, reports, and approvals — organized by category with status tracking",
    sections: ["environmental", "survey", "zoning", "utilities", "geotechnical", "title", "other"],
    requiredFields: ["title", "projectType"],
    optionalFields: ["projectName", "location", "ddPeriodDays", "startDate", "notes"],
    system: true,
  },
  "sdd-summary": {
    id: "sdd-summary",
    name: "Due Diligence Summary",
    format: "pdf",
    category: "real-estate",
    description: "Go/no-go summary with all findings, risk items, cost implications, and timeline impacts",
    sections: ["executive_summary", "environmental", "survey", "zoning", "utilities", "risks", "cost_impacts", "recommendation"],
    requiredFields: ["title", "findings"],
    optionalFields: ["projectName", "location", "environmentalFindings", "surveyFindings", "zoningStatus", "utilityStatus", "risks", "costImpacts", "recommendation", "notes"],
    system: true,
  },
  "sdd-environmental-memo": {
    id: "sdd-environmental-memo",
    name: "Environmental Findings Memo",
    format: "pdf",
    category: "real-estate",
    description: "Phase I ESA findings analysis — RECs, CRECs, HRECs, de minimis conditions, and Phase II recommendations",
    sections: ["summary", "recs", "crecs", "hrecs", "de_minimis", "recommendations"],
    requiredFields: ["title", "environmentalFindings"],
    optionalFields: ["projectName", "siteAddress", "assessorName", "assessmentDate", "recommendations", "notes"],
    system: true,
  },
  "sdd-survey-review": {
    id: "sdd-survey-review",
    name: "Survey Review Memo",
    format: "pdf",
    category: "real-estate",
    description: "ALTA survey analysis with easements, encroachments, setback issues, and title cross-reference",
    sections: ["summary", "easements", "encroachments", "setbacks", "utilities", "flood_zone", "title_cross_reference"],
    requiredFields: ["title", "surveyFindings"],
    optionalFields: ["projectName", "surveyDate", "surveyorName", "tableAItems", "titleExceptions", "notes"],
    system: true,
  },

  // ── W-004 Land Use & Entitlement templates ──
  "lue-zoning-analysis": {
    id: "lue-zoning-analysis",
    name: "Zoning Analysis",
    format: "pdf",
    category: "real-estate",
    description: "Current zoning vs proposed use gap analysis with required approvals, variance needs, and timeline estimate",
    sections: ["current_zoning", "proposed_use", "gap_analysis", "required_approvals", "timeline"],
    requiredFields: ["title", "currentZoning"],
    optionalFields: ["projectName", "location", "proposedUse", "density", "height", "setbacks", "parking", "requiredApprovals", "timelineEstimate", "notes"],
    system: true,
  },
  "lue-application-narrative": {
    id: "lue-application-narrative",
    name: "Application Narrative",
    format: "pdf",
    category: "real-estate",
    description: "Hearing-ready project narrative with compliance analysis, community benefits, and response to anticipated objections",
    sections: ["project_description", "compliance_analysis", "community_benefits", "objection_responses", "visual_summary"],
    requiredFields: ["title", "projectDescription"],
    optionalFields: ["projectName", "applicantName", "hearingDate", "complianceAnalysis", "communityBenefits", "anticipatedObjections", "notes"],
    system: true,
  },
  "lue-condition-tracker": {
    id: "lue-condition-tracker",
    name: "Condition Tracker",
    format: "xlsx",
    category: "real-estate",
    description: "All conditions of approval with classification, responsible party, deadline, and compliance status",
    sections: ["conditions"],
    requiredFields: ["title", "conditions"],
    optionalFields: ["projectName", "approvalDate", "approvingBody", "notes"],
    system: true,
  },
  "lue-timeline": {
    id: "lue-timeline",
    name: "Entitlement Timeline",
    format: "pdf",
    category: "real-estate",
    description: "Visual entitlement timeline with milestones, hearing dates, appeal periods, and critical path",
    sections: ["milestones", "hearings", "appeal_periods", "critical_path"],
    requiredFields: ["title", "milestones"],
    optionalFields: ["projectName", "startDate", "targetCompletionDate", "hearingDates", "appealPeriods", "notes"],
    system: true,
  },

  // ── W-012 Permit Submission & Tracking templates ──
  "pst-permit-checklist": {
    id: "pst-permit-checklist",
    name: "Permit Checklist",
    format: "xlsx",
    category: "construction",
    description: "All required permits by type with application requirements, fees, review timeline, and status tracking",
    sections: ["permits"],
    requiredFields: ["title", "permits"],
    optionalFields: ["projectName", "jurisdiction", "totalFees", "notes"],
    system: true,
  },
  "pst-plan-check-log": {
    id: "pst-plan-check-log",
    name: "Plan Check Log",
    format: "xlsx",
    category: "construction",
    description: "Plan check comments by discipline with responsible party, response status, and resubmission tracking",
    sections: ["comments", "responses", "resubmissions"],
    requiredFields: ["title", "comments"],
    optionalFields: ["projectName", "permitType", "planCheckRound", "responsibleParties", "notes"],
    system: true,
  },
  "pst-fee-summary": {
    id: "pst-fee-summary",
    name: "Permit Fee Summary",
    format: "pdf",
    category: "construction",
    description: "All permit and impact fees with calculation basis, amount, payment status, and total cost impact",
    sections: ["plan_check_fees", "permit_fees", "impact_fees", "utility_fees", "total"],
    requiredFields: ["title", "fees"],
    optionalFields: ["projectName", "jurisdiction", "constructionValue", "totalFees", "notes"],
    system: true,
  },
  "pst-timeline": {
    id: "pst-timeline",
    name: "Permitting Timeline",
    format: "pdf",
    category: "construction",
    description: "Permitting timeline with submission dates, review periods, correction rounds, and projected issuance dates",
    sections: ["timeline", "milestones", "critical_path"],
    requiredFields: ["title", "permits"],
    optionalFields: ["projectName", "jurisdiction", "startDate", "targetIssuance", "notes"],
    system: true,
  },

  // ── W-031 Lease-Up & Marketing templates ──
  "lm-marketing-plan": {
    id: "lm-marketing-plan",
    name: "Marketing Plan",
    format: "pdf",
    category: "real-estate",
    description: "Lease-up marketing strategy with target demographics, channels, budget allocation, and timeline",
    sections: ["target_market", "messaging", "channels", "budget", "timeline", "kpis"],
    requiredFields: ["title", "propertyType"],
    optionalFields: ["projectName", "location", "unitCount", "targetRent", "competitiveSet", "marketingBudget", "notes"],
    system: true,
  },
  "lm-leasing-report": {
    id: "lm-leasing-report",
    name: "Leasing Report",
    format: "pdf",
    category: "real-estate",
    description: "Weekly/monthly leasing velocity report with units leased, conversion rates, concessions, and projected stabilization",
    sections: ["summary", "leasing_activity", "conversion_rates", "concessions", "projections"],
    requiredFields: ["title", "reportPeriod"],
    optionalFields: ["projectName", "totalUnits", "leasedUnits", "leads", "tours", "applications", "leasesSigned", "concessions", "stabilizationDate", "notes"],
    system: true,
  },
  "lm-absorption-forecast": {
    id: "lm-absorption-forecast",
    name: "Absorption Forecast",
    format: "xlsx",
    category: "real-estate",
    description: "Scenario-based lease-up projections with optimistic, base, and pessimistic absorption rates and stabilization dates",
    sections: ["assumptions", "optimistic", "base", "pessimistic", "comparison"],
    requiredFields: ["title", "totalUnits"],
    optionalFields: ["projectName", "currentOccupancy", "monthlyAbsorption", "targetStabilization", "scenarios", "notes"],
    system: true,
  },
  "lm-market-survey": {
    id: "lm-market-survey",
    name: "Market Survey",
    format: "xlsx",
    category: "real-estate",
    description: "Competitive property comparison with rents, concessions, occupancy, amenities, and positioning analysis",
    sections: ["comparables", "rent_comparison", "concession_analysis", "amenity_comparison", "positioning"],
    requiredFields: ["title", "comparables"],
    optionalFields: ["projectName", "location", "subjectRents", "notes"],
    system: true,
  },

  // ── W-033 Property Management templates ──
  "pm-operational-report": {
    id: "pm-operational-report",
    name: "Operational Report",
    format: "pdf",
    category: "real-estate",
    description: "Monthly property management report with occupancy, collections, delinquency, work orders, vendor spend, and incidents",
    sections: ["occupancy", "collections", "delinquency", "work_orders", "vendor_spend", "capital_improvements", "incidents"],
    requiredFields: ["title", "reportMonth"],
    optionalFields: ["propertyName", "totalUnits", "occupancyRate", "collectionsRate", "delinquencyAmount", "openWorkOrders", "vendorSpend", "incidents", "notes"],
    system: true,
  },
  "pm-inspection-report": {
    id: "pm-inspection-report",
    name: "Inspection Report",
    format: "pdf",
    category: "real-estate",
    description: "Property inspection findings with deficiencies, photos, corrective actions, and completion tracking",
    sections: ["summary", "unit_inspections", "common_areas", "building_systems", "grounds", "action_items"],
    requiredFields: ["title", "inspectionDate"],
    optionalFields: ["propertyName", "inspectedBy", "deficiencies", "photos", "actionItems", "notes"],
    system: true,
  },
  "pm-move-in-out-checklist": {
    id: "pm-move-in-out-checklist",
    name: "Move-In/Move-Out Checklist",
    format: "pdf",
    category: "real-estate",
    description: "Standardized move-in/move-out documentation with condition assessment, photo documentation, and deposit disposition",
    sections: ["unit_condition", "utilities", "keys_access", "deposit_disposition"],
    requiredFields: ["title", "unitNumber"],
    optionalFields: ["propertyName", "tenantName", "moveType", "inspectionDate", "condition", "depositAmount", "deductions", "notes"],
    system: true,
  },
  "pm-lease-renewal-tracker": {
    id: "pm-lease-renewal-tracker",
    name: "Lease Renewal Tracker",
    format: "xlsx",
    category: "real-estate",
    description: "All leases with expiration date, current rent, market rent, renewal status, and negotiation pipeline",
    sections: ["renewals", "rent_comparison", "pipeline"],
    requiredFields: ["title", "leases"],
    optionalFields: ["propertyName", "asOfDate", "avgRentIncrease", "renewalRate", "notes"],
    system: true,
  },

  // ── W-039 Accounting templates ──
  "acct-financial-statements": {
    id: "acct-financial-statements",
    name: "Financial Statements",
    format: "pdf",
    category: "financial",
    description: "GAAP-compliant income statement, balance sheet, and cash flow statement with notes — by property and consolidated",
    sections: ["income_statement", "balance_sheet", "cash_flow", "notes"],
    requiredFields: ["title", "period"],
    optionalFields: ["entityName", "propertyName", "revenueDetail", "expenseDetail", "assets", "liabilities", "cashFlows", "notes"],
    system: true,
  },
  "acct-budget-variance": {
    id: "acct-budget-variance",
    name: "Budget vs Actual Variance",
    format: "xlsx",
    category: "financial",
    description: "Budget vs actual variance analysis by account with dollar and percentage variance, YTD comparison, and trend",
    sections: ["summary", "revenue_variance", "expense_variance", "ytd_comparison", "trend"],
    requiredFields: ["title", "period"],
    optionalFields: ["entityName", "propertyName", "budgetData", "actualData", "notes"],
    system: true,
  },
  "acct-job-cost-report": {
    id: "acct-job-cost-report",
    name: "Job Cost Report",
    format: "xlsx",
    category: "financial",
    description: "Construction cost tracking by CSI division with committed, actual, budget remaining, and projected final cost",
    sections: ["summary", "by_division", "committed_vs_actual", "projections"],
    requiredFields: ["title", "divisions"],
    optionalFields: ["projectName", "originalBudget", "approvedChanges", "committedCosts", "actualCosts", "projectedFinal", "notes"],
    system: true,
  },
  "acct-investor-package": {
    id: "acct-investor-package",
    name: "Investor Financial Package",
    format: "pdf",
    category: "financial",
    description: "Investor financial package with property financials, waterfall calculations, distribution summary, and capital account statements",
    sections: ["cover", "financials", "waterfall", "distributions", "capital_accounts"],
    requiredFields: ["title", "period"],
    optionalFields: ["fundName", "dealName", "financials", "waterfallData", "distributions", "capitalAccounts", "notes"],
    system: true,
  },
};

async function getTemplate(templateId, tenantId) {
  if (SYSTEM_TEMPLATES[templateId]) {
    return SYSTEM_TEMPLATES[templateId];
  }

  if (tenantId) {
    try {
      const snap = await getDb()
        .collection("documentTemplates")
        .doc(templateId)
        .get();
      if (snap.exists) {
        const tmpl = snap.data();
        if (tmpl.tenantId === tenantId || tmpl.system === true) {
          return { id: snap.id, ...tmpl };
        }
      }
    } catch (e) {
      console.warn("registry: failed to load custom template", templateId, e.message);
    }
  }

  return null;
}

async function listTemplates(tenantId) {
  const templates = Object.values(SYSTEM_TEMPLATES);

  if (tenantId) {
    try {
      const snap = await getDb()
        .collection("documentTemplates")
        .where("tenantId", "==", tenantId)
        .get();
      snap.forEach((doc) => {
        templates.push({ id: doc.id, ...doc.data() });
      });
    } catch (e) {
      console.warn("registry: failed to load custom templates", e.message);
    }
  }

  return templates;
}

function validateInput(template, data) {
  const missing = [];
  for (const field of template.requiredFields || []) {
    if (data[field] === undefined || data[field] === null || data[field] === "") {
      missing.push(field);
    }
  }
  if (missing.length > 0) {
    return { valid: false, missing };
  }
  return { valid: true };
}

module.exports = { getTemplate, listTemplates, validateInput, SYSTEM_TEMPLATES };
