"use strict";

/**
 * Connector Registry — single source of truth for all available data connections.
 *
 * Every connector declares its vertical whitelist, cost estimate, tier requirement,
 * plain-language description, and underlying service name for the health monitor.
 *
 * Creators never see API keys, endpoints, or rate limits. Alex asks one question
 * per connector. Creator says yes or no. The worker is connected.
 *
 * requiresRaas: true means the connector is blocked unless the worker has raasStatus: "compliant".
 * This applies to all 6 aviation safety connectors.
 */

const CONNECTORS = {
  // ── AVIATION (6 safety connectors — all requiresRaas) ──
  aviationweather: {
    id: "aviationweather",
    label: "Live Weather",
    description: "Pulls live METARs, TAFs, winds aloft, and SIGMETs automatically when a pilot starts a session.",
    verticals: ["aviation"],
    costPerSession: 0.00,
    costLabel: "Free — FAA public data",
    tierRequired: "free",
    requiresRaas: true,
    serviceName: "aviationweather",
    envKey: null,
  },
  notamify: {
    id: "notamify",
    label: "NOTAM Briefings",
    description: "Fetches and summarizes current NOTAMs for departure, destination, and alternate airports.",
    verticals: ["aviation"],
    costPerSession: 0.60,
    costLabel: "~$0.60 per session (3 airports × $0.30)",
    tierRequired: "paid",
    requiresRaas: true,
    creditCost: 30,
    serviceName: "notamify",
    envKey: "NOTAMIFY_API_KEY",
  },
  adsb_exchange: {
    id: "adsb_exchange",
    label: "Live Fleet Tracking",
    description: "Shows real-time aircraft positions for dispatch and fleet monitoring.",
    verticals: ["aviation"],
    costPerSession: 0.002,
    costLabel: "~$0.002 per query — negligible",
    tierRequired: "paid",
    requiresRaas: true,
    creditCost: 1,
    serviceName: "adsb_exchange",
    envKey: "ADSB_EXCHANGE_API_KEY",
  },
  faa_charts: {
    id: "faa_charts",
    label: "FAA Charts & Plates",
    description: "Provides access to current sectional charts, approach plates, and airport diagrams.",
    verticals: ["aviation"],
    costPerSession: 0.00,
    costLabel: "Free — FAA public data",
    tierRequired: "free",
    requiresRaas: true,
    serviceName: "faa_charts",
    envKey: null,
  },
  faa_nasr: {
    id: "faa_nasr",
    label: "Airport & Airspace Data",
    description: "Provides runway lengths, frequencies, procedures, and airspace boundaries from the FAA national database.",
    verticals: ["aviation"],
    costPerSession: 0.00,
    costLabel: "Free — FAA public data",
    tierRequired: "free",
    requiresRaas: true,
    serviceName: "faa_nasr",
    envKey: null,
  },
  tfr_feed: {
    id: "tfr_feed",
    label: "TFR Alerts",
    description: "Pulls active Temporary Flight Restrictions from the FAA and alerts on route conflicts.",
    verticals: ["aviation"],
    costPerSession: 0.00,
    costLabel: "Free — FAA public data",
    tierRequired: "free",
    requiresRaas: true,
    serviceName: "tfr_feed",
    envKey: null,
  },

  // ── GOOGLE PLATFORM (cross-vertical) ──
  google_maps: {
    id: "google_maps",
    label: "Maps & Location",
    description: "Renders property locations, parcel boundaries, and market overlays on the Canvas map.",
    verticals: ["real_estate_development", "solar_vpp", "government", "aviation", "auto_dealer", "health_ems"],
    costPerSession: 0.014,
    costLabel: "~$0.014 per map load",
    tierRequired: "paid",
    requiresRaas: false,
    creditCost: 1,
    serviceName: "google_maps",
    envKey: "GOOGLE_MAPS_API_KEY",
  },
  google_geocoding: {
    id: "google_geocoding",
    label: "Address Geocoding",
    description: "Converts addresses to coordinates and validates address accuracy.",
    verticals: ["real_estate_development", "solar_vpp", "government", "auto_dealer"],
    costPerSession: 0.005,
    costLabel: "~$0.005 per geocode",
    tierRequired: "paid",
    requiresRaas: false,
    creditCost: 1,
    serviceName: "google_geocoding",
    envKey: "GOOGLE_MAPS_API_KEY",
  },
  google_timezone: {
    id: "google_timezone",
    label: "Time Zone",
    description: "Determines local time zone for any location — used for scheduling and duty time calculations.",
    verticals: ["aviation", "real_estate_development"],
    costPerSession: 0.005,
    costLabel: "~$0.005 per lookup",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "google_timezone",
    envKey: "GOOGLE_MAPS_API_KEY",
  },
  google_solar: {
    id: "google_solar",
    label: "Solar Roof Analysis",
    description: "Analyzes roof orientation, panel capacity, and annual energy output from a property address.",
    verticals: ["solar_vpp"],
    costPerSession: 0.02,
    costLabel: "~$0.02 per roof analysis",
    tierRequired: "paid",
    requiresRaas: false,
    creditCost: 2,
    serviceName: "google_solar",
    envKey: "GOOGLE_MAPS_API_KEY",
  },
  google_weather: {
    id: "google_weather",
    label: "Weather Data",
    description: "Provides current conditions and forecasts for job site planning and scheduling.",
    verticals: ["solar_vpp", "real_estate_development"],
    costPerSession: 0.005,
    costLabel: "~$0.005 per lookup",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "google_weather",
    envKey: "GOOGLE_MAPS_API_KEY",
  },

  // ── REAL ESTATE ──
  realie: {
    id: "realie",
    label: "Property Records",
    description: "Pulls address, ownership, tax assessment, and valuation data from a single address input.",
    verticals: ["real_estate_development", "solar_vpp", "government", "mortgage"],
    costPerSession: 0.10,
    costLabel: "~$0.10 per property lookup",
    tierRequired: "paid",
    requiresRaas: false,
    creditCost: 10,
    serviceName: "realie",
    envKey: "REALIE_API_KEY",
  },
  rentcast: {
    id: "rentcast",
    label: "Rental Market Data",
    description: "Provides live rent estimates, rental comps, and occupancy rates by zip code.",
    verticals: ["real_estate_development"],
    costPerSession: 0.06,
    costLabel: "~$0.06 per market lookup",
    tierRequired: "paid",
    requiresRaas: false,
    creditCost: 6,
    serviceName: "rentcast",
    envKey: "RENTCAST_PROPERTY_DATA",
  },

  // ── FREE PUBLIC DATA (cross-vertical) ──
  fema_flood: {
    id: "fema_flood",
    label: "FEMA Flood Zones",
    description: "Shows flood zone designation and risk level for any parcel.",
    verticals: ["real_estate_development", "solar_vpp", "government"],
    costPerSession: 0.00,
    costLabel: "Free — FEMA public data",
    tierRequired: "free",
    requiresRaas: false,
    serviceName: "fema_flood",
    envKey: null,
  },
  us_census: {
    id: "us_census",
    label: "Census Demographics",
    description: "Provides median income, population trends, and employment data by zip code.",
    verticals: ["real_estate_development", "solar_vpp", "government"],
    costPerSession: 0.00,
    costLabel: "Free — Census public data",
    tierRequired: "free",
    requiresRaas: false,
    serviceName: "us_census",
    envKey: null,
  },
  hud_fmr: {
    id: "hud_fmr",
    label: "HUD Fair Market Rents",
    description: "Provides HUD fair market rent benchmarks by MSA for rental analysis.",
    verticals: ["real_estate_development"],
    costPerSession: 0.00,
    costLabel: "Free — HUD public data",
    tierRequired: "free",
    requiresRaas: false,
    serviceName: "hud_fmr",
    envKey: null,
  },

  // ── HEALTHCARE / EMS ──
  provider_lookup: {
    id: "provider_lookup",
    label: "Provider Verification",
    description: "Verifies NPI numbers, credentials, and specialty for any US healthcare provider.",
    verticals: ["health_ems"],
    costPerSession: 0.00,
    costLabel: "Free — CMS public data",
    tierRequired: "free",
    requiresRaas: false,
    serviceName: "nppes",
    envKey: null,
  },
  drug_reference: {
    id: "drug_reference",
    label: "Drug Reference",
    description: "Pulls FDA drug labels, dosing, contraindications, and recall alerts.",
    verticals: ["health_ems"],
    costPerSession: 0.00,
    costLabel: "Free — FDA public data",
    tierRequired: "free",
    requiresRaas: false,
    serviceName: "openfda",
    envKey: null,
  },

  // ── AUTO DEALER ──
  nhtsa_vin: {
    id: "nhtsa_vin",
    label: "VIN Decode",
    description: "Decodes any VIN into make, model, year, engine specs, and safety recalls instantly.",
    verticals: ["auto_dealer"],
    costPerSession: 0.00,
    costLabel: "Free — NHTSA public data",
    tierRequired: "free",
    requiresRaas: false,
    serviceName: "nhtsa",
    envKey: null,
  },
  vincario: {
    id: "vincario",
    label: "Vehicle Market Value",
    description: "Pulls current market value, stolen vehicle check, and 50+ extended specs via VIN.",
    verticals: ["auto_dealer"],
    costPerSession: 0.20,
    costLabel: "~$0.20 per VIN lookup",
    tierRequired: "paid",
    requiresRaas: false,
    creditCost: 20,
    serviceName: "vincario",
    envKey: "VINCARIO_API_KEY",
  },

  // ── WEB3 ──
  helius: {
    id: "helius",
    label: "Solana Blockchain",
    description: "Reads wallet balances, transaction history, and token holdings from Solana via Helius.",
    verticals: ["web3"],
    costPerSession: 0.00,
    costLabel: "Free — included with The Ledger",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "helius",
    envKey: "HELIUS_API_KEY",
  },
  alchemy: {
    id: "alchemy",
    label: "Polygon Blockchain",
    description: "Reads equity records and cap table data from Polygon via Alchemy.",
    verticals: ["web3"],
    costPerSession: 0.00,
    costLabel: "Free — included with The Ledger",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "alchemy",
    envKey: "ALCHEMY_POLYGON_API_KEY",
  },
  snapshot: {
    id: "snapshot",
    label: "Governance Voting",
    description: "Reads Snapshot governance proposals, vote counts, and participation metrics.",
    verticals: ["web3"],
    costPerSession: 0.00,
    costLabel: "Free — public GraphQL",
    tierRequired: "free",
    requiresRaas: false,
    serviceName: "snapshot",
    envKey: null,
  },
  crossmint: {
    id: "crossmint",
    label: "Crossmint NFT Minting",
    description: "Mints NFTs and manages digital collectibles on Polygon and Solana via Crossmint.",
    verticals: ["web3"],
    costPerSession: 0.00,
    costLabel: "Per-mint pricing",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "crossmint",
    envKey: "CROSSMINT_SERVER_API_KEY",
  },

  // ── COMMUNICATIONS (cross-vertical) ──
  sendgrid: {
    id: "sendgrid",
    label: "Email Delivery",
    description: "Sends transactional and campaign emails through SendGrid.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "aviation", "web3", "health_ems", "government", "marketing", "platform"],
    costPerSession: 0.00,
    costLabel: "Included with platform",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "sendgrid",
    envKey: "SENDGRID_API_KEY",
  },
  twilio: {
    id: "twilio",
    label: "SMS & Voice",
    description: "Sends SMS messages and handles voice calls through Twilio.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "aviation", "web3", "health_ems", "government", "marketing", "platform"],
    costPerSession: 0.01,
    costLabel: "~$0.01 per SMS",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "twilio",
    envKey: "TWILIO_ACCOUNT_SID",
  },

  // ── ACCOUNTING & FINANCE (cross-vertical) ──
  quickbooks: {
    id: "quickbooks",
    label: "QuickBooks",
    description: "Reads subscriber QuickBooks data — income, expenses, and property financials.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "aviation", "platform"],
    costPerSession: 0.00,
    costLabel: "Free — subscriber authorizes access",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "quickbooks",
    envKey: "QB_CLIENT_ID",
  },
  plaid: {
    id: "plaid",
    label: "Bank Accounts",
    description: "Reads cash positions and transaction data from connected bank accounts via Plaid.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "aviation", "platform"],
    costPerSession: 0.00,
    costLabel: "Free — subscriber authorizes access",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "plaid",
    envKey: null, // Future — Plaid keys not yet provisioned
  },
  stripe: {
    id: "stripe",
    label: "Stripe Revenue",
    description: "Reads MRR, subscriber count, churn, and revenue data from Stripe.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "aviation", "web3", "platform"],
    costPerSession: 0.00,
    costLabel: "Included with platform",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "stripe",
    envKey: "STRIPE_SECRET_KEY",
  },

  // ── SOCIAL & MARKETING (OAuth-connected, cross-vertical) ──
  meta_posting: {
    id: "meta_posting",
    label: "Meta (Facebook & Instagram)",
    description: "Publishes content to Facebook Pages and Instagram accounts. Subscriber authorizes via OAuth.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "aviation", "web3", "health_ems", "marketing"],
    costPerSession: 0.00,
    costLabel: "Free — subscriber authorizes access",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "meta",
    envKey: "META_APP_ID",
    oauthRequired: true,
  },
  tiktok_posting: {
    id: "tiktok_posting",
    label: "TikTok",
    description: "Publishes video content to TikTok. Subscriber authorizes via OAuth.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "aviation", "web3", "platform"],
    costPerSession: 0.00,
    costLabel: "Free — subscriber authorizes access",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "tiktok",
    envKey: "TIKTOK_CLIENT_KEY",
    oauthRequired: true,
  },
  unified: {
    id: "unified",
    label: "Unified Social Posting",
    description: "Publishes content across all connected social platforms via Unified.to.",
    verticals: ["marketing", "real_estate_development", "auto_dealer", "solar_vpp", "aviation", "web3", "health_ems", "platform"],
    costPerSession: 0.00,
    costLabel: "Per-post pricing",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "unified",
    envKey: "UNIFIED_API_KEY",
    oauthRequired: true,
  },
  google_business_posting: {
    id: "google_business_posting",
    label: "Google Business Profile",
    description: "Publishes posts and updates to Google Business Profile. Subscriber authorizes via OAuth.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "health_ems", "marketing"],
    costPerSession: 0.00,
    costLabel: "Free — subscriber authorizes access",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "google_business",
    envKey: "GOOGLE_OAUTH_CLIENT_ID",
    oauthRequired: true,
  },
  linkedin_posting: {
    id: "linkedin_posting",
    label: "LinkedIn",
    description: "Publishes professional content to LinkedIn. Subscriber authorizes via OAuth.",
    verticals: ["real_estate_development", "auto_dealer", "solar_vpp", "aviation", "web3", "platform"],
    costPerSession: 0.00,
    costLabel: "Free — subscriber authorizes access",
    tierRequired: "paid",
    requiresRaas: false,
    serviceName: "linkedin",
    envKey: "LINKEDIN_CLIENT_ID",
    oauthRequired: true,
  },
};

/**
 * Get connectors available for a vertical.
 * @param {string} vertical
 * @returns {Object[]}
 */
// Normalize legacy vertical names to canonical names
const VERTICAL_ALIASES = {
  "real-estate": "real_estate_development",
  "re": "real_estate_development",
  "auto-dealer": "auto_dealer",
  "auto": "auto_dealer",
  "solar": "solar_vpp",
  "health-ems": "health_ems",
  "health": "health_ems",
  "healthcare": "health_ems",
};

function getConnectorsForVertical(vertical) {
  const normalized = VERTICAL_ALIASES[vertical] || vertical;
  return Object.values(CONNECTORS).filter(c => c.verticals.includes(normalized));
}

/**
 * Get estimated cost per session for a set of connector IDs.
 * @param {string[]} connectorIds
 * @returns {number}
 */
function estimateSessionCost(connectorIds) {
  return connectorIds.reduce((sum, id) => sum + (CONNECTORS[id]?.costPerSession || 0), 0);
}

module.exports = { CONNECTORS, getConnectorsForVertical, estimateSessionCost };
