// LIVE Stripe product/price IDs for the Box plans. Generated by setup-boxes.
// $99/mo base + tiered seat price (first 5 seats free, then $5). Do not hand-edit.
module.exports = {
  "businessInABox": {
    "productId": "prod_UhQcwXznCVPSCO",
    "basePriceId": "price_1Ti1lBBYvxF0jBHyRN9zEkoz",
    "seatPriceId": "price_1Ti1lBBYvxF0jBHyzQlYE4kr"
  },
  "academiaInABox": {
    "productId": "prod_UhQc58VEPobkia",
    "basePriceId": "price_1Ti1lCBYvxF0jBHy78Xk8hEC",
    "seatPriceId": "price_1Ti1lCBYvxF0jBHyZGGA9F78"
  }
};
