// LIVE Stripe product/price IDs for the Box plans. Generated by setup-boxes.
// $99/mo base + tiered seat price (first 5 seats free, then $5). Do not hand-edit.
//
// Known gap (CODEX 76 §6 item 4 / CODEX 88 §4 item 1), checked this pass —
// NOT reconciled because it does not block the overage-billing build: this
// file has live Stripe wiring but no allowance/overage-rate data; the
// allowance math lives in config/pricing.js's businessInABox/education
// blocks under DIFFERENT keys (businessInABox/education here vs.
// businessInABox/academiaInABox... wait, actually matching key names
// EXCEPT education vs academiaInABox — see pricing.js). Institution overage
// (services/billing/institutionOverage.js) doesn't need a merged single
// source: it reads the tenant's own stripeCustomerId/boxPlanStripeSubscriptionId
// directly off the tenant doc for charging, and pricing.js's allowance
// numbers for the visibility-only interaction estimate — it never needs to
// cross-reference a plan-type into THIS file. Also still missing here: any
// metered price for AI-interaction-volume overage — none exists yet (see
// pricing.js's aiInteractionOverageStripePriceId, currently null; no live
// Stripe API credential in this session's sandbox to create one).
module.exports = {
  "businessInABox": {
    "productId": "prod_UhQcwXznCVPSCO",
    "basePriceId": "price_1Ti1lBBYvxF0jBHyRN9zEkoz",
    "seatPriceId": "price_1Ti1lBBYvxF0jBHyzQlYE4kr"
  },
  "academiaInABox": {
    "productId": "prod_UhQc58VEPobkia",
    "basePriceId": "price_1Ti1lCBYvxF0jBHy78Xk8hEC",
    "seatPriceId": "price_1Ti1lCBYvxF0jBHyZGGA9F78"
  },
  // Per-vertical Business/Academia Stacks — 2026-08-22, Sean: same $99/mo
  // pricing as the generic boxes above, distinct Products for sales
  // reporting/management clarity. Created by
  // billing/setupVerticalBoxProducts.js.
  "msr-in-a-box": {
    "productId": "prod_V7jA56CFUXcJ11",
    "basePriceId": "price_1U7Ti2BYvxF0jBHyEXGo00yy",
    "seatPriceId": "price_1U7TrSBYvxF0jBHyobeUzpxO"
  },
  "title-in-a-box": {
    "productId": "prod_V7jEEvKSthzl60",
    "basePriceId": "price_1U7Tm2BYvxF0jBHy4QJDTVWh",
    "seatPriceId": "price_1U7Tm2BYvxF0jBHyU0f05drS"
  },
  "dpp-in-a-box": {
    "productId": "prod_V7jEA0YmqNhkJo",
    "basePriceId": "price_1U7Tm2BYvxF0jBHyWnrsdEKf",
    "seatPriceId": "price_1U7Tm2BYvxF0jBHyDmhEYvM1"
  },
  "aviation-in-a-box": {
    "productId": "prod_V7jEUuo66PrslZ",
    "basePriceId": "price_1U7Tm3BYvxF0jBHyYueeoynA",
    "seatPriceId": "price_1U7Tm3BYvxF0jBHyInxfgPVw"
  },
  "nursing-in-a-box": {
    "productId": "prod_V7jE1JqQeZVCgo",
    "basePriceId": "price_1U7Tm3BYvxF0jBHys8s8iT6q",
    "seatPriceId": "price_1U7Tm3BYvxF0jBHy4v5wn8tK"
  },
  "education-in-a-box": {
    "productId": "prod_V7jEyENgJbSUEU",
    "basePriceId": "price_1U7Tm4BYvxF0jBHyVfoxDnjV",
    "seatPriceId": "price_1U7Tm4BYvxF0jBHyF1gHJZFW"
  }
};
