import React, { useState } from "react";

const API_BASE = import.meta.env.VITE_API_BASE || "https://titleapp-frontdoor.titleapp-core.workers.dev";

const S = {
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 10000 },
  card: { background: "white", borderRadius: 16, padding: "40px 32px", maxWidth: 520, width: "90%", boxShadow: "0 8px 40px rgba(0,0,0,0.2)" },
  title: { fontSize: 20, fontWeight: 700, color: "#111827", marginBottom: 16 },
  text: { fontSize: 14, color: "#4b5563", lineHeight: 1.7, marginBottom: 24 },
  btn: { width: "100%", padding: "14px 24px", background: "#7c3aed", color: "white", border: "none", borderRadius: 10, fontSize: 15, fontWeight: 600, cursor: "pointer" },
  btnDisabled: { width: "100%", padding: "14px 24px", background: "#d1d5db", color: "#9ca3af", border: "none", borderRadius: 10, fontSize: 15, fontWeight: 600, cursor: "not-allowed" },
  badge: { display: "inline-block", padding: "4px 12px", borderRadius: 8, fontSize: 11, fontWeight: 700, marginBottom: 16 },
};

const GATE_CONFIG = {
  simulation: {
    title: "Simulation Disclaimer",
    text: "Scenarios generated by this worker are educational simulations only. They are not clinical protocols, standing orders, or patient care directives. Do not use simulation outputs for actual patient care decisions.",
    badgeColor: "#f59e0b",
    badgeBg: "#fef3c7",
    ackField: "simulationAck",
  },
  jurisdiction: {
    title: "Jurisdiction Acknowledgment",
    text: "This worker uses TitleApp platform-default content. It is educational reference material only until you or the worker creator uploads jurisdiction-specific protocols, scope of practice rules, and employer policies. Do you understand?",
    badgeColor: "#dc2626",
    badgeBg: "#fee2e2",
    ackField: "chartItJurisdictionAck",
  },
  clinical: {
    title: "Clinical Reference Disclaimer",
    text: "This worker is a reference tool only. It does not provide clinical guidance, diagnosis, or treatment recommendations. It is not a substitute for clinical judgment, medical director authority, or institutional protocols. Do not use outputs for patient care decisions.",
    badgeColor: "#dc2626",
    badgeBg: "#fee2e2",
    ackField: "backMeUpDisclaimerAck",
  },
};

/**
 * JurisdictionAckModal — fires on first use of Chart It / Back Me Up / Learn It workers.
 *
 * @param {string} gateType — "simulation" | "jurisdiction" | "clinical"
 * @param {string} workerId — worker ID for audit trail
 * @param {string} lane — worker lane name
 * @param {function} onAcknowledge — called when user accepts
 * @param {function} onCancel — called when user cancels
 */
export default function JurisdictionAckModal({ gateType, workerId, lane, onAcknowledge, onCancel }) {
  const [submitting, setSubmitting] = useState(false);
  const config = GATE_CONFIG[gateType];

  if (!config) return null;

  async function handleAcknowledge() {
    setSubmitting(true);
    try {
      const token = localStorage.getItem("ID_TOKEN");
      const tenantId = localStorage.getItem("TENANT_ID");
      await fetch(`${API_BASE}/api?path=/v1/he:ack`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          tenantId,
          workerId,
          lane,
          ackType: gateType,
          ackText: config.text,
        }),
      });
      // Set localStorage flag so modal doesn't fire again
      localStorage.setItem(`HE_ACK_${config.ackField}`, "true");
      onAcknowledge();
    } catch (e) {
      console.error("Acknowledgment failed:", e);
    }
    setSubmitting(false);
  }

  return (
    <div style={S.overlay}>
      <div style={S.card}>
        <div style={{ ...S.badge, color: config.badgeColor, background: config.badgeBg }}>Required</div>
        <div style={S.title}>{config.title}</div>
        <div style={S.text}>{config.text}</div>
        <button
          style={submitting ? S.btnDisabled : S.btn}
          onClick={handleAcknowledge}
          disabled={submitting}
        >
          {submitting ? "Recording..." : "I Understand"}
        </button>
        {onCancel && (
          <button
            style={{ ...S.btn, background: "transparent", color: "#6b7280", marginTop: 8, border: "1px solid #e5e7eb" }}
            onClick={onCancel}
          >
            Go Back
          </button>
        )}
      </div>
    </div>
  );
}

/**
 * Check if a user has already acknowledged a gate.
 * Checks localStorage first (fast), falls back to Firestore check if needed.
 */
export function hasAcknowledged(gateType) {
  const config = GATE_CONFIG[gateType];
  if (!config) return true;
  return localStorage.getItem(`HE_ACK_${config.ackField}`) === "true";
}

/**
 * Determine which gate type (if any) is required for a given lane.
 * Returns null if no gate needed.
 */
export function getRequiredGate(lane) {
  const laneLower = (lane || "").toLowerCase().replace(/\s+/g, "_");
  if (laneLower === "learn_it" || laneLower === "learn it") return "simulation";
  if (laneLower === "chart_it" || laneLower === "chart it") return "jurisdiction";
  if (laneLower === "back_me_up" || laneLower === "back me up") return "clinical";
  return null;
}
