"use strict";

/**
 * contractReview.js — Sterling's structured contract findings (CODEX 103,
 * Section 1b).
 *
 * Design invariants from the spec, enforced here in code (not by
 * instructing the model and trusting it):
 *  - Fixed checklist, always all 7 categories — an empty/partial findings
 *    list is structurally impossible; anything the model skips becomes an
 *    explicit "not_reviewed" finding.
 *  - No severity/likelihood scoring, ever.
 *  - sourceText must be a real, exact quote from the document — verified
 *    here, in code, before a finding is ever returned. A finding that
 *    fails is rejected, not paraphrased or "fixed."
 *  - Hidden-content scanning runs in code BEFORE the model reads the
 *    document. Honest limitation: this operates on already-extracted
 *    plain text, so it strips zero-width/invisible unicode (a real hiding
 *    mechanism it CAN see) but cannot see font color/size — that needs
 *    raw PDF/docx structure, which no extraction pipeline in this
 *    codebase currently provides. Named here, not overclaimed.
 *  - A concrete, enumerated "material contract" threshold — Sterling is
 *    never the sole reviewer above it.
 */

const CHECKLIST_CATEGORIES = [
  "indemnity",
  "limitation_of_liability",
  "termination",
  "ip_assignment",
  "governing_law",
  "auto_renewal",
  "exclusivity",
];

// Zero-width / invisible unicode sometimes used to hide text or split up
// trigger phrases so a naive scanner misses them.
const ZERO_WIDTH_RE = /[​-‏⁠﻿]/g;

// Heuristic patterns for text that reads as an instruction to an AI reader,
// not a contract term — the shape of attack this design targets. These are
// advisory findings for Sean, generated by code (never by the model, which
// is exactly the actor this defense doesn't trust to self-report).
const INJECTION_PATTERNS = [
  /ignore (all|any|the) (previous|prior|above) instructions/i,
  /you are (now|actually) (a|an|the)\b/i,
  /disregard (all|any|the) (previous|prior|above)/i,
  /report (this|these|it) as (standard|no concerns|clean|fine)/i,
  /do not (flag|mention|report) (this|any)/i,
  /\[\[?\s*(system|assistant|ai)\s*:/i,
];

function scanForHiddenContent(rawText) {
  const findings = [];
  const zeroWidthCount = (rawText.match(ZERO_WIDTH_RE) || []).length;
  if (zeroWidthCount > 3) {
    findings.push({
      type: "hidden_content",
      detail: `${zeroWidthCount} zero-width/invisible unicode characters found in the extracted document text — a known way to hide or obfuscate content from a plain read. Stripped before this document was sent for review.`,
    });
  }
  const cleanedText = rawText.replace(ZERO_WIDTH_RE, "");
  for (const re of INJECTION_PATTERNS) {
    const m = cleanedText.match(re);
    if (m) {
      findings.push({
        type: "possible_injection",
        detail: `Text resembling an instruction directed at an AI reader was found — review this passage yourself before trusting any summary of it: "${m[0]}"`,
        sourceText: m[0],
      });
    }
  }
  return { findings, cleanedText };
}

// $10,000 is a placeholder threshold — the spec calls this "TBD at build
// time." Flagged here explicitly rather than silently treated as settled.
const MATERIAL_DOLLAR_THRESHOLD = 10000;

function detectMaterialTriggers(findings, text) {
  const reasons = [];
  const presentCats = new Set(
    findings.filter((f) => f.presence === "present" || f.presence === "unusual").map((f) => f.category)
  );
  if (presentCats.has("ip_assignment")) reasons.push("IP assignment clause present");
  if (presentCats.has("exclusivity")) reasons.push("Exclusivity clause present");
  if (/personal guarant/i.test(text)) reasons.push("Possible personal-guarantee language found");
  if (/\bequity\b|\bstock\b|\bwarrant\b|\boption pool\b/i.test(text)) reasons.push("Possible equity-related language found");
  const dollarMatches = text.match(/\$\s?[\d,]{4,}(\.\d{2})?/g) || [];
  for (const m of dollarMatches) {
    const n = Number(m.replace(/[^\d.]/g, ""));
    if (n >= MATERIAL_DOLLAR_THRESHOLD) {
      reasons.push(`Dollar amount ≥ $${MATERIAL_DOLLAR_THRESHOLD.toLocaleString()} found (${m.trim()})`);
      break;
    }
  }
  return reasons;
}

function parseModelFindings(raw) {
  const jsonMatch = raw.match(/\[[\s\S]*\]/);
  const parsed = JSON.parse(jsonMatch ? jsonMatch[0] : raw);
  if (!Array.isArray(parsed)) throw new Error("model output was not a JSON array");
  return parsed;
}

/**
 * @param {object} args
 * @param {string} args.documentName
 * @param {string} args.documentText - real extracted text, not a summary
 * @param {object} args.anthropicClient - an initialized Anthropic SDK client
 */
async function reviewContract({ documentName, documentText, anthropicClient }) {
  if (!documentText || typeof documentText !== "string" || documentText.trim().length < 20) {
    throw new Error("reviewContract: documentText is required and must be real extracted contract text, not a summary");
  }
  if (!anthropicClient) throw new Error("reviewContract: anthropicClient is required");

  const { findings: hiddenContentFindings, cleanedText } = scanForHiddenContent(documentText);

  const prompt = `You are reviewing a contract for structured findings only. You do not give legal advice, an opinion on enforceability, or a recommendation to sign or not sign.

Check these ${CHECKLIST_CATEGORIES.length} categories, every one, no skipping: ${CHECKLIST_CATEGORIES.join(", ")}.

Return a JSON array of EXACTLY ${CHECKLIST_CATEGORIES.length} objects, one per category, each with:
- "category": the category name exactly as listed above
- "presence": "present", "absent", or "unusual"
- "sourceText": the EXACT verbatim text from the document that this finding is about (required when presence is "present" or "unusual"; omit entirely when "absent" — never paraphrase, never invent text not literally in the document)
- "questionForCounsel": a question for a human to resolve — never an answer, opinion, or recommendation, and never a statement that a term is "standard" or "fine"

DOCUMENT: ${documentName || "(untitled)"}
---
${cleanedText}
---

Return ONLY the JSON array. No prose before or after it.`;

  const resp = await anthropicClient.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 4096,
    messages: [{ role: "user", content: prompt }],
  });

  const rawText = (resp.content || []).map((b) => b.text || "").join("");
  let modelFindings;
  try {
    modelFindings = parseModelFindings(rawText);
  } catch (e) {
    throw new Error(`reviewContract: model output was not valid JSON — refusing to guess at findings (${e.message})`);
  }

  const verified = [];
  const rejected = [];
  const seenCategories = new Set();

  for (const f of modelFindings) {
    const category = CHECKLIST_CATEGORIES.includes(f && f.category) ? f.category : null;
    if (!category) { rejected.push({ raw: f, reason: "unknown_or_missing_category" }); continue; }
    if (seenCategories.has(category)) { rejected.push({ raw: f, reason: "duplicate_category" }); continue; }

    const presence = ["present", "absent", "unusual"].includes(f.presence) ? f.presence : null;
    if (!presence) { rejected.push({ raw: f, reason: "invalid_presence" }); continue; }

    let sourceText = null;
    if (presence !== "absent") {
      const candidate = typeof f.sourceText === "string" ? f.sourceText.trim() : "";
      // The load-bearing check: code, not the model, verifies this text is
      // real. Reject rather than trust a plausible-looking quote.
      if (!candidate || !cleanedText.includes(candidate)) {
        rejected.push({ raw: f, reason: "sourceText_not_verified_in_document" });
        continue;
      }
      sourceText = candidate;
    }

    seenCategories.add(category);
    verified.push({
      category,
      presence,
      sourceText,
      questionForCounsel: typeof f.questionForCounsel === "string" && f.questionForCounsel.trim()
        ? f.questionForCounsel.trim()
        : `${category.replace(/_/g, " ")} was not given a specific question — have counsel review this category directly.`,
    });
  }

  // Coverage guarantee: a category the model skipped, or that was rejected
  // for a bad sourceText, still gets an explicit entry — never silently
  // missing, never indistinguishable from "checked and clean."
  for (const category of CHECKLIST_CATEGORIES) {
    if (!seenCategories.has(category)) {
      verified.push({
        category,
        presence: "not_reviewed",
        sourceText: null,
        questionForCounsel: `This category could not be verified automatically (model output was rejected or missing) — have counsel check ${category.replace(/_/g, " ")} manually.`,
      });
    }
  }

  const materialReasons = detectMaterialTriggers(verified, cleanedText);

  return {
    documentName: documentName || null,
    findings: verified,
    rejectedFindingsCount: rejected.length,
    hiddenContentFindings,
    requiresMandatoryHumanReview: materialReasons.length > 0,
    materialReasons,
    reviewedAt: new Date().toISOString(),
  };
}

module.exports = {
  reviewContract,
  scanForHiddenContent,
  detectMaterialTriggers,
  CHECKLIST_CATEGORIES,
  MATERIAL_DOLLAR_THRESHOLD,
};
